/*
 * OpenMPIR.cpp - Minimal ompparser compatibility implementation using ROUP
 *
 * This provides ONLY the implementation (.cpp), using ompparser's headers
 * from the git submodule at compat/ompparser/ompparser/src/
 *
 * Copyright (c) 2025 ROUP Project
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <OpenMPIR.h>
#include <cstring>
#include <sstream>
#include <string>

// Include ROUP constants (auto-generated by build.rs from src/c_api.rs)
#include <roup_constants.h>

// ============================================================================
// ROUP C API Forward Declarations
// ============================================================================

extern "C" {
    // Opaque types from ROUP
    struct OmpDirective;
    struct OmpClause;
    struct OmpClauseIterator;

    // Core parsing
    OmpDirective* roup_parse(const char* input);
    void roup_directive_free(OmpDirective* directive);

    // Directive queries
    int32_t roup_directive_kind(const OmpDirective* directive);
    int32_t roup_directive_clause_count(const OmpDirective* directive);
    OmpClauseIterator* roup_directive_clauses_iter(const OmpDirective* directive);

    // Iterator operations (updated API with out parameter)
    int32_t roup_clause_iterator_next(OmpClauseIterator* iter, const OmpClause** out);
    void roup_clause_iterator_free(OmpClauseIterator* iter);

    // Clause queries
    int32_t roup_clause_kind(const OmpClause* clause);
}

// ============================================================================
// Global State
// ============================================================================

static OpenMPBaseLang current_lang = Lang_C;

// Language prefix constants - defined once to avoid manual synchronization
static constexpr const char FORTRAN_PREFIX[] = "!$omp";       // Fortran prefix (lowercase)
static constexpr const char FORTRAN_PREFIX_UPPER[] = "!$OMP"; // Fortran prefix (uppercase)
static constexpr const char C_PRAGMA_PREFIX[] = "#pragma";    // C/C++ pragma prefix
// Compile-time string lengths: sizeof() includes null terminator, subtract 1 for actual length
static constexpr size_t FORTRAN_PREFIX_LEN = sizeof(FORTRAN_PREFIX) - 1;
static constexpr size_t C_PRAGMA_PREFIX_LEN = sizeof(C_PRAGMA_PREFIX) - 1;

// setLang is a C++ function (not extern "C") to match ompparser API
void setLang(OpenMPBaseLang lang) {
    current_lang = lang;
}

// ============================================================================
// Helper Functions
// ============================================================================

static OpenMPDirectiveKind mapRoupToOmpparserDirective(int32_t roup_kind) {
    // Complete ROUP to ompparser directive mapping (all 132 OpenMP directives)
    // See src/c_api.rs:directive_name_to_kind() for ROUP code assignments
    switch (roup_kind) {
        case 0: return OMPD_allocate;
        case 4: return OMPD_atomic;
        case 10: return OMPD_barrier;
        case 14: return OMPD_cancel;
        case 15: return OMPD_cancellation_point;
        case 16: return OMPD_critical;
        case 18: return OMPD_declare_mapper;
        case 19: return OMPD_declare_reduction;
        case 20: return OMPD_declare_simd;
        case 21: return OMPD_declare_target;
        case 23: return OMPD_depobj;
        case 25: return OMPD_distribute;
        case 26: return OMPD_distribute_parallel_for;
        case 27: return OMPD_distribute_parallel_for_simd;
        case 30: return OMPD_distribute_simd;
        case 31: return OMPD_distribute_parallel_do;
        case 32: return OMPD_distribute_parallel_do_simd;
        case 33: return OMPD_do;
        case 34: return OMPD_do_simd;
        case 36: return OMPD_end_declare_target;
        case 39: return OMPD_flush;
        case 42: return OMPD_for;
        case 43: return OMPD_for_simd;
        case 46: return OMPD_loop;
        case 51: return OMPD_master;
        case 52: return OMPD_master_taskloop;
        case 53: return OMPD_master_taskloop_simd;
        case 54: return OMPD_metadirective;
        case 57: return OMPD_ordered;
        case 58: return OMPD_parallel;
        case 59: return OMPD_parallel_do;
        case 60: return OMPD_parallel_do_simd;
        case 61: return OMPD_parallel_for;
        case 62: return OMPD_parallel_for_simd;
        case 63: return OMPD_parallel_loop;
        case 68: return OMPD_parallel_master;
        case 69: return OMPD_parallel_master_taskloop;
        case 70: return OMPD_parallel_master_taskloop_simd;
        case 71: return OMPD_parallel_sections;
        case 72: return OMPD_requires;
        case 74: return OMPD_scan;
        case 75: return OMPD_section;
        case 76: return OMPD_sections;
        case 77: return OMPD_simd;
        case 78: return OMPD_single;
        case 81: return OMPD_target;
        case 82: return OMPD_target_data;
        case 83: return OMPD_target_enter_data;
        case 84: return OMPD_target_exit_data;
        case 88: return OMPD_target_parallel;
        case 89: return OMPD_target_parallel_do;
        case 90: return OMPD_target_parallel_do_simd;
        case 91: return OMPD_target_parallel_for;
        case 92: return OMPD_target_parallel_for_simd;
        case 93: return OMPD_target_parallel_loop;
        case 95: return OMPD_target_simd;
        case 96: return OMPD_target_teams;
        case 97: return OMPD_target_teams_distribute;
        case 98: return OMPD_target_teams_distribute_parallel_do;
        case 99: return OMPD_target_teams_distribute_parallel_do_simd;
        case 100: return OMPD_target_teams_distribute_parallel_for;
        case 101: return OMPD_target_teams_distribute_parallel_for_simd;
        case 104: return OMPD_target_teams_distribute_simd;
        case 105: return OMPD_target_teams_loop;
        case 107: return OMPD_target_update;
        case 108: return OMPD_task;
        case 110: return OMPD_taskgroup;
        case 112: return OMPD_taskloop;
        case 113: return OMPD_taskloop_simd;
        case 114: return OMPD_taskwait;
        case 115: return OMPD_taskyield;
        case 116: return OMPD_teams;
        case 117: return OMPD_teams_distribute;
        case 118: return OMPD_teams_distribute_parallel_do;
        case 119: return OMPD_teams_distribute_parallel_do_simd;
        case 120: return OMPD_teams_distribute_parallel_for;
        case 121: return OMPD_teams_distribute_parallel_for_simd;
        case 124: return OMPD_teams_distribute_simd;
        case 125: return OMPD_teams_loop;
        case 127: return OMPD_threadprivate;
        case 128: return OMPD_tile;
        case 129: return OMPD_unroll;
        case 131: return OMPD_workshare;
        default: return OMPD_unknown;
    }
}

static OpenMPClauseKind mapRoupToOmpparserClause(int32_t roup_kind) {
    // ROUP clause kind mapping using named constants from roup_constants.h
    // Single source of truth: src/c_api.rs:convert_clause()
    switch (roup_kind) {
        case ROUP_CLAUSE_NUM_THREADS:   return OMPC_num_threads;
        case ROUP_CLAUSE_IF:            return OMPC_if;
        case ROUP_CLAUSE_PRIVATE:       return OMPC_private;
        case ROUP_CLAUSE_SHARED:        return OMPC_shared;
        case ROUP_CLAUSE_FIRSTPRIVATE:  return OMPC_firstprivate;
        case ROUP_CLAUSE_LASTPRIVATE:   return OMPC_lastprivate;
        case ROUP_CLAUSE_REDUCTION:     return OMPC_reduction;
        case ROUP_CLAUSE_SCHEDULE:      return OMPC_schedule;
        case ROUP_CLAUSE_COLLAPSE:      return OMPC_collapse;
        case ROUP_CLAUSE_ORDERED:       return OMPC_ordered;
        case ROUP_CLAUSE_NOWAIT:        return OMPC_nowait;
        case ROUP_CLAUSE_DEFAULT:       return OMPC_default;
        default:                        return OMPC_unknown;
    }
}

// ============================================================================
// Main Entry Point
// ============================================================================

extern "C" {

OpenMPDirective* parseOpenMP(const char* input, void* exprParse(const char* expr)) {
    if (!input || input[0] == '\0') {
        return nullptr;
    }

    // Validate input length using constant from ROUP C API
    // Use strnlen to safely handle potentially untrusted/non-null-terminated input
    const size_t input_len = strnlen(input, ROUP_MAX_PRAGMA_LENGTH);
    if (input_len == ROUP_MAX_PRAGMA_LENGTH) {
        return nullptr;  // Input too long or not null-terminated within limit
    }

    // Determine input format based on current language mode
    std::string input_str(input, input_len);

    // Handle different language pragmas
    if (current_lang == Lang_Fortran) {
        // Fortran uses !$omp prefix - add if missing (case-insensitive check)
        const bool has_prefix =
            input_str.length() >= FORTRAN_PREFIX_LEN &&
            (input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX) == 0 ||
             input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX_UPPER) == 0);
        if (!has_prefix) {
            input_str = std::string(FORTRAN_PREFIX) + " " + input_str;
        }
    } else {
        // C/C++ use #pragma omp prefix - add if missing
        // compare() returns 0 if strings match, non-zero otherwise
        if (input_str.compare(0, C_PRAGMA_PREFIX_LEN, C_PRAGMA_PREFIX) != 0) {
            input_str = std::string(C_PRAGMA_PREFIX) + " " + input_str;
        }
    }

    // Call ROUP parser
    OmpDirective* roup_dir = roup_parse(input_str.c_str());
    if (!roup_dir) {
        return nullptr;
    }

    // Get directive kind from ROUP
    int32_t roup_kind = roup_directive_kind(roup_dir);
    OpenMPDirectiveKind kind = mapRoupToOmpparserDirective(roup_kind);

    // Create ompparser-compatible directive
    // Use ompparser's actual constructor: OpenMPDirective(kind, lang, line, col)
    OpenMPDirective* dir = new OpenMPDirective(kind, current_lang, 0, 0);

    // Convert clauses using ompparser's addOpenMPClause method
    OmpClauseIterator* iter = roup_directive_clauses_iter(roup_dir);
    if (iter) {
        const OmpClause* roup_clause;
        while (roup_clause_iterator_next(iter, &roup_clause) == 1) {
            int32_t roup_kind_clause = roup_clause_kind(roup_clause);
            OpenMPClauseKind clause_kind = mapRoupToOmpparserClause(roup_kind_clause);

            // Use public variadic version: addOpenMPClause(int kind, ...)
            // Cast to int and pass just the kind for basic clause support
            dir->addOpenMPClause(static_cast<int>(clause_kind));
        }
        roup_clause_iterator_free(iter);
    }

    // Free ROUP directive (we've extracted what we need)
    roup_directive_free(roup_dir);

    return dir;
}

} // extern "C"
