/*
 * OpenMPIR.cpp - Minimal ompparser compatibility implementation using ROUP
 *
 * This provides ONLY the implementation (.cpp), using ompparser's headers
 * from the git submodule at compat/ompparser/ompparser/src/
 *
 * Copyright (c) 2025 ROUP Project
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <OpenMPIR.h>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>

// Include ROUP constants (auto-generated by build.rs from src/c_api.rs)
#include <roup_constants.h>

// ============================================================================
// ROUP C API Forward Declarations
// ============================================================================

extern "C" {
    // Opaque types from ROUP
    struct OmpDirective;
    struct OmpClause;
    struct OmpClauseIterator;

    // Core parsing
    OmpDirective* roup_parse(const char* input);
    void roup_directive_free(OmpDirective* directive);

    // Directive queries
    int32_t roup_directive_kind(const OmpDirective* directive);
    const char* roup_directive_name(const OmpDirective* directive);
    const char* roup_directive_parameter(const OmpDirective* directive);
    int32_t roup_directive_clause_count(const OmpDirective* directive);
    OmpClauseIterator* roup_directive_clauses_iter(const OmpDirective* directive);

    // Iterator operations (updated API with out parameter)
    int32_t roup_clause_iterator_next(OmpClauseIterator* iter, const OmpClause** out);
    void roup_clause_iterator_free(OmpClauseIterator* iter);

    // Clause queries
    int32_t roup_clause_kind(const OmpClause* clause);
    const char* roup_clause_text(const OmpClause* clause);

    // Clause parameter queries
    int32_t roup_clause_schedule_kind(const OmpClause* clause);
    int32_t roup_clause_reduction_operator(const OmpClause* clause);
    int32_t roup_clause_default_data_sharing(const OmpClause* clause);
    int32_t roup_clause_proc_bind(const OmpClause* clause);
}

// ============================================================================
// Global State
// ============================================================================

static OpenMPBaseLang current_lang = Lang_C;

// Language prefix constants - defined once to avoid manual synchronization
static constexpr const char FORTRAN_PREFIX[] = "!$omp";       // Fortran prefix (lowercase)
static constexpr const char FORTRAN_PREFIX_UPPER[] = "!$OMP"; // Fortran prefix (uppercase)
static constexpr const char C_PRAGMA_PREFIX[] = "#pragma";    // C/C++ pragma prefix
// Compile-time string lengths: sizeof() includes null terminator, subtract 1 for actual length
static constexpr size_t FORTRAN_PREFIX_LEN = sizeof(FORTRAN_PREFIX) - 1;
static constexpr size_t C_PRAGMA_PREFIX_LEN = sizeof(C_PRAGMA_PREFIX) - 1;

// setLang function with C++ linkage to match ompparser test expectations
void setLang(OpenMPBaseLang lang) {
    current_lang = lang;
}

// ============================================================================
// Helper Functions
// ============================================================================

// Normalize spacing in clause expressions (add space after commas)
static std::string normalizeClauseSpacing(const std::string& expr) {
    std::string result;
    result.reserve(expr.length() * 1.2); // Reserve extra space for added spaces

    int bracket_depth = 0; // Track if we're inside brackets []

    for (size_t i = 0; i < expr.length(); i++) {
        char c = expr[i];
        result += c;

        // Track bracket depth
        if (c == '[') {
            bracket_depth++;
        } else if (c == ']') {
            bracket_depth--;
        }

        // Add space after comma if not already present and not at end
        if (c == ',' && i + 1 < expr.length() && expr[i + 1] != ' ') {
            result += ' ';
        }
        // Add space after colon ONLY if:
        // - not inside brackets (array subscripts like a[1:10] should not have space)
        // - not already followed by space
        // - not at end
        // - not followed by another colon (for :: in Fortran)
        if (c == ':' && bracket_depth == 0 && i + 1 < expr.length() &&
            expr[i + 1] != ' ' && expr[i + 1] != ':') {
            result += ' ';
        }
    }

    return result;
}

// Parse a comma-separated list from parentheses "(a,b,c)" -> ["a", "b", "c"]
static std::vector<std::string> parseParenthesizedList(const char* param) {
    std::vector<std::string> result;
    if (!param) return result;

    std::string param_str(param);

    // Find opening and closing parentheses
    size_t open = param_str.find('(');
    size_t close = param_str.rfind(')');

    if (open == std::string::npos || close == std::string::npos || close <= open) {
        return result;
    }

    // Extract content between parentheses
    std::string content = param_str.substr(open + 1, close - open - 1);

    // Split by comma
    std::stringstream ss(content);
    std::string item;
    while (std::getline(ss, item, ',')) {
        // Trim whitespace
        size_t start = item.find_first_not_of(" \t\r\n");
        size_t end = item.find_last_not_of(" \t\r\n");
        if (start != std::string::npos && end != std::string::npos) {
            result.push_back(item.substr(start, end - start + 1));
        }
    }

    return result;
}

static OpenMPDirectiveKind mapDirectiveNameToKind(const char* name) {
    if (!name) {
        return OMPD_unknown;
    }

    // Map directive names (with spaces) to ompparser kinds (with underscores)
    // ROUP uses names like "parallel for", ompparser uses OMPD_parallel_for
    // This mapping handles ALL directives including composites

    // Use strcmp for exact string matching
    // Single-word directives
    if (strcmp(name, "parallel") == 0) return OMPD_parallel;
    if (strcmp(name, "for") == 0) return OMPD_for;
    if (strcmp(name, "do") == 0) return OMPD_do;
    if (strcmp(name, "simd") == 0) return OMPD_simd;
    if (strcmp(name, "loop") == 0) return OMPD_loop;
    if (strcmp(name, "sections") == 0) return OMPD_sections;
    if (strcmp(name, "section") == 0) return OMPD_section;
    if (strcmp(name, "single") == 0) return OMPD_single;
    if (strcmp(name, "workshare") == 0) return OMPD_workshare;
    if (strcmp(name, "cancel") == 0) return OMPD_cancel;
    if (strcmp(name, "allocate") == 0) return OMPD_allocate;
    if (strcmp(name, "threadprivate") == 0) return OMPD_threadprivate;
    if (strcmp(name, "teams") == 0) return OMPD_teams;
    if (strcmp(name, "metadirective") == 0) return OMPD_metadirective;
    if (strcmp(name, "task") == 0) return OMPD_task;
    if (strcmp(name, "taskloop") == 0) return OMPD_taskloop;
    if (strcmp(name, "taskyield") == 0) return OMPD_taskyield;
    if (strcmp(name, "requires") == 0) return OMPD_requires;
    if (strcmp(name, "target") == 0) return OMPD_target;
    if (strcmp(name, "master") == 0) return OMPD_master;
    if (strcmp(name, "masked") == 0) return OMPD_master;  // masked is alias for master
    if (strcmp(name, "end") == 0) return OMPD_end;
    if (strcmp(name, "barrier") == 0) return OMPD_barrier;
    if (strcmp(name, "taskwait") == 0) return OMPD_taskwait;
    if (strcmp(name, "unroll") == 0) return OMPD_unroll;
    if (strcmp(name, "tile") == 0) return OMPD_tile;
    if (strcmp(name, "taskgroup") == 0) return OMPD_taskgroup;
    if (strcmp(name, "flush") == 0) return OMPD_flush;
    if (strcmp(name, "atomic") == 0) return OMPD_atomic;
    if (strcmp(name, "critical") == 0) return OMPD_critical;
    if (strcmp(name, "depobj") == 0) return OMPD_depobj;
    if (strcmp(name, "ordered") == 0) return OMPD_ordered;
    if (strcmp(name, "distribute") == 0) return OMPD_distribute;
    if (strcmp(name, "scan") == 0) return OMPD_scan;

    // Composite directives with "for" (C/C++)
    if (strcmp(name, "for simd") == 0) return OMPD_for_simd;
    if (strcmp(name, "parallel for") == 0) return OMPD_parallel_for;
    if (strcmp(name, "parallel for simd") == 0) return OMPD_parallel_for_simd;
    if (strcmp(name, "distribute parallel for") == 0) return OMPD_distribute_parallel_for;
    if (strcmp(name, "distribute parallel for simd") == 0) return OMPD_distribute_parallel_for_simd;
    if (strcmp(name, "parallel loop") == 0) return OMPD_parallel_loop;
    if (strcmp(name, "distribute simd") == 0) return OMPD_distribute_simd;

    // Composite directives with "do" (Fortran)
    if (strcmp(name, "do simd") == 0) return OMPD_do_simd;
    if (strcmp(name, "parallel do") == 0) return OMPD_parallel_do;
    if (strcmp(name, "parallel do simd") == 0) return OMPD_parallel_do_simd;
    if (strcmp(name, "distribute parallel do") == 0) return OMPD_distribute_parallel_do;
    if (strcmp(name, "distribute parallel do simd") == 0) return OMPD_distribute_parallel_do_simd;

    // declare directives
    if (strcmp(name, "declare simd") == 0) return OMPD_declare_simd;
    if (strcmp(name, "declare reduction") == 0) return OMPD_declare_reduction;
    if (strcmp(name, "declare mapper") == 0) return OMPD_declare_mapper;
    if (strcmp(name, "declare target") == 0) return OMPD_declare_target;
    if (strcmp(name, "end declare target") == 0) return OMPD_end_declare_target;
    if (strcmp(name, "declare variant") == 0) return OMPD_declare_variant;

    // parallel composites
    if (strcmp(name, "parallel sections") == 0) return OMPD_parallel_sections;
    if (strcmp(name, "parallel workshare") == 0) return OMPD_parallel_workshare;
    if (strcmp(name, "parallel master") == 0) return OMPD_parallel_master;

    // taskloop composites
    if (strcmp(name, "taskloop simd") == 0) return OMPD_taskloop_simd;
    if (strcmp(name, "master taskloop") == 0) return OMPD_master_taskloop;
    if (strcmp(name, "master taskloop simd") == 0) return OMPD_master_taskloop_simd;
    if (strcmp(name, "parallel master taskloop") == 0) return OMPD_parallel_master_taskloop;
    if (strcmp(name, "parallel master taskloop simd") == 0) return OMPD_parallel_master_taskloop_simd;

    // target directives
    if (strcmp(name, "target data") == 0) return OMPD_target_data;
    if (strcmp(name, "target enter data") == 0) return OMPD_target_enter_data;
    if (strcmp(name, "target update") == 0) return OMPD_target_update;
    if (strcmp(name, "target exit data") == 0) return OMPD_target_exit_data;
    if (strcmp(name, "target simd") == 0) return OMPD_target_simd;
    if (strcmp(name, "target parallel") == 0) return OMPD_target_parallel;
    if (strcmp(name, "target parallel for") == 0) return OMPD_target_parallel_for;
    if (strcmp(name, "target parallel for simd") == 0) return OMPD_target_parallel_for_simd;
    if (strcmp(name, "target parallel loop") == 0) return OMPD_target_parallel_loop;
    if (strcmp(name, "target parallel do") == 0) return OMPD_target_parallel_do;
    if (strcmp(name, "target parallel do simd") == 0) return OMPD_target_parallel_do_simd;

    // teams directives
    if (strcmp(name, "teams distribute") == 0) return OMPD_teams_distribute;
    if (strcmp(name, "teams distribute simd") == 0) return OMPD_teams_distribute_simd;
    if (strcmp(name, "teams distribute parallel for") == 0) return OMPD_teams_distribute_parallel_for;
    if (strcmp(name, "teams distribute parallel for simd") == 0) return OMPD_teams_distribute_parallel_for_simd;
    if (strcmp(name, "teams distribute parallel do") == 0) return OMPD_teams_distribute_parallel_do;
    if (strcmp(name, "teams distribute parallel do simd") == 0) return OMPD_teams_distribute_parallel_do_simd;
    if (strcmp(name, "teams loop") == 0) return OMPD_teams_loop;

    // target teams directives
    if (strcmp(name, "target teams") == 0) return OMPD_target_teams;
    if (strcmp(name, "target teams distribute") == 0) return OMPD_target_teams_distribute;
    if (strcmp(name, "target teams distribute simd") == 0) return OMPD_target_teams_distribute_simd;
    if (strcmp(name, "target teams loop") == 0) return OMPD_target_teams_loop;
    if (strcmp(name, "target teams distribute parallel for") == 0) return OMPD_target_teams_distribute_parallel_for;
    if (strcmp(name, "target teams distribute parallel for simd") == 0) return OMPD_target_teams_distribute_parallel_for_simd;
    if (strcmp(name, "target teams distribute parallel do") == 0) return OMPD_target_teams_distribute_parallel_do;
    if (strcmp(name, "target teams distribute parallel do simd") == 0) return OMPD_target_teams_distribute_parallel_do_simd;

    // cancellation point
    if (strcmp(name, "cancellation point") == 0) return OMPD_cancellation_point;

    return OMPD_unknown;
}

static OpenMPClauseKind mapRoupToOmpparserClause(int32_t roup_kind) {
    // ROUP clause kind mapping using named constants from roup_constants.h
    // Single source of truth: src/c_api.rs:convert_clause()
    switch (roup_kind) {
        case ROUP_CLAUSE_NUM_THREADS:   return OMPC_num_threads;
        case ROUP_CLAUSE_IF:            return OMPC_if;
        case ROUP_CLAUSE_PRIVATE:       return OMPC_private;
        case ROUP_CLAUSE_SHARED:        return OMPC_shared;
        case ROUP_CLAUSE_FIRSTPRIVATE:  return OMPC_firstprivate;
        case ROUP_CLAUSE_LASTPRIVATE:   return OMPC_lastprivate;
        case ROUP_CLAUSE_REDUCTION:     return OMPC_reduction;
        case ROUP_CLAUSE_SCHEDULE:      return OMPC_schedule;
        case ROUP_CLAUSE_COLLAPSE:      return OMPC_collapse;
        case ROUP_CLAUSE_ORDERED:       return OMPC_ordered;
        case ROUP_CLAUSE_NOWAIT:        return OMPC_nowait;
        case ROUP_CLAUSE_DEFAULT:       return OMPC_default;
        case ROUP_CLAUSE_COPYIN:        return OMPC_copyin;
        case ROUP_CLAUSE_ALIGN:         return OMPC_align;
        case ROUP_CLAUSE_PROC_BIND:     return OMPC_proc_bind;
        case ROUP_CLAUSE_ALLOCATE:      return OMPC_allocate;
        case ROUP_CLAUSE_NUM_TEAMS:     return OMPC_num_teams;
        case ROUP_CLAUSE_THREAD_LIMIT:  return OMPC_thread_limit;
        case ROUP_CLAUSE_PARTIAL:       return OMPC_partial;
        case ROUP_CLAUSE_FULL:          return OMPC_full;
        case ROUP_CLAUSE_ORDER:         return OMPC_order;
        case ROUP_CLAUSE_LINEAR:        return OMPC_linear;
        case ROUP_CLAUSE_SAFELEN:       return OMPC_safelen;
        case ROUP_CLAUSE_SIMDLEN:       return OMPC_simdlen;
        case ROUP_CLAUSE_ALIGNED:       return OMPC_aligned;
        case ROUP_CLAUSE_NONTEMPORAL:   return OMPC_nontemporal;
        case ROUP_CLAUSE_UNIFORM:       return OMPC_uniform;
        case ROUP_CLAUSE_INBRANCH:      return OMPC_inbranch;
        case ROUP_CLAUSE_NOTINBRANCH:   return OMPC_notinbranch;
        case ROUP_CLAUSE_DIST_SCHEDULE: return OMPC_dist_schedule;
        case ROUP_CLAUSE_BIND:          return OMPC_bind;
        case ROUP_CLAUSE_INCLUSIVE:     return OMPC_inclusive;
        case ROUP_CLAUSE_EXCLUSIVE:     return OMPC_exclusive;
        case ROUP_CLAUSE_COPYPRIVATE:   return OMPC_copyprivate;
        case ROUP_CLAUSE_PARALLEL:      return OMPC_parallel;
        case ROUP_CLAUSE_SECTIONS:      return OMPC_sections;
        case ROUP_CLAUSE_FOR:           return OMPC_for;
        case ROUP_CLAUSE_DO:            return OMPC_do;
        case ROUP_CLAUSE_TASKGROUP:     return OMPC_taskgroup;
        case ROUP_CLAUSE_ALLOCATOR:     return OMPC_allocator;
        case ROUP_CLAUSE_INITIALIZER:   return OMPC_initializer;
        case ROUP_CLAUSE_FINAL:         return OMPC_final;
        case ROUP_CLAUSE_UNTIED:        return OMPC_untied;
        case ROUP_CLAUSE_REQUIRES:      return OMPC_requires;
        case ROUP_CLAUSE_MERGEABLE:     return OMPC_mergeable;
        case ROUP_CLAUSE_IN_REDUCTION:  return OMPC_in_reduction;
        case ROUP_CLAUSE_DEPEND:        return OMPC_depend;
        case ROUP_CLAUSE_PRIORITY:      return OMPC_priority;
        case ROUP_CLAUSE_AFFINITY:      return OMPC_affinity;
        case ROUP_CLAUSE_DETACH:        return OMPC_detach;
        case ROUP_CLAUSE_GRAINSIZE:     return OMPC_grainsize;
        case ROUP_CLAUSE_NUM_TASKS:     return OMPC_num_tasks;
        case ROUP_CLAUSE_NOGROUP:       return OMPC_nogroup;
        case ROUP_CLAUSE_REVERSE_OFFLOAD: return OMPC_reverse_offload;
        case ROUP_CLAUSE_UNIFIED_ADDRESS: return OMPC_unified_address;
        case ROUP_CLAUSE_UNIFIED_SHARED_MEMORY: return OMPC_unified_shared_memory;
        case ROUP_CLAUSE_ATOMIC_DEFAULT_MEM_ORDER: return OMPC_atomic_default_mem_order;
        case ROUP_CLAUSE_DYNAMIC_ALLOCATORS: return OMPC_dynamic_allocators;
        case ROUP_CLAUSE_EXT_IMPLEMENTATION_DEFINED_REQUIREMENT: return OMPC_ext_implementation_defined_requirement;
        case ROUP_CLAUSE_DEVICE:        return OMPC_device;
        case ROUP_CLAUSE_MAP:           return OMPC_map;
        case ROUP_CLAUSE_USE_DEVICE_PTR: return OMPC_use_device_ptr;
        case ROUP_CLAUSE_SIZES:         return OMPC_sizes;
        case ROUP_CLAUSE_USE_DEVICE_ADDR: return OMPC_use_device_addr;
        case ROUP_CLAUSE_IS_DEVICE_PTR: return OMPC_is_device_ptr;
        case ROUP_CLAUSE_HAS_DEVICE_ADDR: return OMPC_has_device_addr;
        case ROUP_CLAUSE_DEFAULTMAP:    return OMPC_defaultmap;
        case ROUP_CLAUSE_TO:            return OMPC_to;
        case ROUP_CLAUSE_FROM:          return OMPC_from;
        case ROUP_CLAUSE_USES_ALLOCATORS: return OMPC_uses_allocators;
        case ROUP_CLAUSE_WHEN:          return OMPC_when;
        case ROUP_CLAUSE_MATCH:         return OMPC_match;
        case ROUP_CLAUSE_LINK:          return OMPC_link;
        case ROUP_CLAUSE_DEVICE_TYPE:   return OMPC_device_type;
        case ROUP_CLAUSE_TASK_REDUCTION: return OMPC_task_reduction;
        case ROUP_CLAUSE_ACQ_REL:       return OMPC_acq_rel;
        case ROUP_CLAUSE_RELEASE:       return OMPC_release;
        case ROUP_CLAUSE_ACQUIRE:       return OMPC_acquire;
        case ROUP_CLAUSE_READ:          return OMPC_read;
        case ROUP_CLAUSE_WRITE:         return OMPC_write;
        case ROUP_CLAUSE_UPDATE:        return OMPC_update;
        case ROUP_CLAUSE_CAPTURE:       return OMPC_capture;
        case ROUP_CLAUSE_SEQ_CST:       return OMPC_seq_cst;
        case ROUP_CLAUSE_RELAXED:       return OMPC_relaxed;
        case ROUP_CLAUSE_HINT:          return OMPC_hint;
        case ROUP_CLAUSE_DESTROY:       return OMPC_destroy;
        case ROUP_CLAUSE_DEPOBJ_UPDATE: return OMPC_depobj_update;
        case ROUP_CLAUSE_THREADS:       return OMPC_threads;
        case ROUP_CLAUSE_SIMD:          return OMPC_simd;
        default:                        return OMPC_unknown;
    }
}

// ============================================================================
// Main Entry Point
// ============================================================================

extern "C" {

OpenMPDirective* parseOpenMP(const char* input, void* exprParse(const char* expr)) {
    if (!input || input[0] == '\0') {
        return nullptr;
    }

    // Validate input length using constant from ROUP C API
    // Use strnlen to safely handle potentially untrusted/non-null-terminated input
    const size_t input_len = strnlen(input, ROUP_MAX_PRAGMA_LENGTH);
    if (input_len == ROUP_MAX_PRAGMA_LENGTH) {
        return nullptr;  // Input too long or not null-terminated within limit
    }

    // Determine input format based on current language mode
    std::string input_str(input, input_len);

    // Handle different language pragmas
    if (current_lang == Lang_Fortran) {
        // Fortran uses !$omp prefix - add if missing (case-insensitive check)
        const bool has_prefix =
            input_str.length() >= FORTRAN_PREFIX_LEN &&
            (input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX) == 0 ||
             input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX_UPPER) == 0);
        if (!has_prefix) {
            input_str = std::string(FORTRAN_PREFIX) + " " + input_str;
        }
    } else {
        // C/C++ use #pragma omp prefix - add if missing
        // compare() returns 0 if strings match, non-zero otherwise
        if (input_str.compare(0, C_PRAGMA_PREFIX_LEN, C_PRAGMA_PREFIX) != 0) {
            input_str = std::string(C_PRAGMA_PREFIX) + " " + input_str;
        }
    }

    // Call ROUP parser
    OmpDirective* roup_dir = roup_parse(input_str.c_str());
    if (!roup_dir) {
        return nullptr;
    }

    // Get directive name from ROUP (e.g., "parallel for", "target teams")
    const char* directive_name = roup_directive_name(roup_dir);
    OpenMPDirectiveKind kind = mapDirectiveNameToKind(directive_name);

    // Create ompparser-compatible directive
    // Use specialized directive types for those that have extra data
    OpenMPDirective* dir = nullptr;

    switch (kind) {
        case OMPD_threadprivate:
            dir = new OpenMPThreadprivateDirective();
            break;
        case OMPD_allocate:
            dir = new OpenMPAllocateDirective();
            break;
        case OMPD_declare_variant:
            dir = new OpenMPDeclareVariantDirective();
            break;
        case OMPD_declare_reduction:
            dir = new OpenMPDeclareReductionDirective();
            break;
        case OMPD_declare_mapper:
            dir = new OpenMPDeclareMapperDirective(OMPD_DECLARE_MAPPER_IDENTIFIER_unspecified);
            break;
        case OMPD_declare_simd:
            dir = new OpenMPDeclareSimdDirective();
            break;
        case OMPD_declare_target:
        case OMPD_end_declare_target:
            dir = new OpenMPDeclareTargetDirective();
            break;
        case OMPD_end:
            dir = new OpenMPEndDirective();
            break;
        case OMPD_critical:
            dir = new OpenMPCriticalDirective();
            break;
        case OMPD_flush:
            dir = new OpenMPFlushDirective();
            break;
        case OMPD_depobj:
            dir = new OpenMPDepobjDirective();
            break;
        case OMPD_atomic:
            dir = new OpenMPAtomicDirective();
            break;
        case OMPD_ordered:
            dir = new OpenMPOrderedDirective();
            break;
        case OMPD_requires:
            dir = new OpenMPRequiresDirective();
            break;
        default:
            // For all other directives, use base OpenMPDirective
            dir = new OpenMPDirective(kind, current_lang, 0, 0);
            break;
    }

    // Set language for all directive types
    dir->setBaseLang(current_lang);

    // Handle directive-specific parameters (e.g., threadprivate list, allocate list)
    const char* param = roup_directive_parameter(roup_dir);
    if (param) {
        std::vector<std::string> param_list = parseParenthesizedList(param);

        switch (kind) {
            case OMPD_threadprivate: {
                OpenMPThreadprivateDirective* tp_dir = static_cast<OpenMPThreadprivateDirective*>(dir);
                for (const auto& item : param_list) {
                    // Need to duplicate string since addThreadprivateList stores the pointer
                    char* item_copy = strdup(item.c_str());
                    tp_dir->addThreadprivateList(item_copy);
                }
                break;
            }
            case OMPD_allocate: {
                OpenMPAllocateDirective* alloc_dir = static_cast<OpenMPAllocateDirective*>(dir);
                for (const auto& item : param_list) {
                    char* item_copy = strdup(item.c_str());
                    alloc_dir->addAllocateList(item_copy);
                }
                break;
            }
            case OMPD_flush: {
                OpenMPFlushDirective* flush_dir = static_cast<OpenMPFlushDirective*>(dir);
                for (const auto& item : param_list) {
                    // flush_list uses std::string, so direct push works
                    flush_dir->addFlushList(item.c_str());
                }
                break;
            }
            case OMPD_declare_target:
            case OMPD_end_declare_target: {
                OpenMPDeclareTargetDirective* dt_dir = static_cast<OpenMPDeclareTargetDirective*>(dir);
                for (const auto& item : param_list) {
                    // extended_list uses std::string, so direct push works
                    dt_dir->addExtendedList(item.c_str());
                }
                break;
            }
            default:
                // Other directives may use parameter differently
                break;
        }
    }

    // Convert clauses using ompparser's addOpenMPClause method
    OmpClauseIterator* iter = roup_directive_clauses_iter(roup_dir);
    if (iter) {
        const OmpClause* roup_clause;
        while (roup_clause_iterator_next(iter, &roup_clause) == 1) {
            int32_t roup_kind_clause = roup_clause_kind(roup_clause);
            OpenMPClauseKind clause_kind = mapRoupToOmpparserClause(roup_kind_clause);

            // Get the full clause text from ROUP (e.g., "private(a, b)")
            const char* clause_text = roup_clause_text(roup_clause);

            // Handle specialized clauses with parameters
            OpenMPClause* omp_clause = nullptr;

            if (clause_kind == OMPC_if) {
                // For if clauses, use unspecified modifier to avoid adding unwanted "parallel:" prefix
                omp_clause = dir->addOpenMPClause(static_cast<int>(clause_kind), OMPC_IF_MODIFIER_unspecified);
            } else if (clause_kind == OMPC_default) {
                // Use ROUP's parsed default kind
                int32_t default_kind = roup_clause_default_data_sharing(roup_clause);
                OpenMPDefaultClauseKind omp_default_kind;
                switch (default_kind) {
                    case 0: omp_default_kind = OMPC_DEFAULT_shared; break;
                    case 1: omp_default_kind = OMPC_DEFAULT_none; break;
                    case 2: omp_default_kind = OMPC_DEFAULT_private; break;
                    case 3: omp_default_kind = OMPC_DEFAULT_firstprivate; break;
                    default: omp_default_kind = OMPC_DEFAULT_shared; break;
                }
                omp_clause = dir->addOpenMPClause(static_cast<int>(clause_kind), omp_default_kind);
            } else if (clause_kind == OMPC_schedule) {
                // Use ROUP's parsed schedule kind
                int32_t schedule_kind = roup_clause_schedule_kind(roup_clause);
                OpenMPScheduleClauseKind omp_schedule_kind;
                switch (schedule_kind) {
                    case 0: omp_schedule_kind = OMPC_SCHEDULE_KIND_static; break;
                    case 1: omp_schedule_kind = OMPC_SCHEDULE_KIND_dynamic; break;
                    case 2: omp_schedule_kind = OMPC_SCHEDULE_KIND_guided; break;
                    case 3: omp_schedule_kind = OMPC_SCHEDULE_KIND_auto; break;
                    case 4: omp_schedule_kind = OMPC_SCHEDULE_KIND_runtime; break;
                    default: omp_schedule_kind = OMPC_SCHEDULE_KIND_static; break;
                }
                // For now, use unspecified modifiers - full schedule parsing would need more work
                omp_clause = dir->addOpenMPClause(static_cast<int>(clause_kind),
                                                   OMPC_SCHEDULE_MODIFIER_unspecified,
                                                   OMPC_SCHEDULE_MODIFIER_unspecified,
                                                   omp_schedule_kind);
            } else if (clause_kind == OMPC_proc_bind) {
                // Use ROUP's parsed proc_bind kind
                int32_t proc_bind_kind = roup_clause_proc_bind(roup_clause);
                OpenMPProcBindClauseKind omp_proc_bind_kind;
                switch (proc_bind_kind) {
                    case 0: omp_proc_bind_kind = OMPC_PROC_BIND_master; break;
                    case 1: omp_proc_bind_kind = OMPC_PROC_BIND_close; break;
                    case 2: omp_proc_bind_kind = OMPC_PROC_BIND_spread; break;
                    case 3: omp_proc_bind_kind = OMPC_PROC_BIND_master; break; // primary -> master for compat
                    default: omp_proc_bind_kind = OMPC_PROC_BIND_master; break;
                }
                omp_clause = dir->addOpenMPClause(static_cast<int>(clause_kind), omp_proc_bind_kind);
            } else {
                // Create basic clause for all other types
                omp_clause = dir->addOpenMPClause(static_cast<int>(clause_kind));
            }

            // If we have clause text with parameters, extract and add them
            if (omp_clause && clause_text) {
                std::string text(clause_text);

                // Find the opening and closing parentheses
                size_t open_paren = text.find('(');
                size_t close_paren = text.rfind(')');

                if (open_paren != std::string::npos && close_paren != std::string::npos && close_paren > open_paren) {
                    // Extract the content between parentheses
                    std::string expr = text.substr(open_paren + 1, close_paren - open_paren - 1);

                    // Normalize spacing (add spaces after commas and colons)
                    expr = normalizeClauseSpacing(expr);

                    // Add the expression to the clause
                    if (!expr.empty()) {
                        omp_clause->addLangExpr(expr.c_str());
                    }
                }
            }
        }
        roup_clause_iterator_free(iter);
    }

    // Free ROUP directive (we've extracted what we need)
    roup_directive_free(roup_dir);

    return dir;
}

} // extern "C"
