#ifndef ROUP_OMPPARSER_TYPED_CONTRACT_H
#define ROUP_OMPPARSER_TYPED_CONTRACT_H

/*
 * Exhaustive mapping from ROUP's stable numeric OpenMP contract to
 * ompparser's enums. Keep this list explicit: an ABI addition must make the
 * adapter fail closed until its representation is deliberately selected.
 */

#define ROUP_OMPPARSER_DIRECTIVES(X) \
  X(ALLOCATE, allocate) \
  X(ALLOCATORS, allocators) \
  X(ASSUME, assume) \
  X(ASSUMES, assumes) \
  X(ATOMIC, atomic) \
  X(BARRIER, barrier) \
  X(BEGIN_ASSUMES, begin_assumes) \
  X(BEGIN_DECLARE_TARGET, begin_declare_target) \
  X(BEGIN_DECLARE_VARIANT, begin_declare_variant) \
  X(CANCEL, cancel) \
  X(CANCELLATION_POINT, cancellation_point) \
  X(CRITICAL, critical) \
  X(DECLARE_INDUCTION, declare_induction) \
  X(DECLARE_MAPPER, declare_mapper) \
  X(DECLARE_REDUCTION, declare_reduction) \
  X(DECLARE_SIMD, declare_simd) \
  X(DECLARE_TARGET, declare_target) \
  X(DECLARE_VARIANT, declare_variant) \
  X(DEPOBJ, depobj) \
  X(DISPATCH, dispatch) \
  X(DISTRIBUTE, distribute) \
  X(DISTRIBUTE_PARALLEL_DO, distribute_parallel_do) \
  X(DISTRIBUTE_PARALLEL_DO_SIMD, distribute_parallel_do_simd) \
  X(DISTRIBUTE_PARALLEL_FOR, distribute_parallel_for) \
  X(DISTRIBUTE_PARALLEL_FOR_SIMD, distribute_parallel_for_simd) \
  X(DISTRIBUTE_PARALLEL_LOOP, distribute_parallel_loop) \
  X(DISTRIBUTE_PARALLEL_LOOP_SIMD, distribute_parallel_loop_simd) \
  X(DISTRIBUTE_SIMD, distribute_simd) \
  X(DO, do) \
  X(DO_SIMD, do_simd) \
  X(ERROR, error) \
  X(FLUSH, flush) \
  X(FUSE, fuse) \
  X(GROUPPRIVATE, groupprivate) \
  X(FOR, for) \
  X(FOR_SIMD, for_simd) \
  X(INTERCHANGE, interchange) \
  X(INTEROP, interop) \
  X(LOOP, loop) \
  X(REVERSE, reverse) \
  X(MASKED, masked) \
  X(MASKED_TASKLOOP, masked_taskloop) \
  X(MASKED_TASKLOOP_SIMD, masked_taskloop_simd) \
  X(MASTER, master) \
  X(MASTER_TASKLOOP, master_taskloop) \
  X(MASTER_TASKLOOP_SIMD, master_taskloop_simd) \
  X(METADIRECTIVE, metadirective) \
  X(BEGIN_METADIRECTIVE, begin_metadirective) \
  X(NOTHING, nothing) \
  X(ORDERED, ordered) \
  X(PARALLEL, parallel) \
  X(PARALLEL_DO, parallel_do) \
  X(PARALLEL_DO_SIMD, parallel_do_simd) \
  X(PARALLEL_FOR, parallel_for) \
  X(PARALLEL_FOR_SIMD, parallel_for_simd) \
  X(PARALLEL_LOOP, parallel_loop) \
  X(PARALLEL_LOOP_SIMD, parallel_loop_simd) \
  X(PARALLEL_MASKED, parallel_masked) \
  X(PARALLEL_MASKED_TASKLOOP, parallel_masked_taskloop) \
  X(PARALLEL_MASKED_TASKLOOP_SIMD, parallel_masked_taskloop_simd) \
  X(PARALLEL_MASTER, parallel_master) \
  X(PARALLEL_MASTER_TASKLOOP, parallel_master_taskloop) \
  X(PARALLEL_MASTER_TASKLOOP_SIMD, parallel_master_taskloop_simd) \
  X(PARALLEL_SECTIONS, parallel_sections) \
  X(PARALLEL_SINGLE, parallel_single) \
  X(PARALLEL_WORKSHARE, parallel_workshare) \
  X(REQUIRES, requires) \
  X(SCOPE, scope) \
  X(SCAN, scan) \
  X(SECTION, section) \
  X(SECTIONS, sections) \
  X(SIMD, simd) \
  X(SINGLE, single) \
  X(SPLIT, split) \
  X(STRIPE, stripe) \
  X(TARGET, target) \
  X(TARGET_DATA, target_data) \
  X(TARGET_ENTER_DATA, target_enter_data) \
  X(TARGET_EXIT_DATA, target_exit_data) \
  X(TARGET_LOOP, target_loop) \
  X(TARGET_LOOP_SIMD, target_loop_simd) \
  X(TARGET_PARALLEL, target_parallel) \
  X(TARGET_PARALLEL_DO, target_parallel_do) \
  X(TARGET_PARALLEL_DO_SIMD, target_parallel_do_simd) \
  X(TARGET_PARALLEL_FOR, target_parallel_for) \
  X(TARGET_PARALLEL_FOR_SIMD, target_parallel_for_simd) \
  X(TARGET_PARALLEL_LOOP, target_parallel_loop) \
  X(TARGET_PARALLEL_LOOP_SIMD, target_parallel_loop_simd) \
  X(TARGET_SIMD, target_simd) \
  X(TARGET_TEAMS, target_teams) \
  X(TARGET_TEAMS_DISTRIBUTE, target_teams_distribute) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO, target_teams_distribute_parallel_do) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD, target_teams_distribute_parallel_do_simd) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR, target_teams_distribute_parallel_for) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD, target_teams_distribute_parallel_for_simd) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP, target_teams_distribute_parallel_loop) \
  X(TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD, target_teams_distribute_parallel_loop_simd) \
  X(TARGET_TEAMS_DISTRIBUTE_SIMD, target_teams_distribute_simd) \
  X(TARGET_TEAMS_LOOP, target_teams_loop) \
  X(TARGET_TEAMS_LOOP_SIMD, target_teams_loop_simd) \
  X(TARGET_TEAMS_WORKDISTRIBUTE, target_teams_workdistribute) \
  X(TARGET_UPDATE, target_update) \
  X(TASK, task) \
  X(TASK_ITERATION, task_iteration) \
  X(TASKGROUP, taskgroup) \
  X(TASKGRAPH, taskgraph) \
  X(TASKLOOP, taskloop) \
  X(TASKLOOP_SIMD, taskloop_simd) \
  X(TASKWAIT, taskwait) \
  X(TASKYIELD, taskyield) \
  X(TEAMS, teams) \
  X(TEAMS_DISTRIBUTE, teams_distribute) \
  X(TEAMS_DISTRIBUTE_PARALLEL_DO, teams_distribute_parallel_do) \
  X(TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD, teams_distribute_parallel_do_simd) \
  X(TEAMS_DISTRIBUTE_PARALLEL_FOR, teams_distribute_parallel_for) \
  X(TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD, teams_distribute_parallel_for_simd) \
  X(TEAMS_DISTRIBUTE_PARALLEL_LOOP, teams_distribute_parallel_loop) \
  X(TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD, teams_distribute_parallel_loop_simd) \
  X(TEAMS_DISTRIBUTE_SIMD, teams_distribute_simd) \
  X(TEAMS_LOOP, teams_loop) \
  X(TEAMS_LOOP_SIMD, teams_loop_simd) \
  X(THREADPRIVATE, threadprivate) \
  X(TILE, tile) \
  X(UNROLL, unroll) \
  X(WORKDISTRIBUTE, workdistribute) \
  X(WORKSHARE, workshare) \
  X(OMPX, ompx)

#define ROUP_OMPPARSER_END_DIRECTIVES(X) \
  X(END_SECTION, section) \
  X(END_ALLOCATORS, allocators) \
  X(END_DISPATCH, dispatch) \
  X(END_PARALLEL, parallel) \
  X(END_DO, do) \
  X(END_SIMD, simd) \
  X(END_SECTIONS, sections) \
  X(END_SINGLE, single) \
  X(END_WORKSHARE, workshare) \
  X(END_ORDERED, ordered) \
  X(END_LOOP, loop) \
  X(END_DISTRIBUTE, distribute) \
  X(END_TEAMS, teams) \
  X(END_TASKLOOP, taskloop) \
  X(END_TASK, task) \
  X(END_TASKGROUP, taskgroup) \
  X(END_MASTER, master) \
  X(END_MASKED, masked) \
  X(END_UNROLL, unroll) \
  X(END_CRITICAL, critical) \
  X(END_ATOMIC, atomic) \
  X(END_PARALLEL_DO, parallel_do) \
  X(END_PARALLEL_SECTIONS, parallel_sections) \
  X(END_PARALLEL_WORKSHARE, parallel_workshare) \
  X(END_PARALLEL_MASTER, parallel_master) \
  X(END_PARALLEL_SINGLE, parallel_single) \
  X(END_PARALLEL_MASTER_TASKLOOP, parallel_master_taskloop) \
  X(END_PARALLEL_MASTER_TASKLOOP_SIMD, parallel_master_taskloop_simd) \
  X(END_DO_SIMD, do_simd) \
  X(END_PARALLEL_DO_SIMD, parallel_do_simd) \
  X(END_DISTRIBUTE_SIMD, distribute_simd) \
  X(END_DISTRIBUTE_PARALLEL_DO, distribute_parallel_do) \
  X(END_DISTRIBUTE_PARALLEL_DO_SIMD, distribute_parallel_do_simd) \
  X(END_TARGET_PARALLEL, target_parallel) \
  X(END_TARGET_PARALLEL_DO, target_parallel_do) \
  X(END_TARGET_PARALLEL_DO_SIMD, target_parallel_do_simd) \
  X(END_TARGET_PARALLEL_LOOP, target_parallel_loop) \
  X(END_TARGET_SIMD, target_simd) \
  X(END_TARGET_TEAMS, target_teams) \
  X(END_TARGET_TEAMS_DISTRIBUTE, target_teams_distribute) \
  X(END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO, target_teams_distribute_parallel_do) \
  X(END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD, target_teams_distribute_parallel_do_simd) \
  X(END_TARGET_TEAMS_DISTRIBUTE_SIMD, target_teams_distribute_simd) \
  X(END_TARGET_TEAMS_LOOP, target_teams_loop) \
  X(END_TARGET_TEAMS_WORKDISTRIBUTE, target_teams_workdistribute) \
  X(END_TEAMS_DISTRIBUTE, teams_distribute) \
  X(END_TEAMS_DISTRIBUTE_PARALLEL_DO, teams_distribute_parallel_do) \
  X(END_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD, teams_distribute_parallel_do_simd) \
  X(END_TEAMS_DISTRIBUTE_SIMD, teams_distribute_simd) \
  X(END_TEAMS_LOOP, teams_loop) \
  X(END_TASKLOOP_SIMD, taskloop_simd) \
  X(END_MASTER_TASKLOOP, master_taskloop) \
  X(END_MASTER_TASKLOOP_SIMD, master_taskloop_simd) \
  X(END_MASKED_TASKLOOP, masked_taskloop) \
  X(END_MASKED_TASKLOOP_SIMD, masked_taskloop_simd) \
  X(END_PARALLEL_MASKED, parallel_masked) \
  X(END_PARALLEL_MASKED_TASKLOOP, parallel_masked_taskloop) \
  X(END_PARALLEL_MASKED_TASKLOOP_SIMD, parallel_masked_taskloop_simd) \
  X(END_PARALLEL_LOOP, parallel_loop) \
  X(END_TARGET_LOOP, target_loop) \
  X(END_TILE, tile) \
  X(END_METADIRECTIVE, metadirective) \
  X(END_SCOPE, scope) \
  X(END_TARGET, target) \
  X(END_TARGET_DATA, target_data)

#define ROUP_OMPPARSER_DIRECT_END_DIRECTIVES(X) \
  X(END_ASSUME, end_assume) \
  X(END_ASSUMES, end_assumes) \
  X(END_DECLARE_TARGET, end_declare_target) \
  X(END_DECLARE_VARIANT, end_declare_variant)

#define ROUP_OMPPARSER_CLAUSES(X) \
  X(ABSENT, absent) \
  X(ACQ_REL, acq_rel) \
  X(ACQUIRE, acquire) \
  X(ADJUST_ARGS, adjust_args) \
  X(AFFINITY, affinity) \
  X(ALIGN, align) \
  X(ALIGNED, aligned) \
  X(ALLOCATE, allocate) \
  X(ALLOCATOR, allocator) \
  X(APPEND_ARGS, append_args) \
  X(APPLY, apply) \
  X(AT, at) \
  X(ATOMIC_DEFAULT_MEM_ORDER, atomic_default_mem_order) \
  X(BIND, bind) \
  X(CAPTURE, capture) \
  X(COLLAPSE, collapse) \
  X(COLLECTOR, collector) \
  X(COMBINER, combiner) \
  X(COMPARE, compare) \
  X(CONTAINS, contains) \
  X(COPY_IN, copyin) \
  X(COPYPRIVATE, copyprivate) \
  X(PARALLEL, parallel) \
  X(SECTIONS, sections) \
  X(FOR, for) \
  X(DO, do) \
  X(TASKGROUP, taskgroup) \
  X(COUNTS, counts) \
  X(DEFAULT, default) \
  X(DEFAULTMAP, defaultmap) \
  X(DEPEND, depend) \
  X(DEPOBJ_UPDATE, depobj_update) \
  X(DESTROY, destroy) \
  X(DETACH, detach) \
  X(DEVICE, device) \
  X(DEVICE_SAFESYNC, device_safesync) \
  X(DEVICE_TYPE, device_type) \
  X(DIST_SCHEDULE, dist_schedule) \
  X(DOACROSS, doacross) \
  X(DYNAMIC_ALLOCATORS, dynamic_allocators) \
  X(EXT_IMPLEMENTATION_DEFINED_REQUIREMENT, ext_implementation_defined_requirement) \
  X(ENTER, enter) \
  X(EXCLUSIVE, exclusive) \
  X(FAIL, fail) \
  X(FINAL, final) \
  X(FILTER, filter) \
  X(FIRSTPRIVATE, firstprivate) \
  X(FROM, from) \
  X(FULL, full) \
  X(GRAINSIZE, grainsize) \
  X(GRAPH_ID, graph_id) \
  X(GRAPH_RESET, graph_reset) \
  X(HAS_DEVICE_ADDR, has_device_addr) \
  X(HINT, hint) \
  X(HOLDS, holds) \
  X(IF, if) \
  X(IN_REDUCTION, in_reduction) \
  X(INDUCTION, induction) \
  X(INDUCTOR, inductor) \
  X(INBRANCH, inbranch) \
  X(INCLUSIVE, inclusive) \
  X(INIT, init) \
  X(INIT_COMPLETE, init_complete) \
  X(INITIALIZER, initializer) \
  X(INDIRECT, indirect) \
  X(IS_DEVICE_PTR, is_device_ptr) \
  X(LASTPRIVATE, lastprivate) \
  X(LINEAR, linear) \
  X(LINK, link) \
  X(LOCAL, local) \
  X(LOOPRANGE, looprange) \
  X(MAP, map) \
  X(MATCH, match) \
  X(MESSAGE, message) \
  X(MEMSCOPE, memscope) \
  X(MERGEABLE, mergeable) \
  X(NOCONTEXT, nocontext) \
  X(NOGROUP, nogroup) \
  X(NO_OPENMP, no_openmp) \
  X(NO_OPENMP_CONSTRUCTS, no_openmp_constructs) \
  X(NO_OPENMP_ROUTINES, no_openmp_routines) \
  X(NO_PARALLELISM, no_parallelism) \
  X(NONTEMPORAL, nontemporal) \
  X(NOTINBRANCH, notinbranch) \
  X(NOVARIANTS, novariants) \
  X(INTEROP, interop) \
  X(NOWAIT, nowait) \
  X(NUM_TASKS, num_tasks) \
  X(NUM_TEAMS, num_teams) \
  X(NUM_THREADS, num_threads) \
  X(ORDER, order) \
  X(ORDERED, ordered) \
  X(OTHERWISE, otherwise) \
  X(PARTIAL, partial) \
  X(PERMUTATION, permutation) \
  X(PRIORITY, priority) \
  X(PRIVATE, private) \
  X(PROC_BIND, proc_bind) \
  X(READ, read) \
  X(REDUCTION, reduction) \
  X(RELEASE, release) \
  X(RELAXED, relaxed) \
  X(REPLAYABLE, replayable) \
  X(REVERSE_OFFLOAD, reverse_offload) \
  X(SAFELEN, safelen) \
  X(SAFESYNC, safesync) \
  X(SCHEDULE, schedule) \
  X(SELF_MAPS, self_maps) \
  X(SEQ_CST, seq_cst) \
  X(SEVERITY, severity) \
  X(SHARED, shared) \
  X(SIMD, simd) \
  X(SIMDLEN, simdlen) \
  X(SIZES, sizes) \
  X(TASK_REDUCTION, task_reduction) \
  X(THREAD_LIMIT, thread_limit) \
  X(THREADS, threads) \
  X(THREADSET, threadset) \
  X(TO, to) \
  X(TRANSPARENT, transparent) \
  X(UNIFIED_ADDRESS, unified_address) \
  X(UNIFIED_SHARED_MEMORY, unified_shared_memory) \
  X(UNIFORM, uniform) \
  X(UNTIED, untied) \
  X(UPDATE, update) \
  X(USE, use) \
  X(USE_DEVICE_ADDR, use_device_addr) \
  X(USE_DEVICE_PTR, use_device_ptr) \
  X(USES_ALLOCATORS, uses_allocators) \
  X(WEAK, weak) \
  X(WHEN, when) \
  X(WRITE, write)

#endif
