/*
 * compat_impl.cpp - accparser compatibility implementation using ROUP
 *
 * Provides parseOpenACC() implementation using ROUP parser + accparser AST.
 * Uses OpenACCParser.h from submodule (no ANTLR dependency).
 *
 * Copyright (c) 2025 ROUP Project
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <OpenACCParser.h>
#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include <string>

// Include ROUP constants (auto-generated by build.rs from src/c_api.rs)
#include <roup_constants.h>

// ============================================================================
// ROUP C API Forward Declarations
// ============================================================================

extern "C" {
    // Opaque types from ROUP
    struct AccDirective;
    struct AccClause;
    struct AccClauseIterator;

    // Core parsing
    AccDirective* acc_parse(const char* input);
    AccDirective* acc_parse_with_language(const char* input, int32_t language);
    void acc_directive_free(AccDirective* directive);

    // Directive queries
    int32_t acc_directive_kind(const AccDirective* directive);
    int32_t acc_directive_clause_count(const AccDirective* directive);
    AccClauseIterator* acc_directive_clauses_iter(const AccDirective* directive);

    // Iterator operations
    int32_t acc_clause_iterator_next(AccClauseIterator* iter, const AccClause** out);
    void acc_clause_iterator_free(AccClauseIterator* iter);

    // Clause queries
    int32_t acc_clause_kind(const AccClause* clause);
    const char* acc_clause_original_keyword(const AccClause* clause);
    int32_t acc_clause_expressions_count(const AccClause* clause);
    const char* acc_clause_expression_at(const AccClause* clause, int32_t index);
    int32_t acc_clause_modifier(const AccClause* clause);
    int32_t acc_clause_data_variant(const AccClause* clause);
    int32_t acc_clause_data_modifier_count(const AccClause* clause);
    int32_t acc_clause_data_modifier_at(const AccClause* clause, int32_t index);
    int32_t acc_clause_reduction_operator(const AccClause* clause);
    int32_t acc_clause_vector_modifier(const AccClause* clause);
    int32_t acc_clause_worker_modifier(const AccClause* clause);
    int32_t acc_clause_gang_arg_kind(const AccClause* clause);
    int32_t acc_clause_device_type_count(const AccClause* clause);
    int32_t acc_clause_device_type_kind_at(const AccClause* clause, int32_t index);
    int32_t acc_clause_indirect_present(const AccClause* clause);
    const char* acc_clause_indirect_value(const AccClause* clause);
    int32_t acc_clause_indirect_value_is_string_literal(const AccClause* clause);
    int32_t acc_clause_operator(const AccClause* clause);
    const char* acc_clause_wait_devnum(const AccClause* clause);
    int32_t acc_clause_wait_has_queues(const AccClause* clause);

    // Cache directive queries
    int32_t acc_cache_directive_modifier(const AccDirective* directive);
    int32_t acc_cache_directive_var_count(const AccDirective* directive);
    const char* acc_cache_directive_var_at(const AccDirective* directive, int32_t index);

    // Wait directive queries
    int32_t acc_directive_wait_expression_count(const AccDirective* directive);
    const char* acc_directive_wait_expression_at(const AccDirective* directive, int32_t index);
    const char* acc_directive_wait_devnum(const AccDirective* directive);
    int32_t acc_directive_wait_has_queues(const AccDirective* directive);

    // Routine directive queries
    const char* acc_directive_routine_name(const AccDirective* directive);

    // End directive queries
    int32_t acc_directive_end_paired_kind(const AccDirective* directive);
}

// ============================================================================
// Global State
// ============================================================================

static OpenACCBaseLang current_lang = ACC_Lang_C;

// Language prefix constants
static constexpr const char FORTRAN_PREFIX[] = "!$acc";       // Fortran prefix (lowercase)
static constexpr const char FORTRAN_PREFIX_UPPER[] = "!$ACC"; // Fortran prefix (uppercase)
static constexpr const char C_PRAGMA_PREFIX[] = "#pragma";    // C/C++ pragma prefix
static constexpr size_t FORTRAN_PREFIX_LEN = sizeof(FORTRAN_PREFIX) - 1;
static constexpr size_t C_PRAGMA_PREFIX_LEN = sizeof(C_PRAGMA_PREFIX) - 1;

extern "C" void setLang(OpenACCBaseLang lang) {
    current_lang = lang;
}

static void maybeMergeClause(OpenACCDirective* directive, OpenACCClauseKind kind, OpenACCClause* clause) {
    const bool prev_merge = OpenACCDirective::getClauseMerging();
    OpenACCDirective::setClauseMerging(true);
    switch (kind) {
        case ACCC_async:
            static_cast<OpenACCAsyncClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_bind:
            static_cast<OpenACCBindClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_collapse:
            static_cast<OpenACCCollapseClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_copyin:
            static_cast<OpenACCCopyinClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_copyout:
            static_cast<OpenACCCopyoutClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_create:
            static_cast<OpenACCCreateClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_default_async:
            static_cast<OpenACCDefaultAsyncClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_device_num:
            static_cast<OpenACCDeviceNumClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_tile:
            static_cast<OpenACCTileClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_gang:
            static_cast<OpenACCGangClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_num_gangs:
            static_cast<OpenACCNumGangsClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_num_workers:
            static_cast<OpenACCNumWorkersClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_reduction:
            static_cast<OpenACCReductionClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_vector:
            static_cast<OpenACCVectorClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_vector_length:
            static_cast<OpenACCVectorLengthClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_delete:
            static_cast<OpenACCDeleteClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_detach:
            static_cast<OpenACCDetachClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_device:
            static_cast<OpenACCDeviceClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_use_device:
            static_cast<OpenACCUseDeviceClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_host:
            static_cast<OpenACCHostClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_private:
            static_cast<OpenACCPrivateClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_firstprivate:
            static_cast<OpenACCFirstprivateClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_no_create:
            static_cast<OpenACCNoCreateClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_present:
            static_cast<OpenACCPresentClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_link:
            static_cast<OpenACCLinkClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_device_resident:
            static_cast<OpenACCDeviceResidentClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_deviceptr:
            static_cast<OpenACCDeviceptrClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_wait:
            static_cast<OpenACCWaitClause*>(clause)->mergeClause(directive, clause);
            break;
        case ACCC_worker:
            static_cast<OpenACCWorkerClause*>(clause)->mergeClause(directive, clause);
            break;
        default:
            break;
    }
    OpenACCDirective::setClauseMerging(prev_merge);
}

// ============================================================================
// Helper Functions
// ============================================================================

static OpenACCDirectiveKind mapRoupToAccparserDirective(int32_t roup_kind) {
    // ROUP directive kind mapping using named constants from roup_constants.h
    // Mapping from ROUP IDs (src/c_api.rs:acc_directive_name_to_kind lines 1636-1664)
    // to accparser enum values (compat/accparser/accparser/src/OpenACCKinds.h)
    //
    // The ROUP C API may return either the reduced directive kind (small
    // integers like 0..N) or the full macro values (offset by ACC_DIRECTIVE_BASE,
    // e.g., 10000+). Normalize here to the full macro values so the switch
    // statements using `ROUP_ACCD_*` macros match correctly.
    // Expect ROUP to publish canonical ACC namespace values (ACC_DIRECTIVE_BASE + raw).
    // Any reduced 0..N values or otherwise out-of-range values indicate a producer bug
    // and must be treated as a fatal error rather than normalized silently.
    const int32_t ACC_DIRECTIVE_BASE = 10000;
    int32_t full_kind = roup_kind;
    if (full_kind >= 0 && full_kind < ACC_DIRECTIVE_BASE) {
        // This indicates ROUP returned a reduced numeric value rather than the
        // canonical ACC_DIRECTIVE_BASE-offset value. Treat as fatal.
        fprintf(stderr, "FATAL: ROUP returned non-canonical OpenACC directive kind: %d\n", roup_kind);
        abort();
    }

    // Note: ROUP supports both space and underscore variants for some directives:
    //   - "enter data" and "enter_data" both map to ACCD_enter_data
    //   - "exit data" and "exit_data" both map to ACCD_exit_data
    //   - "host_data" (underscore form) maps to ACCD_host_data (space-form is
    //     not accepted by the ROUP canonical mapping used here)
    //   - "wait" and "wait(... )" both map to ACCD_wait
    switch (full_kind) {
        case ROUP_ACCD_parallel:    return ACCD_parallel;     // 0 = "parallel"
        case ROUP_ACCD_loop:        return ACCD_loop;         // 1 = "loop"
        case ROUP_ACCD_kernels:     return ACCD_kernels;      // 2 = "kernels"
    case ROUP_ACCD_data:                 return ACCD_data;         // 3 = "data"
    case ROUP_ACCD_enter_data:           return ACCD_enter_data;   // 4 = "enter data" (space)
    case ROUP_ACCD_exit_data:            return ACCD_exit_data;    // 5 = "exit data" (space)
        case ROUP_ACCD_atomic:      return ACCD_atomic;       // 7 = "atomic"
        case ROUP_ACCD_declare:     return ACCD_declare;      // 8 = "declare"
        case ROUP_ACCD_wait:        return ACCD_wait;         // 9 = "wait"
        case ROUP_ACCD_end:         return ACCD_end;          // 10 = "end"
    case ROUP_ACCD_host_data:   return ACCD_host_data;    // host_data (underscore form)
    case ROUP_ACCD_update:      return ACCD_update;       // 12 = "update"
    // Note: ROUP previously emitted target/teams/distribute family aliases
    // in the OpenACC mapping. These constructs do not appear in the
    // accparser OpenACCKinds.h header, so the ROUP constants for them are
    // no longer generated. Do not attempt to map them here.

    // Preserve earlier per-directive loop/kernels mappings for other kinds
    case ROUP_ACCD_kernels_loop:         return ACCD_kernels_loop; // 10016 = "kernels loop"
    case ROUP_ACCD_parallel_loop:        return ACCD_parallel_loop;// 10017 = "parallel loop"
    case ROUP_ACCD_serial_loop:          return ACCD_serial_loop;  // 10018 = "serial loop"
        case ROUP_ACCD_serial:      return ACCD_serial;       // 17 = "serial"
        case ROUP_ACCD_routine:     return ACCD_routine;      // 18 = "routine"
        case ROUP_ACCD_set:         return ACCD_set;          // 19 = "set"
        case ROUP_ACCD_init:        return ACCD_init;         // 20 = "init"
        case ROUP_ACCD_shutdown:    return ACCD_shutdown;     // 21 = "shutdown"
    case ROUP_ACCD_cache:       return ACCD_cache;        // 23 = "cache(... )" with content
    // underscore-form variants removed from ROUP OpenACC mapping
        default:                        return ACCD_unknown;
    }
}

static OpenACCClauseKind mapRoupToAccparserClause(int32_t roup_kind) {
    // ROUP clause kind mapping using named constants from roup_constants.h
    // Single source of truth: src/c_api/openacc.rs:clause_name_to_kind()
    switch (roup_kind) {
        case ROUP_ACCC_async:           return ACCC_async;
        case ROUP_ACCC_wait:            return ACCC_wait;
        case ROUP_ACCC_num_gangs:       return ACCC_num_gangs;
        case ROUP_ACCC_num_workers:     return ACCC_num_workers;
        case ROUP_ACCC_vector_length:   return ACCC_vector_length;
        case ROUP_ACCC_gang:            return ACCC_gang;
        case ROUP_ACCC_worker:          return ACCC_worker;
        case ROUP_ACCC_vector:          return ACCC_vector;
        case ROUP_ACCC_seq:             return ACCC_seq;
        case ROUP_ACCC_independent:     return ACCC_independent;
        case ROUP_ACCC_auto:            return ACCC_auto;
        case ROUP_ACCC_collapse:        return ACCC_collapse;
        case ROUP_ACCC_device_type:     return ACCC_device_type;
        case ROUP_ACCC_bind:            return ACCC_bind;
        case ROUP_ACCC_if:              return ACCC_if;
        case ROUP_ACCC_default:         return ACCC_default;
        case ROUP_ACCC_firstprivate:    return ACCC_firstprivate;
        case ROUP_ACCC_default_async:   return ACCC_default_async;
        case ROUP_ACCC_link:            return ACCC_link;
        case ROUP_ACCC_no_create:       return ACCC_no_create;
        case ROUP_ACCC_nohost:          return ACCC_nohost;
        case ROUP_ACCC_present:         return ACCC_present;
        case ROUP_ACCC_private:         return ACCC_private;
        case ROUP_ACCC_reduction:       return ACCC_reduction;
        case ROUP_ACCC_read:            return ACCC_read;
        case ROUP_ACCC_self:            return ACCC_self;
        case ROUP_ACCC_tile:            return ACCC_tile;
        case ROUP_ACCC_use_device:      return ACCC_use_device;
        case ROUP_ACCC_attach:          return ACCC_attach;
        case ROUP_ACCC_detach:          return ACCC_detach;
        case ROUP_ACCC_finalize:        return ACCC_finalize;
        case ROUP_ACCC_if_present:      return ACCC_if_present;
        case ROUP_ACCC_capture:         return ACCC_capture;
        case ROUP_ACCC_write:           return ACCC_write;
        case ROUP_ACCC_update:          return ACCC_update;
        case ROUP_ACCC_copy:            return ACCC_copy;
        case ROUP_ACCC_copyin:          return ACCC_copyin;
        case ROUP_ACCC_copyout:         return ACCC_copyout;
        case ROUP_ACCC_create:          return ACCC_create;
        case ROUP_ACCC_delete:          return ACCC_delete;
        case ROUP_ACCC_device:          return ACCC_device;
        case ROUP_ACCC_deviceptr:       return ACCC_deviceptr;
        case ROUP_ACCC_device_num:      return ACCC_device_num;
        case ROUP_ACCC_device_resident: return ACCC_device_resident;
        case ROUP_ACCC_host:            return ACCC_host;
        case ROUP_ACCC_indirect:        return ACCC_indirect;
        default:                         return ACCC_unknown;
    }
}

// ============================================================================
// Main Entry Point
// ============================================================================

extern "C" {

OpenACCDirective* parseOpenACC(const char* input, void* exprParse(const char* expr)) {
    if (!input || input[0] == '\0') {
        return nullptr;
    }

    // Validate input length using constant from ROUP C API
    // Manual safe strlen to avoid non-portable strnlen (POSIX.1-2008)
    size_t input_len = 0;
    while (input_len < ROUP_MAX_PRAGMA_LENGTH && input[input_len] != '\0') {
        ++input_len;
    }
    // If loop exited because we hit the limit (not because we found '\0'),
    // the input is too long or not null-terminated within bounds
    // Check if we exited due to reaching the limit AND the last checked char wasn't NUL
    if (input_len == ROUP_MAX_PRAGMA_LENGTH && (input_len == 0 || input[input_len - 1] != '\0')) {
        return nullptr;  // Input too long or not null-terminated within limit
    }

    // Determine input format based on current language mode (auto-detect Fortran)
    std::string input_str(input, input_len);
    auto has_prefix_icase = [](const std::string& value, const char* prefix) {
        const size_t len = std::strlen(prefix);
        return value.size() >= len &&
               strncasecmp(value.c_str(), prefix, len) == 0;
    };

    OpenACCBaseLang effective_lang = current_lang;
    // Auto-detect Fortran sentinels when lang is not explicitly set
    if (effective_lang == ACC_Lang_C) {
        const std::string trimmed = input_str;
        if (has_prefix_icase(trimmed, "!$acc") || has_prefix_icase(trimmed, "c$acc") ||
            has_prefix_icase(trimmed, "*$acc")) {
            effective_lang = ACC_Lang_Fortran;
        }
    }

    // Handle different language pragmas
    if (effective_lang == ACC_Lang_Fortran) {
        // Fortran uses !$acc prefix - add if missing (case-insensitive check)
        const bool has_prefix =
            input_str.length() >= FORTRAN_PREFIX_LEN &&
            (input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX) == 0 ||
             input_str.compare(0, FORTRAN_PREFIX_LEN, FORTRAN_PREFIX_UPPER) == 0);
        if (!has_prefix) {
            input_str = std::string(FORTRAN_PREFIX) + " " + input_str;
        }
    } else {
        // C/C++ use #pragma acc prefix - add if missing
        if (input_str.compare(0, C_PRAGMA_PREFIX_LEN, C_PRAGMA_PREFIX) != 0) {
            input_str = std::string(C_PRAGMA_PREFIX) + " " + input_str;
        }
    }

    // Call ROUP parser with language setting to honor setLang()
    // Map accparser language to ROUP language constants (roup_constants.h)
    // ROUP_LANG_C = 0, ROUP_LANG_FORTRAN_FREE = 1, ROUP_LANG_FORTRAN_FIXED = 2
    int32_t roup_lang = (effective_lang == ACC_Lang_Fortran) ? 1 : 0; // 0=C, 1=Fortran free-form
    AccDirective* roup_dir = acc_parse_with_language(input_str.c_str(), roup_lang);
    if (!roup_dir) {
        return nullptr;
    }

    // Get directive kind from ROUP
    int32_t roup_kind = acc_directive_kind(roup_dir);
    OpenACCDirectiveKind kind = mapRoupToAccparserDirective(roup_kind);

    // Unknown directive kind is a fatal error: the generator and runtime
    // must agree on canonical OpenACC mapping.
    if (kind == ACCD_unknown) {
        fprintf(stderr, "FATAL: Unknown directive kind from ROUP: %d\n", roup_kind);
        abort();
    }

    // Create accparser-compatible directive
    // Cache and Wait directives need special handling
    OpenACCDirective* dir = nullptr;

    if (kind == ACCD_cache) {
        // Create OpenACCCacheDirective
        OpenACCCacheDirective* cache_dir = new OpenACCCacheDirective();
        cache_dir->setBaseLang(effective_lang);

        // Get cache modifier (0=none, 1=readonly)
        int32_t cache_modifier = acc_cache_directive_modifier(roup_dir);
        if (cache_modifier == 1) {
            cache_dir->setModifier(ACCC_CACHE_readonly);
        }

        // Get cache variables
        int32_t var_count = acc_cache_directive_var_count(roup_dir);
        for (int32_t i = 0; i < var_count; i++) {
            const char* var = acc_cache_directive_var_at(roup_dir, i);
            if (var) {
                cache_dir->addVar(std::string(var));
            }
        }

        dir = cache_dir;
    } else if (kind == ACCD_wait) {
        // Create OpenACCWaitDirective
        OpenACCWaitDirective* wait_dir = new OpenACCWaitDirective();
        wait_dir->setBaseLang(effective_lang);

        int32_t expr_count = acc_directive_wait_expression_count(roup_dir);
        for (int32_t i = 0; i < expr_count; ++i) {
            const char* expr = acc_directive_wait_expression_at(roup_dir, i);
            if (expr) {
                wait_dir->addAsyncId(std::string(expr));
            }
        }

        if (const char* devnum = acc_directive_wait_devnum(roup_dir)) {
            if (devnum[0] != '\0') {
                wait_dir->setDevnum(std::string(devnum));
            }
        }

        if (acc_directive_wait_has_queues(roup_dir)) {
            wait_dir->setQueues(true);
        }

        dir = wait_dir;
    } else if (kind == ACCD_routine) {
        // Create OpenACCRoutineDirective
        OpenACCRoutineDirective* routine_dir = new OpenACCRoutineDirective();
        routine_dir->setBaseLang(effective_lang);

        // Get routine name if present
        const char* routine_name = acc_directive_routine_name(roup_dir);
        if (routine_name && routine_name[0] != '\0') {
            routine_dir->setName(std::string(routine_name));
        }

        dir = routine_dir;
    } else if (kind == ACCD_end) {
        // Create OpenACCEndDirective
        OpenACCEndDirective* end_dir = new OpenACCEndDirective();
        end_dir->setBaseLang(effective_lang);

        // Get paired directive kind from ROUP
        int32_t paired_kind = acc_directive_end_paired_kind(roup_dir);
        if (paired_kind >= 0) {
            OpenACCDirectiveKind paired_acc_kind = mapRoupToAccparserDirective(paired_kind);
            // Create a minimal paired directive (just for toString generation)
            OpenACCDirective* paired = new OpenACCDirective(paired_acc_kind, effective_lang, 0, 0);
            end_dir->setPairedDirective(paired);
        } else {
            end_dir->setPairedDirective(nullptr);
        }

        dir = end_dir;
    } else {
        // Regular directive
        dir = new OpenACCDirective(kind, effective_lang, 0, 0);
    }

    // Disable accparser's global clause merging; compat controls merging
    // explicitly via maybeMergeClause to preserve duplicate/self clauses.
    const bool prev_merge = OpenACCDirective::getClauseMerging();
    OpenACCDirective::setClauseMerging(false);

    // Convert clauses - get ALL data from ROUP's C API
    AccClauseIterator* iter = acc_directive_clauses_iter(roup_dir);
    if (iter) {
        const AccClause* roup_clause;
        while (acc_clause_iterator_next(iter, &roup_clause) == 1) {
            int32_t roup_kind_clause = acc_clause_kind(roup_clause);
            OpenACCClauseKind clause_kind = mapRoupToAccparserClause(roup_kind_clause);

            // Create clause using accparser's API
            OpenACCClause* clause = dir->addOpenACCClause(static_cast<int>(clause_kind));

            if (!clause) {
                fprintf(stderr,
                        "WARNING: addOpenACCClause returned null (directive=%d, clause=%d)\n",
                        static_cast<int>(kind),
                        static_cast<int>(clause_kind));
                continue;
            }

            // Collect clause expressions up front
            std::vector<std::string> expressions;
            {
                int32_t expr_count = acc_clause_expressions_count(roup_clause);
                expressions.reserve(expr_count > 0 ? expr_count : 0);
                for (int32_t i = 0; i < expr_count; i++) {
                    const char* expr = acc_clause_expression_at(roup_clause, i);
                    if (expr) {
                        expressions.emplace_back(expr);
                    }
                }
            }
            // Apply typed, enum-based payload fields (no string/number inspection).
            if (auto* data_clause = dynamic_cast<OpenACCDataClause*>(clause)) {
                const int32_t variant_code = acc_clause_data_variant(roup_clause);
                if (variant_code >= 0) {
                    data_clause->setVariant(static_cast<OpenACCDataClauseVariant>(variant_code));
                }
                const int32_t mod_count = acc_clause_data_modifier_count(roup_clause);
                for (int32_t i = 0; i < mod_count; ++i) {
                    const int32_t mod_code = acc_clause_data_modifier_at(roup_clause, i);
                    if (mod_code >= 0) {
                        data_clause->addModifier(static_cast<OpenACCDataClauseModifierKind>(mod_code));
                    }
                }
            }

            if (clause_kind == ACCC_reduction) {
                const int32_t op_code = acc_clause_reduction_operator(roup_clause);
                static_cast<OpenACCReductionClause*>(clause)->setOperator(
                    static_cast<OpenACCReductionClauseOperator>(op_code));
            } else if (clause_kind == ACCC_default) {
                const int32_t kind_code = acc_clause_modifier(roup_clause);
                static_cast<OpenACCDefaultClause*>(clause)->setKind(
                    static_cast<OpenACCDefaultClauseKind>(kind_code));
            }

            // Populate clause-specific payloads using structured data
            switch (clause_kind) {
                case ACCC_async: {
                    if (!expressions.empty()) {
                        auto* async_clause = static_cast<OpenACCAsyncClause*>(clause);
                        async_clause->setAsyncExpr(expressions.front());
                        async_clause->setModifier(ACCC_ASYNC_expr);
                    }
                    break;
                }
                case ACCC_default_async: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCDefaultAsyncClause*>(clause)->setAsyncExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_bind: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCBindClause*>(clause)->setBinding(expressions.front(), /*is_string_literal=*/false);
                    }
                    break;
                }
                case ACCC_collapse: {
                    auto* collapse = static_cast<OpenACCCollapseClause*>(clause);
                    for (const auto& expr : expressions) {
                        collapse->addCountExpr(expr);
                    }
                    break;
                }
                case ACCC_num_gangs: {
                    auto* ng = static_cast<OpenACCNumGangsClause*>(clause);
                    for (const auto& expr : expressions) {
                        ng->addNum(expr);
                    }
                    break;
                }
                case ACCC_num_workers: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCNumWorkersClause*>(clause)->setNumExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_vector_length: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCVectorLengthClause*>(clause)->setLengthExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_device_num: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCDeviceNumClause*>(clause)->setDeviceExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_if: {
                    if (!expressions.empty()) {
                        static_cast<OpenACCIfClause*>(clause)->setCondition(expressions.front());
                    }
                    break;
                }
                case ACCC_device: {
                    auto* dev = static_cast<OpenACCDeviceClause*>(clause);
                    for (const auto& expr : expressions) {
                        dev->addDevice(expr);
                    }
                    break;
                }
                case ACCC_tile: {
                    auto* tile = static_cast<OpenACCTileClause*>(clause);
                    for (const auto& expr : expressions) {
                        tile->addTileSize(expr);
                    }
                    break;
                }
                case ACCC_vector: {
                    auto* vec = static_cast<OpenACCVectorClause*>(clause);
                    vec->setModifier(static_cast<OpenACCVectorClauseModifier>(
                        acc_clause_vector_modifier(roup_clause)));
                    if (!expressions.empty()) {
                        vec->setLengthExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_worker: {
                    auto* worker = static_cast<OpenACCWorkerClause*>(clause);
                    worker->setModifier(static_cast<OpenACCWorkerClauseModifier>(
                        acc_clause_worker_modifier(roup_clause)));
                    if (!expressions.empty()) {
                        worker->setNumExpr(expressions.front());
                    }
                    break;
                }
                case ACCC_gang: {
                    auto* gang = static_cast<OpenACCGangClause*>(clause);
                    const int32_t kind_code = acc_clause_gang_arg_kind(roup_clause);
                    OpenACCGangArgKind arg_kind = (kind_code >= 0)
                        ? static_cast<OpenACCGangArgKind>(kind_code)
                        : ACCC_GANG_ARG_other;
                    for (const auto& expr : expressions) {
                        gang->addArg(arg_kind, expr);
                    }
                    break;
                }
                case ACCC_device_type: {
                    auto* dtype = static_cast<OpenACCDeviceTypeClause*>(clause);
                    const int32_t count = acc_clause_device_type_count(roup_clause);
                    for (int32_t i = 0; i < count; ++i) {
                        const int32_t kind_code = acc_clause_device_type_kind_at(roup_clause, i);
                        if (kind_code == ACCC_DEVICE_TYPE_unknown) {
                            const char* raw = acc_clause_expression_at(roup_clause, i);
                            if (raw && raw[0] != '\0') {
                                dtype->addDeviceTypeString(std::string(raw));
                            }
                        } else if (kind_code >= 0) {
                            dtype->addDeviceType(static_cast<OpenACCDeviceTypeKind>(kind_code));
                        }
                    }
                    break;
                }
                case ACCC_indirect: {
                    auto* indirect = static_cast<OpenACCIndirectClause*>(clause);
                    if (acc_clause_indirect_present(roup_clause)) {
                        indirect->setPresent(true);
                        const char* value = acc_clause_indirect_value(roup_clause);
                        if (value && value[0] != '\0') {
                            const bool is_str =
                                acc_clause_indirect_value_is_string_literal(roup_clause) != 0;
                            indirect->setValue(std::string(value), is_str);
                        }
                    }
                    break;
                }
                case ACCC_wait: {
                    auto* wait_clause = static_cast<OpenACCWaitClause*>(clause);
                    for (const auto& expr : expressions) {
                        wait_clause->addAsyncId(expr);
                    }
                    break;
                }
                default:
                    break;
            }

            // Populate variable-list style clauses
            if (auto* var_clause = dynamic_cast<OpenACCVarListClause*>(clause)) {
                auto add_var_token = [&](const std::string& token) {
                    const auto first = token.find_first_not_of(" \t");
                    if (first == std::string::npos) {
                        return;
                    }
                    const auto last = token.find_last_not_of(" \t");
                    var_clause->addVar(token.substr(first, last - first + 1));
                };

                for (const auto& expr : expressions) {
                    add_var_token(expr);
                }
            } else if (expressions.empty() == false) {
                // For non-varlist clauses that still carry expressions, preserve them
                for (const auto& expr : expressions) {
                    clause->addLangExpr(expr);
                }
            }

            // Deduplicate trivial marker clauses that are expected to merge
            if (clause_kind == ACCC_auto || clause_kind == ACCC_independent ||
                clause_kind == ACCC_if_present) {
                auto* existing = dir->getClauses(clause_kind);
                if (existing != nullptr && existing->size() > 1) {
                    auto* order = dir->getClausesInOriginalOrder();
                    if (order && !order->empty() && order->back() == clause) {
                        order->pop_back();
                    }
                    existing->pop_back();
                    delete clause;
                    continue;
                }
            }

            // Drop duplicate/self-subset clauses
            if (clause_kind == ACCC_self) {
                auto* self_clause = static_cast<OpenACCSelfClause*>(clause);
                auto* existing = dir->getClauses(ACCC_self);
                if (existing != nullptr) {
                    const auto& condition = self_clause->getCondition();
                    const bool has_condition = !condition.text.empty();
                    bool drop_current = false;
                    std::vector<OpenACCSelfClause*> remove_list;

                    // Skip the clause we just added (last element)
                    for (auto it = existing->begin(); it != existing->end(); ++it) {
                        if (it + 1 == existing->end()) {
                            break;
                        }
                        auto* prev = static_cast<OpenACCSelfClause*>(*it);
                        const auto& prev_condition = prev->getCondition();
                        const bool prev_has_condition = !prev_condition.text.empty();
                        if (has_condition || prev_has_condition) {
                            if (has_condition && prev_has_condition &&
                                prev_condition.text == condition.text &&
                                prev_condition.separator == condition.separator) {
                                remove_list.push_back(prev);
                            }
                            continue;
                        }

                        // Both are var-list clauses: drop subsets/duplicates.
                        auto normalize_vars =
                            [](const std::vector<OpenACCExpressionItem>& raw_vars) {
                            std::vector<std::string> tokens;
                            tokens.reserve(raw_vars.size());
                            for (const auto& raw_item : raw_vars) {
                                const auto& raw = raw_item.text;
                                if (raw.find(',') != std::string::npos) {
                                    std::stringstream ss(raw);
                                    std::string part;
                                    while (std::getline(ss, part, ',')) {
                                        const auto first = part.find_first_not_of(" \t");
                                        const auto last = part.find_last_not_of(" \t");
                                        if (first == std::string::npos) {
                                            continue;
                                        }
                                        tokens.emplace_back(
                                            part.substr(first, last - first + 1));
                                    }
                                } else {
                                    const auto first = raw.find_first_not_of(" \t");
                                    const auto last = raw.find_last_not_of(" \t");
                                    if (first == std::string::npos) {
                                        continue;
                                    }
                                    tokens.emplace_back(raw.substr(first, last - first + 1));
                                }
                            }
                            return tokens;
                        };

                        const auto incoming_vars = normalize_vars(self_clause->getVars());
                        const auto prev_vars = normalize_vars(prev->getVars());
                        const bool incoming_empty = incoming_vars.empty();
                        const bool prev_empty = prev_vars.empty();

                        if (incoming_empty && prev_empty) {
                            drop_current = true;
                            break;
                        }
                        if (incoming_empty != prev_empty) {
                            continue;
                        }

                        auto is_subset = [](const std::vector<std::string>& a,
                                            const std::vector<std::string>& b) {
                            return std::all_of(a.begin(), a.end(), [&](const std::string& val) {
                                return std::find(b.begin(), b.end(), val) != b.end();
                            });
                        };

                        if (is_subset(prev_vars, incoming_vars)) {
                            if (is_subset(incoming_vars, prev_vars)) {
                                // Exact duplicate: drop the incoming clause to preserve order
                                drop_current = true;
                                break;
                            }
                            // Incoming is a strict superset: remove the previous subset clause
                            remove_list.push_back(prev);
                        } else if (is_subset(incoming_vars, prev_vars)) {
                            // Incoming is a subset of an existing clause: skip it
                            drop_current = true;
                            break;
                        }
                    }

                    if (drop_current) {
                        auto* order = dir->getClausesInOriginalOrder();
                        if (order && !order->empty() && order->back() == clause) {
                            order->pop_back();
                        }
                        if (!existing->empty() && existing->back() == clause) {
                            existing->pop_back();
                        }
                        delete clause;
                        continue;
                    }

                    if (!remove_list.empty()) {
                        auto* order = dir->getClausesInOriginalOrder();
                        for (auto* prev : remove_list) {
                            if (order) {
                                order->erase(
                                    std::remove(order->begin(), order->end(), prev),
                                    order->end());
                            }
                            existing->erase(
                                std::remove(existing->begin(), existing->end(), prev),
                                existing->end());
                            delete prev;
                        }
                    }
                }
            }

            if (clause_kind == ACCC_wait) {
                if (const char* devnum_value = acc_clause_wait_devnum(roup_clause)) {
                    static_cast<OpenACCWaitClause*>(clause)->setDevnum(std::string(devnum_value));
                }
                if (acc_clause_wait_has_queues(roup_clause)) {
                    static_cast<OpenACCWaitClause*>(clause)->setQueues(true);
                }
            }

            maybeMergeClause(dir, clause_kind, clause);
        }
        acc_clause_iterator_free(iter);
    }

    // Free ROUP directive (we've extracted what we need)
    acc_directive_free(roup_dir);

    // Restore previous merging setting
    OpenACCDirective::setClauseMerging(prev_merge);

    return dir;
}

} // extern "C"

OpenACCDirective* parseOpenACC(std::string input) {
    return parseOpenACC(input.c_str(), nullptr);
}
