[book]
title = "ROUP Documentation"
authors = ["Anjia Wang"]
description = "Rust-based OpenMP/OpenACC Unified Parser - Safe, fast, and extensible"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/ouankou/roup"
edit-url-template = "https://github.com/ouankou/roup/edit/main/docs/book/{path}"
site-url = "/"
cname = "roup.ouankou.com"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.playground]
runnable = false
