# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    resource_class: arm.medium
    steps:
      - run: lscpu
      - run: lsb_release -a
      - run: rustc --version
      - run: cargo --version

  notify-github:
    parameters:
      image:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: arm.medium
    steps:
      - run:
          name: Trigger GitHub Dispatch Event
          command: |
            curl -X POST -u "ouankou:${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/ouankou/roup/dispatches" \
            -d '{"event_type": "circleci-success"}'

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
# Test the latest three stable versions.
workflows:
  test-workflow:
    jobs:
      - build:
          matrix:
            parameters:
              image: ["cimg/rust:1.74", "cimg/rust:1.73", "cimg/rust:1.72", "cimg/rust:1.71"]
      - notify-github:
          requires:
            - build
