# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    resource_class: arm.medium
    steps:
      - run: lscpu
      - run: lsb_release -a
      - run: rustc --version
      - run: cargo --version

  notify-github:
    docker:
      - image: cimg/base:current
# https://circleci.com/product/features/resource-classes/
    resource_class: arm.medium
    steps:
      - run:
          name: Trigger GitHub Dispatch Event
          command: |
            if [ -n "${CIRCLE_PULL_REQUEST}" ]; then
              echo "This build was triggered by a pull request."
              curl -X POST -u "ouankou:${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/ouankou/roup/dispatches" \
              -d '{"event_type": "circleci-pull-request"}'
            else
              echo "This build was triggered by a push to the branch."
              curl -X POST -u "ouankou:${GITHUB_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/ouankou/roup/dispatches" \
              -d '{"event_type": "circleci-push"}'
            fi

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
# Test the latest three stable versions.
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              image: ["cimg/rust:1.81", "cimg/rust:1.80", "cimg/rust:1.79", "cimg/rust:1.78", "cimg/rust:1.77", "cimg/rust:1.76"]
          filters:
            branches:
              only: main

      - notify-github:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
