//! Opaque handle-based C ABI for the safe ROUP parser.
//!
//! The pure Rust parser remains in `roup`. This crate owns global handle
//! storage and one audited module for all foreign pointer access.

#![deny(unsafe_code)]
#![deny(unsafe_op_in_unsafe_fn)]

#[allow(unsafe_code)]
mod boundary;

mod handle;

mod service;

/// Current version of the redesigned handle-based C ABI.
///
/// Version 3 makes host-language expressions and type syntax recursively
/// queryable, exposes node spans and related diagnostic locations, and names
/// extension dialects explicitly. Older callers are rejected instead of
/// observing a partially typed schema.
pub const ROUP_ABI_VERSION: u32 = 3;

pub const ROUP_DIALECT_OPENMP: u32 = 1;
pub const ROUP_DIALECT_OPENACC: u32 = 2;

pub const ROUP_VERSION_ANY: u32 = 0;
pub const ROUP_VERSION_EXACT: u32 = 1;
pub const ROUP_PARSER_OMPPARSER_EXTENSIONS: u32 = 1 << 0;
pub const ROUP_PARSER_ACCPARSER_EXTENSIONS: u32 = 1 << 1;

pub const ROUP_OMP_VERSION_1_0: u32 = 100;
pub const ROUP_OMP_VERSION_1_1: u32 = 110;
pub const ROUP_OMP_VERSION_2_0: u32 = 200;
pub const ROUP_OMP_VERSION_2_5: u32 = 250;
pub const ROUP_OMP_VERSION_3_0: u32 = 300;
pub const ROUP_OMP_VERSION_3_1: u32 = 310;
pub const ROUP_OMP_VERSION_4_0: u32 = 400;
pub const ROUP_OMP_VERSION_4_5: u32 = 450;
pub const ROUP_OMP_VERSION_5_0: u32 = 500;
pub const ROUP_OMP_VERSION_5_1: u32 = 510;
pub const ROUP_OMP_VERSION_5_2: u32 = 520;
pub const ROUP_OMP_VERSION_6_0: u32 = 600;

pub const ROUP_ACC_VERSION_1_0: u32 = 100;
pub const ROUP_ACC_VERSION_2_0: u32 = 200;
pub const ROUP_ACC_VERSION_2_5: u32 = 250;
pub const ROUP_ACC_VERSION_2_6: u32 = 260;
pub const ROUP_ACC_VERSION_2_7: u32 = 270;
pub const ROUP_ACC_VERSION_3_0: u32 = 300;
pub const ROUP_ACC_VERSION_3_1: u32 = 310;
pub const ROUP_ACC_VERSION_3_2: u32 = 320;
pub const ROUP_ACC_VERSION_3_3: u32 = 330;
pub const ROUP_ACC_VERSION_3_4: u32 = 340;

pub const ROUP_OMP_VERSION_BIT_1_0: u64 = 1 << 0;
pub const ROUP_OMP_VERSION_BIT_1_1: u64 = 1 << 1;
pub const ROUP_OMP_VERSION_BIT_2_0: u64 = 1 << 2;
pub const ROUP_OMP_VERSION_BIT_2_5: u64 = 1 << 3;
pub const ROUP_OMP_VERSION_BIT_3_0: u64 = 1 << 4;
pub const ROUP_OMP_VERSION_BIT_3_1: u64 = 1 << 5;
pub const ROUP_OMP_VERSION_BIT_4_0: u64 = 1 << 6;
pub const ROUP_OMP_VERSION_BIT_4_5: u64 = 1 << 7;
pub const ROUP_OMP_VERSION_BIT_5_0: u64 = 1 << 8;
pub const ROUP_OMP_VERSION_BIT_5_1: u64 = 1 << 9;
pub const ROUP_OMP_VERSION_BIT_5_2: u64 = 1 << 10;
pub const ROUP_OMP_VERSION_BIT_6_0: u64 = 1 << 11;

pub const ROUP_ACC_VERSION_BIT_1_0: u64 = 1 << 0;
pub const ROUP_ACC_VERSION_BIT_2_0: u64 = 1 << 1;
pub const ROUP_ACC_VERSION_BIT_2_5: u64 = 1 << 2;
pub const ROUP_ACC_VERSION_BIT_2_6: u64 = 1 << 3;
pub const ROUP_ACC_VERSION_BIT_2_7: u64 = 1 << 4;
pub const ROUP_ACC_VERSION_BIT_3_0: u64 = 1 << 5;
pub const ROUP_ACC_VERSION_BIT_3_1: u64 = 1 << 6;
pub const ROUP_ACC_VERSION_BIT_3_2: u64 = 1 << 7;
pub const ROUP_ACC_VERSION_BIT_3_3: u64 = 1 << 8;
pub const ROUP_ACC_VERSION_BIT_3_4: u64 = 1 << 9;

pub const ROUP_HOST_C: u32 = 1;
pub const ROUP_HOST_CPP: u32 = 2;
pub const ROUP_HOST_FORTRAN: u32 = 3;

pub const ROUP_C_89: u32 = 89;
pub const ROUP_C_99: u32 = 99;
pub const ROUP_C_11: u32 = 11;
pub const ROUP_C_18: u32 = 18;
pub const ROUP_C_23: u32 = 23;
pub const ROUP_CPP_98: u32 = 98;
pub const ROUP_CPP_11: u32 = 11;
pub const ROUP_CPP_14: u32 = 14;
pub const ROUP_CPP_17: u32 = 17;
pub const ROUP_CPP_20: u32 = 20;
pub const ROUP_CPP_23: u32 = 23;
pub const ROUP_FORTRAN_77: u32 = 77;
pub const ROUP_FORTRAN_90: u32 = 90;
pub const ROUP_FORTRAN_95: u32 = 95;
pub const ROUP_FORTRAN_2003: u32 = 2003;
pub const ROUP_FORTRAN_2008: u32 = 2008;
pub const ROUP_FORTRAN_2018: u32 = 2018;
pub const ROUP_FORTRAN_2023: u32 = 2023;

pub const ROUP_SOURCE_PRAGMA: u32 = 1;
pub const ROUP_SOURCE_FORTRAN_FREE: u32 = 2;
pub const ROUP_SOURCE_FORTRAN_FIXED: u32 = 3;

pub const ROUP_DIAGNOSTIC_INVALID_POINTER: u32 = 60_000;
pub const ROUP_DIAGNOSTIC_INVALID_UTF8: u32 = 60_001;
pub const ROUP_DIAGNOSTIC_BUFFER_TOO_SMALL: u32 = 60_002;
pub const ROUP_DIAGNOSTIC_INVALID_HANDLE: u32 = 60_003;
pub const ROUP_DIAGNOSTIC_INDEX_OUT_OF_RANGE: u32 = 60_004;
pub const ROUP_DIAGNOSTIC_INTERNAL_ERROR: u32 = 60_005;

pub const ROUP_FIELD_VALUE_BOOL: u32 = 1;
pub const ROUP_FIELD_VALUE_U32: u32 = 2;
pub const ROUP_FIELD_VALUE_STRING: u32 = 3;
pub const ROUP_FIELD_VALUE_STRING_LIST: u32 = 4;
pub const ROUP_FIELD_VALUE_U32_LIST: u32 = 5;
pub const ROUP_FIELD_VALUE_NODE: u32 = 6;
pub const ROUP_FIELD_VALUE_NODE_LIST: u32 = 7;
pub const ROUP_FIELD_VALUE_U64: u32 = 8;

pub const ROUP_FIELD_VALUE: u32 = 1;
pub const ROUP_FIELD_VALUES: u32 = 2;
pub const ROUP_FIELD_ITEMS: u32 = 3;
pub const ROUP_FIELD_KIND: u32 = 4;
pub const ROUP_FIELD_MODIFIER: u32 = 5;
pub const ROUP_FIELD_MODIFIERS: u32 = 6;
pub const ROUP_FIELD_OPERATOR: u32 = 7;
pub const ROUP_FIELD_USER_IDENTIFIER: u32 = 8;
pub const ROUP_FIELD_MAPPER: u32 = 9;
pub const ROUP_FIELD_ITERATORS: u32 = 10;
pub const ROUP_FIELD_CONDITION: u32 = 11;
pub const ROUP_FIELD_CHUNK_SIZE: u32 = 12;
pub const ROUP_FIELD_STEP: u32 = 13;
pub const ROUP_FIELD_ALIGNMENT: u32 = 14;
pub const ROUP_FIELD_ALLOCATOR: u32 = 15;
pub const ROUP_FIELD_LABEL: u32 = 16;
pub const ROUP_FIELD_ARGUMENTS: u32 = 18;
pub const ROUP_FIELD_DIRECTIVES: u32 = 19;
pub const ROUP_FIELD_BEHAVIOR: u32 = 20;
pub const ROUP_FIELD_CATEGORY: u32 = 21;
pub const ROUP_FIELD_DEPEND_TYPE: u32 = 22;
pub const ROUP_FIELD_DEVICE_NUM: u32 = 23;
pub const ROUP_FIELD_MEMORY_ORDER: u32 = 26;
pub const ROUP_FIELD_REQUIREMENTS: u32 = 27;
pub const ROUP_FIELD_ALLOCATORS: u32 = 28;
pub const ROUP_FIELD_READONLY: u32 = 30;
pub const ROUP_FIELD_NESTED_DIRECTIVE: u32 = 37;
pub const ROUP_FIELD_TYPE_NAME: u32 = 38;
pub const ROUP_FIELD_VARIABLE: u32 = 39;
pub const ROUP_FIELD_COMBINER: u32 = 40;
pub const ROUP_FIELD_INITIALIZER: u32 = 41;
pub const ROUP_FIELD_FUNCTION: u32 = 42;
pub const ROUP_FIELD_START: u32 = 43;
pub const ROUP_FIELD_END: u32 = 44;
pub const ROUP_FIELD_SCORE: u32 = 45;
pub const ROUP_FIELD_CLAUSES: u32 = 46;
pub const ROUP_FIELD_PARAMETER: u32 = 47;
pub const ROUP_FIELD_TRAITS: u32 = 49;
pub const ROUP_FIELD_ENTRIES: u32 = 50;
pub const ROUP_FIELD_FORCE: u32 = 51;
pub const ROUP_FIELD_DIRECTIVE: u32 = 52;
pub const ROUP_FIELD_MEMSPACE: u32 = 53;
pub const ROUP_FIELD_NAME: u32 = 54;
pub const ROUP_FIELD_VARIABLE_TYPE: u32 = 55;
pub const ROUP_FIELD_STEP_TYPE: u32 = 56;
pub const ROUP_FIELD_TYPE_SPECIFIERS: u32 = 57;
pub const ROUP_FIELD_EVENT: u32 = 58;
pub const ROUP_FIELD_DO_NOT_SYNCHRONIZE: u32 = 59;
pub const ROUP_FIELD_FULLY_UNROLL: u32 = 60;
pub const ROUP_FIELD_UNROLL_FACTOR: u32 = 61;
pub const ROUP_FIELD_CAN_MERGE: u32 = 62;
pub const ROUP_FIELD_CAN_CHANGE_THREADS: u32 = 63;
pub const ROUP_FIELD_APPLY_TO_SIMD: u32 = 64;
pub const ROUP_FIELD_APPLY_TO_THREADS: u32 = 65;
pub const ROUP_FIELD_CAN_ASSUME: u32 = 66;
pub const ROUP_FIELD_INVOKED_BY_FPTR: u32 = 67;
pub const ROUP_FIELD_REPLAYABLE_EXPRESSION: u32 = 68;
pub const ROUP_FIELD_WIDTH: u32 = 69;
pub const ROUP_FIELD_IMPEX_TYPE: u32 = 70;
pub const ROUP_FIELD_USE_SEMANTICS: u32 = 71;
pub const ROUP_FIELD_REQUIRED: u32 = 72;
pub const ROUP_FIELD_BASE: u32 = 73;
pub const ROUP_FIELD_GLOBAL: u32 = 74;
pub const ROUP_FIELD_QUALIFIER: u32 = 75;
pub const ROUP_FIELD_ENCODING: u32 = 76;
pub const ROUP_FIELD_FIRST: u32 = 77;
pub const ROUP_FIELD_COUNT: u32 = 78;
pub const ROUP_FIELD_DIRECTIVE_NAME_MODIFIER: u32 = 79;
pub const ROUP_FIELD_OPERATION: u32 = 80;
pub const ROUP_FIELD_PARAMETERS: u32 = 81;
pub const ROUP_FIELD_OPERATIONS: u32 = 82;
pub const ROUP_FIELD_OFFSET: u32 = 83;
pub const ROUP_FIELD_OBJECTS: u32 = 84;
pub const ROUP_FIELD_LOWER_BOUND: u32 = 90;
pub const ROUP_FIELD_UPPER_BOUND: u32 = 91;
pub const ROUP_FIELD_SOURCE_SYNTAX: u32 = 92;
pub const ROUP_FIELD_ALLOCATOR_EXPRESSION: u32 = 93;
pub const ROUP_FIELD_ALIGNMENT_EXPRESSION: u32 = 94;
pub const ROUP_FIELD_ALLOCATE_SOURCE_SYNTAX: u32 = 95;
pub const ROUP_FIELD_LOOP_MODIFIER: u32 = 100;
pub const ROUP_FIELD_INDICES: u32 = 101;
pub const ROUP_FIELD_APPLIED_DIRECTIVES: u32 = 102;
pub const ROUP_FIELD_IDENTIFIER: u32 = 103;
pub const ROUP_FIELD_INTEROP_TYPES: u32 = 104;
pub const ROUP_FIELD_PREFERENCES: u32 = 105;
pub const ROUP_FIELD_SELECTORS: u32 = 106;
pub const ROUP_FIELD_ATTRIBUTES: u32 = 107;
pub const ROUP_FIELD_LOCATOR: u32 = 108;
pub const ROUP_FIELD_ITERATION: u32 = 109;
pub const ROUP_FIELD_DEPENDENCE: u32 = 110;
pub const ROUP_FIELD_PROPERTIES: u32 = 120;
pub const ROUP_FIELD_TRAIT_NAME: u32 = 121;
pub const ROUP_FIELD_REQUIREMENT: u32 = 122;
pub const ROUP_FIELD_SOURCE_ALIAS: u32 = 123;
pub const ROUP_FIELD_QUEUES_KEYWORD: u32 = 124;
pub const ROUP_FIELD_MAP_TYPE_SPELLING: u32 = 125;
pub const ROUP_FIELD_PRECEDING_SEPARATOR: u32 = 126;
pub const ROUP_FIELD_QUOTE_STYLE: u32 = 127;
pub const ROUP_FIELD_DECLARATOR_ATTACHED: u32 = 128;
pub const ROUP_FIELD_LENGTH: u32 = 129;
pub const ROUP_FIELD_STRIDE: u32 = 130;
pub const ROUP_FIELD_SOURCE_SPELLING: u32 = 131;
pub const ROUP_FIELD_OPERAND: u32 = 132;
pub const ROUP_FIELD_LEFT: u32 = 133;
pub const ROUP_FIELD_RIGHT: u32 = 134;
pub const ROUP_FIELD_THEN_EXPRESSION: u32 = 135;
pub const ROUP_FIELD_ELSE_EXPRESSION: u32 = 136;
pub const ROUP_FIELD_TARGET: u32 = 137;
pub const ROUP_FIELD_CALLEE: u32 = 138;
pub const ROUP_FIELD_MEMBER: u32 = 139;
pub const ROUP_FIELD_ACCESS: u32 = 140;
pub const ROUP_FIELD_SEMANTICS: u32 = 141;
pub const ROUP_FIELD_TOKENS: u32 = 142;
pub const ROUP_FIELD_PROFILE: u32 = 143;
pub const ROUP_FIELD_HIGH: u32 = 144;
pub const ROUP_FIELD_LOW: u32 = 145;
pub const ROUP_FIELD_FRACTIONAL_DIGITS: u32 = 146;
pub const ROUP_FIELD_EXPONENT: u32 = 147;
pub const ROUP_FIELD_NEGATIVE: u32 = 148;
pub const ROUP_FIELD_UNSIGNED: u32 = 149;
pub const ROUP_FIELD_SIZE_T: u32 = 150;
pub const ROUP_FIELD_SYNTAX: u32 = 151;
pub const ROUP_FIELD_LANGUAGE: u32 = 152;
pub const ROUP_FIELD_COMPACT_SPELLING: u32 = 153;
pub const ROUP_FIELD_CANONICAL_SPELLING: u32 = 154;

pub const ROUP_OMP_CLAUSE_ALIAS_DEPEND_SOURCE: u32 = 1;
pub const ROUP_OMP_CLAUSE_ALIAS_DEPEND_SOURCE_CURRENT: u32 = 2;
pub const ROUP_OMP_CLAUSE_ALIAS_DEPEND_SINK: u32 = 3;
pub const ROUP_OMP_CLAUSE_ALIAS_DEPEND_SINK_PREVIOUS_CURRENT: u32 = 4;
pub const ROUP_OMP_CLAUSE_ALIAS_METADIRECTIVE_DEFAULT: u32 = 5;
pub const ROUP_OMP_CLAUSE_ALIAS_DECLARE_TARGET_TO: u32 = 6;
pub const ROUP_OMP_CLAUSE_ALIAS_PROC_BIND_MASTER: u32 = 7;
pub const ROUP_OMP_CLAUSE_ALIAS_DOACROSS_SOURCE_EMPTY: u32 = 8;
pub const ROUP_OMP_CLAUSE_ALIAS_REDUCTION_ORIGINAL_POSITIONAL: u32 = 9;

pub const ROUP_OMP_DIRECTIVE_ALIAS_NONE: u32 = 0;
pub const ROUP_OMP_DIRECTIVE_ALIAS_OPENMP60_UNDERSCORE: u32 = 1;
pub const ROUP_OMP_DIRECTIVE_ALIAS_FORTRAN_COMPACT: u32 = 2;
pub const ROUP_OMP_DIRECTIVE_ALIAS_FORTRAN_REDUNDANT_OMP: u32 = 3;

pub const ROUP_OMP_CLAUSE_SEPARATOR_SPACE: u32 = 1;
pub const ROUP_OMP_CLAUSE_SEPARATOR_COMMA: u32 = 2;

pub const ROUP_OMP_DECLARE_REDUCTION_INLINE_COMBINER: u32 = 1;
pub const ROUP_OMP_DECLARE_REDUCTION_COMBINER_CLAUSE: u32 = 2;

pub const ROUP_QUOTE_SINGLE: u32 = 1;
pub const ROUP_QUOTE_DOUBLE: u32 = 2;

pub const ROUP_OMP_USES_ALLOCATORS_HISTORICAL: u32 = 1;
pub const ROUP_OMP_USES_ALLOCATORS_MODIFIER: u32 = 2;

pub const ROUP_ACC_CLAUSE_ALIAS_PCOPY: u32 = 1;
pub const ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPY: u32 = 2;
pub const ROUP_ACC_CLAUSE_ALIAS_PCOPYIN: u32 = 3;
pub const ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPYIN: u32 = 4;
pub const ROUP_ACC_CLAUSE_ALIAS_PCOPYOUT: u32 = 5;
pub const ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPYOUT: u32 = 6;
pub const ROUP_ACC_CLAUSE_ALIAS_PCREATE: u32 = 7;
pub const ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_CREATE: u32 = 8;
pub const ROUP_ACC_CLAUSE_ALIAS_UPDATE_HOST: u32 = 9;

pub const ROUP_NODE_FAMILY_REQUIRE_MODIFIER: u32 = 3;
pub const ROUP_NODE_FAMILY_DEPEND_ITERATOR: u32 = 4;
pub const ROUP_NODE_FAMILY_USES_ALLOCATOR: u32 = 5;
pub const ROUP_NODE_FAMILY_OMP_DIRECTIVE: u32 = 6;
pub const ROUP_NODE_FAMILY_OMP_CLAUSE: u32 = 7;
pub const ROUP_NODE_FAMILY_REDUCTION_MODIFIER: u32 = 8;
pub const ROUP_NODE_FAMILY_OMP_PARAMETER: u32 = 10;
pub const ROUP_NODE_FAMILY_OMP_INDUCTION_TYPE: u32 = 12;
pub const ROUP_NODE_FAMILY_ACC_SIZE_EXPRESSION: u32 = 13;
pub const ROUP_NODE_FAMILY_ACC_GANG_ARGUMENT: u32 = 14;
pub const ROUP_NODE_FAMILY_ACC_CACHE_ITEM: u32 = 15;
pub const ROUP_NODE_FAMILY_ACC_END_KIND: u32 = 16;
pub const ROUP_NODE_FAMILY_ACC_BIND_TARGET: u32 = 17;
pub const ROUP_NODE_FAMILY_CLAUSE_ITEM: u32 = 18;
pub const ROUP_NODE_FAMILY_OMP_STORAGE_ITEM: u32 = 19;
pub const ROUP_NODE_FAMILY_OMP_DECLARE_TARGET_ITEM: u32 = 20;
pub const ROUP_NODE_FAMILY_OMP_FLUSH_ITEM: u32 = 21;
pub const ROUP_NODE_FAMILY_OMP_MAPPER_ID: u32 = 22;
pub const ROUP_NODE_FAMILY_OMP_ID_EXPRESSION: u32 = 23;
pub const ROUP_NODE_FAMILY_OMP_CPP_OPERATOR_QUALIFIER: u32 = 24;
pub const ROUP_NODE_FAMILY_OMP_IDENTIFIER: u32 = 25;
pub const ROUP_NODE_FAMILY_OMP_STYLIZED_EXPRESSION: u32 = 26;
pub const ROUP_NODE_FAMILY_OMP_REDUCTION_INITIALIZER: u32 = 27;
pub const ROUP_NODE_FAMILY_OMP_INITIALIZER_VALUE: u32 = 28;
pub const ROUP_NODE_FAMILY_OMP_ALLOCATOR_KIND: u32 = 29;
pub const ROUP_NODE_FAMILY_ACC_DEVICE_TYPE: u32 = 30;
pub const ROUP_NODE_FAMILY_ACC_REDUCTION_OPERATOR: u32 = 31;
pub const ROUP_NODE_FAMILY_OMP_COUNT: u32 = 32;
pub const ROUP_NODE_FAMILY_OMP_LOCATOR: u32 = 33;
pub const ROUP_NODE_FAMILY_OMP_PARAMETER_LIST_ITEM: u32 = 40;
pub const ROUP_NODE_FAMILY_OMP_APPEND_OPERATION: u32 = 41;
pub const ROUP_NODE_FAMILY_OMP_APPLY_MODIFIER: u32 = 50;
pub const ROUP_NODE_FAMILY_OMP_PREFERENCE_SPECIFICATION: u32 = 51;
pub const ROUP_NODE_FAMILY_OMP_PREFERENCE_SELECTOR: u32 = 52;
pub const ROUP_NODE_FAMILY_OMP_FOREIGN_RUNTIME_IDENTIFIER: u32 = 53;
pub const ROUP_NODE_FAMILY_STRING_LITERAL: u32 = 54;
pub const ROUP_NODE_FAMILY_OMP_DEPENDENCE: u32 = 55;
pub const ROUP_NODE_FAMILY_OMP_DOACROSS_ITERATION: u32 = 56;
pub const ROUP_NODE_FAMILY_OMP_DOACROSS_VECTOR_ITEM: u32 = 57;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_ENTRY: u32 = 60;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_DEVICE_TRAIT: u32 = 61;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_IMPLEMENTATION_TRAIT: u32 = 62;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_NAME_LIST_TRAIT: u32 = 63;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_EXTENSION_TRAIT: u32 = 64;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_EXTENSION_PROPERTY: u32 = 65;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_REQUIREMENT: u32 = 66;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_CONSTRUCT: u32 = 67;
pub const ROUP_NODE_FAMILY_OMP_SELECTOR_TRAIT_VALUE: u32 = 68;
pub const ROUP_NODE_FAMILY_OMP_ARRAY_SHAPING_SUBSCRIPT: u32 = 69;
pub const ROUP_NODE_FAMILY_OMPX_PAYLOAD_ITEM: u32 = 70;
pub const ROUP_NODE_FAMILY_HOST_EXPRESSION: u32 = 80;
pub const ROUP_NODE_FAMILY_HOST_LITERAL: u32 = 81;
pub const ROUP_NODE_FAMILY_HOST_TYPE_NAME: u32 = 82;
pub const ROUP_NODE_FAMILY_HOST_TEMPLATE_ARGUMENT: u32 = 83;
pub const ROUP_NODE_FAMILY_HOST_SUBSCRIPT: u32 = 84;
pub const ROUP_NODE_FAMILY_HOST_ARRAY_SECTION: u32 = 85;
pub const ROUP_NODE_FAMILY_HOST_FORTRAN_ARGUMENT: u32 = 86;
pub const ROUP_NODE_FAMILY_HOST_TYPE_TOKEN: u32 = 87;
pub const ROUP_NODE_FAMILY_HOST_LITERAL_CODE_UNIT: u32 = 88;
pub const ROUP_NODE_FAMILY_HOST_TYPE_SYNTAX: u32 = 89;
pub const ROUP_NODE_FAMILY_HOST_INTEGER_SUFFIX: u32 = 90;
pub const ROUP_NODE_FAMILY_HOST_REAL_SUFFIX: u32 = 91;
pub const ROUP_NODE_FAMILY_HOST_VARIABLE: u32 = 92;
pub const ROUP_NODE_FAMILY_HOST_LVALUE: u32 = 93;

pub const ROUP_HOST_EXPR_LITERAL: u32 = 1;
pub const ROUP_HOST_EXPR_NAME: u32 = 2;
pub const ROUP_HOST_EXPR_THIS: u32 = 3;
pub const ROUP_HOST_EXPR_SIZEOF_TYPE: u32 = 4;
pub const ROUP_HOST_EXPR_SIZEOF_EXPRESSION: u32 = 5;
pub const ROUP_HOST_EXPR_CPP_TEMPLATE_ID: u32 = 6;
pub const ROUP_HOST_EXPR_LEGACY_QUALIFIED_INTEGER: u32 = 7;
pub const ROUP_HOST_EXPR_LEGACY_QUALIFIED_NAME: u32 = 8;
pub const ROUP_HOST_EXPR_LEGACY_FORTRAN_SUBSCRIPT: u32 = 9;
pub const ROUP_HOST_EXPR_LEGACY_FORTRAN_UNARY_DESIGNATOR: u32 = 10;
pub const ROUP_HOST_EXPR_PARENTHESIZED: u32 = 11;
pub const ROUP_HOST_EXPR_UNARY: u32 = 12;
pub const ROUP_HOST_EXPR_FORTRAN_DEFINED_UNARY: u32 = 13;
pub const ROUP_HOST_EXPR_BINARY: u32 = 14;
pub const ROUP_HOST_EXPR_FORTRAN_DEFINED_BINARY: u32 = 15;
pub const ROUP_HOST_EXPR_CONDITIONAL: u32 = 16;
pub const ROUP_HOST_EXPR_ASSIGNMENT: u32 = 17;
pub const ROUP_HOST_EXPR_CALL: u32 = 18;
pub const ROUP_HOST_EXPR_SUBSCRIPT: u32 = 19;
pub const ROUP_HOST_EXPR_MEMBER: u32 = 20;
pub const ROUP_HOST_EXPR_POSTFIX: u32 = 21;
pub const ROUP_HOST_EXPR_FORTRAN_APPLY: u32 = 22;
pub const ROUP_HOST_EXPR_SIZEOF_AMBIGUOUS: u32 = 23;

pub const ROUP_HOST_LITERAL_BOOLEAN: u32 = 1;
pub const ROUP_HOST_LITERAL_NULL_POINTER: u32 = 2;
pub const ROUP_HOST_LITERAL_INTEGER: u32 = 3;
pub const ROUP_HOST_LITERAL_REAL: u32 = 4;
pub const ROUP_HOST_LITERAL_CHARACTER: u32 = 5;
pub const ROUP_HOST_LITERAL_STRING: u32 = 6;

pub const ROUP_HOST_TEMPLATE_ARGUMENT_TYPE: u32 = 1;
pub const ROUP_HOST_TEMPLATE_ARGUMENT_EXPRESSION: u32 = 2;
pub const ROUP_HOST_TEMPLATE_ARGUMENT_AMBIGUOUS: u32 = 3;
pub const ROUP_HOST_SUBSCRIPT_INDEX: u32 = 1;
pub const ROUP_HOST_SUBSCRIPT_SECTION: u32 = 2;
pub const ROUP_HOST_FORTRAN_ARGUMENT_POSITIONAL: u32 = 1;
pub const ROUP_HOST_FORTRAN_ARGUMENT_KEYWORD: u32 = 2;
pub const ROUP_HOST_FORTRAN_ARGUMENT_SECTION: u32 = 3;
pub const ROUP_HOST_LITERAL_CODE_UNIT_SCALAR: u32 = 1;
pub const ROUP_HOST_LITERAL_CODE_UNIT_NUMERIC_ESCAPE: u32 = 2;
pub const ROUP_HOST_TYPE_SYNTAX_TOKEN: u32 = 1;
pub const ROUP_HOST_TYPE_SYNTAX_PARENTHESIZED: u32 = 2;
pub const ROUP_HOST_TYPE_SYNTAX_BRACKETED: u32 = 3;
pub const ROUP_HOST_TYPE_SYNTAX_TEMPLATE_ARGUMENTS: u32 = 4;
pub const ROUP_HOST_TYPE_SYNTAX_TEMPLATE_ARGUMENT: u32 = 5;

pub const ROUP_HOST_ARRAY_SECTION: u32 = 1;
pub const ROUP_HOST_SECTION_C_LENGTH: u32 = 1;
pub const ROUP_HOST_SECTION_FORTRAN_UPPER_BOUND: u32 = 2;

pub const ROUP_HOST_LEGACY_FORTRAN_UNARY_DEREFERENCE: u32 = 1;
pub const ROUP_HOST_LEGACY_FORTRAN_UNARY_ADDRESS_OF: u32 = 2;
pub const ROUP_HOST_UNARY_PLUS: u32 = 1;
pub const ROUP_HOST_UNARY_MINUS: u32 = 2;
pub const ROUP_HOST_UNARY_LOGICAL_NOT: u32 = 3;
pub const ROUP_HOST_UNARY_BITWISE_NOT: u32 = 4;
pub const ROUP_HOST_UNARY_DEREFERENCE: u32 = 5;
pub const ROUP_HOST_UNARY_ADDRESS_OF: u32 = 6;
pub const ROUP_HOST_UNARY_PRE_INCREMENT: u32 = 7;
pub const ROUP_HOST_UNARY_PRE_DECREMENT: u32 = 8;
pub const ROUP_HOST_BINARY_POWER: u32 = 1;
pub const ROUP_HOST_BINARY_MULTIPLY: u32 = 2;
pub const ROUP_HOST_BINARY_DIVIDE: u32 = 3;
pub const ROUP_HOST_BINARY_REMAINDER: u32 = 4;
pub const ROUP_HOST_BINARY_ADD: u32 = 5;
pub const ROUP_HOST_BINARY_SUBTRACT: u32 = 6;
pub const ROUP_HOST_BINARY_CONCATENATE: u32 = 7;
pub const ROUP_HOST_BINARY_SHIFT_LEFT: u32 = 8;
pub const ROUP_HOST_BINARY_SHIFT_RIGHT: u32 = 9;
pub const ROUP_HOST_BINARY_LESS: u32 = 10;
pub const ROUP_HOST_BINARY_LESS_EQUAL: u32 = 11;
pub const ROUP_HOST_BINARY_GREATER: u32 = 12;
pub const ROUP_HOST_BINARY_GREATER_EQUAL: u32 = 13;
pub const ROUP_HOST_BINARY_EQUAL: u32 = 14;
pub const ROUP_HOST_BINARY_NOT_EQUAL: u32 = 15;
pub const ROUP_HOST_BINARY_BITWISE_AND: u32 = 16;
pub const ROUP_HOST_BINARY_BITWISE_XOR: u32 = 17;
pub const ROUP_HOST_BINARY_BITWISE_OR: u32 = 18;
pub const ROUP_HOST_BINARY_LOGICAL_AND: u32 = 19;
pub const ROUP_HOST_BINARY_LOGICAL_OR: u32 = 20;
pub const ROUP_HOST_BINARY_LOGICAL_EQV: u32 = 21;
pub const ROUP_HOST_BINARY_LOGICAL_NEQV: u32 = 22;
pub const ROUP_HOST_BINARY_COMMA: u32 = 23;
pub const ROUP_HOST_ASSIGNMENT_ASSIGN: u32 = 1;
pub const ROUP_HOST_ASSIGNMENT_ADD: u32 = 2;
pub const ROUP_HOST_ASSIGNMENT_SUBTRACT: u32 = 3;
pub const ROUP_HOST_ASSIGNMENT_MULTIPLY: u32 = 4;
pub const ROUP_HOST_ASSIGNMENT_DIVIDE: u32 = 5;
pub const ROUP_HOST_ASSIGNMENT_REMAINDER: u32 = 6;
pub const ROUP_HOST_ASSIGNMENT_SHIFT_LEFT: u32 = 7;
pub const ROUP_HOST_ASSIGNMENT_SHIFT_RIGHT: u32 = 8;
pub const ROUP_HOST_ASSIGNMENT_BITWISE_AND: u32 = 9;
pub const ROUP_HOST_ASSIGNMENT_BITWISE_XOR: u32 = 10;
pub const ROUP_HOST_ASSIGNMENT_BITWISE_OR: u32 = 11;
pub const ROUP_HOST_POSTFIX_INCREMENT: u32 = 1;
pub const ROUP_HOST_POSTFIX_DECREMENT: u32 = 2;
pub const ROUP_HOST_MEMBER_DOT: u32 = 1;
pub const ROUP_HOST_MEMBER_ARROW: u32 = 2;
pub const ROUP_HOST_MEMBER_SCOPE: u32 = 3;
pub const ROUP_HOST_MEMBER_FORTRAN_COMPONENT: u32 = 4;

pub const ROUP_HOST_INTEGER_BASE_BINARY: u32 = 2;
pub const ROUP_HOST_INTEGER_BASE_OCTAL: u32 = 8;
pub const ROUP_HOST_INTEGER_BASE_DECIMAL: u32 = 10;
pub const ROUP_HOST_INTEGER_BASE_HEXADECIMAL: u32 = 16;
pub const ROUP_HOST_LITERAL_ESCAPE_OCTAL: u32 = 8;
pub const ROUP_HOST_LITERAL_ESCAPE_HEXADECIMAL: u32 = 16;
pub const ROUP_HOST_INTEGER_SUFFIX_NONE: u32 = 1;
pub const ROUP_HOST_INTEGER_SUFFIX_C: u32 = 2;
pub const ROUP_HOST_INTEGER_SUFFIX_FORTRAN_NUMERIC: u32 = 3;
pub const ROUP_HOST_INTEGER_SUFFIX_FORTRAN_NAMED: u32 = 4;
pub const ROUP_HOST_C_INTEGER_WIDTH_DEFAULT: u32 = 1;
pub const ROUP_HOST_C_INTEGER_WIDTH_LONG: u32 = 2;
pub const ROUP_HOST_C_INTEGER_WIDTH_LONG_LONG: u32 = 3;
pub const ROUP_HOST_REAL_SUFFIX_C_FLOAT: u32 = 1;
pub const ROUP_HOST_REAL_SUFFIX_C_DOUBLE: u32 = 2;
pub const ROUP_HOST_REAL_SUFFIX_C_LONG_DOUBLE: u32 = 3;
pub const ROUP_HOST_REAL_SUFFIX_FORTRAN_DEFAULT: u32 = 4;
pub const ROUP_HOST_REAL_SUFFIX_FORTRAN_NUMERIC: u32 = 5;
pub const ROUP_HOST_REAL_SUFFIX_FORTRAN_NAMED: u32 = 6;
pub const ROUP_HOST_REAL_EXPONENT_E: u32 = 1;
pub const ROUP_HOST_REAL_EXPONENT_D: u32 = 2;

pub const ROUP_HOST_TYPE_TOKEN_IDENTIFIER: u32 = 1;
pub const ROUP_HOST_TYPE_TOKEN_RESERVED_KEYWORD: u32 = 2;
pub const ROUP_HOST_TYPE_TOKEN_INTEGER: u32 = 3;
pub const ROUP_HOST_TYPE_TOKEN_REAL: u32 = 4;
pub const ROUP_HOST_TYPE_TOKEN_CHARACTER: u32 = 5;
pub const ROUP_HOST_TYPE_TOKEN_STRING: u32 = 6;
pub const ROUP_HOST_TYPE_TOKEN_BOOLEAN: u32 = 7;
pub const ROUP_HOST_TYPE_TOKEN_NULL_POINTER: u32 = 8;
pub const ROUP_HOST_TYPE_TOKEN_LEFT_PAREN: u32 = 9;
pub const ROUP_HOST_TYPE_TOKEN_RIGHT_PAREN: u32 = 10;
pub const ROUP_HOST_TYPE_TOKEN_LEFT_BRACKET: u32 = 11;
pub const ROUP_HOST_TYPE_TOKEN_RIGHT_BRACKET: u32 = 12;
pub const ROUP_HOST_TYPE_TOKEN_COMMA: u32 = 13;
pub const ROUP_HOST_TYPE_TOKEN_QUESTION: u32 = 14;
pub const ROUP_HOST_TYPE_TOKEN_COLON: u32 = 15;
pub const ROUP_HOST_TYPE_TOKEN_SCOPE: u32 = 16;
pub const ROUP_HOST_TYPE_TOKEN_DOT: u32 = 17;
pub const ROUP_HOST_TYPE_TOKEN_PERCENT: u32 = 18;
pub const ROUP_HOST_TYPE_TOKEN_ARROW: u32 = 19;
pub const ROUP_HOST_TYPE_TOKEN_PLUS: u32 = 20;
pub const ROUP_HOST_TYPE_TOKEN_MINUS: u32 = 21;
pub const ROUP_HOST_TYPE_TOKEN_STAR: u32 = 22;
pub const ROUP_HOST_TYPE_TOKEN_SLASH: u32 = 23;
pub const ROUP_HOST_TYPE_TOKEN_POWER: u32 = 24;
pub const ROUP_HOST_TYPE_TOKEN_CONCAT: u32 = 25;
pub const ROUP_HOST_TYPE_TOKEN_REMAINDER: u32 = 26;
pub const ROUP_HOST_TYPE_TOKEN_LOGICAL_NOT: u32 = 27;
pub const ROUP_HOST_TYPE_TOKEN_BITWISE_NOT: u32 = 28;
pub const ROUP_HOST_TYPE_TOKEN_AMPERSAND: u32 = 29;
pub const ROUP_HOST_TYPE_TOKEN_PIPE: u32 = 30;
pub const ROUP_HOST_TYPE_TOKEN_CARET: u32 = 31;
pub const ROUP_HOST_TYPE_TOKEN_LOGICAL_AND: u32 = 32;
pub const ROUP_HOST_TYPE_TOKEN_LOGICAL_OR: u32 = 33;
pub const ROUP_HOST_TYPE_TOKEN_LOGICAL_EQV: u32 = 34;
pub const ROUP_HOST_TYPE_TOKEN_LOGICAL_NEQV: u32 = 35;
pub const ROUP_HOST_TYPE_TOKEN_FORTRAN_DEFINED_OPERATOR: u32 = 36;
pub const ROUP_HOST_TYPE_TOKEN_EQUAL: u32 = 37;
pub const ROUP_HOST_TYPE_TOKEN_EQUAL_EQUAL: u32 = 38;
pub const ROUP_HOST_TYPE_TOKEN_NOT_EQUAL: u32 = 39;
pub const ROUP_HOST_TYPE_TOKEN_LESS: u32 = 40;
pub const ROUP_HOST_TYPE_TOKEN_LESS_EQUAL: u32 = 41;
pub const ROUP_HOST_TYPE_TOKEN_GREATER: u32 = 42;
pub const ROUP_HOST_TYPE_TOKEN_GREATER_EQUAL: u32 = 43;
pub const ROUP_HOST_TYPE_TOKEN_SHIFT_LEFT: u32 = 44;
pub const ROUP_HOST_TYPE_TOKEN_SHIFT_RIGHT: u32 = 45;
pub const ROUP_HOST_TYPE_TOKEN_PLUS_PLUS: u32 = 46;
pub const ROUP_HOST_TYPE_TOKEN_MINUS_MINUS: u32 = 47;
pub const ROUP_HOST_TYPE_TOKEN_PLUS_EQUAL: u32 = 48;
pub const ROUP_HOST_TYPE_TOKEN_MINUS_EQUAL: u32 = 49;
pub const ROUP_HOST_TYPE_TOKEN_STAR_EQUAL: u32 = 50;
pub const ROUP_HOST_TYPE_TOKEN_SLASH_EQUAL: u32 = 51;
pub const ROUP_HOST_TYPE_TOKEN_REMAINDER_EQUAL: u32 = 52;
pub const ROUP_HOST_TYPE_TOKEN_AMPERSAND_EQUAL: u32 = 53;
pub const ROUP_HOST_TYPE_TOKEN_PIPE_EQUAL: u32 = 54;
pub const ROUP_HOST_TYPE_TOKEN_CARET_EQUAL: u32 = 55;
pub const ROUP_HOST_TYPE_TOKEN_SHIFT_LEFT_EQUAL: u32 = 56;
pub const ROUP_HOST_TYPE_TOKEN_SHIFT_RIGHT_EQUAL: u32 = 57;
pub const ROUP_HOST_TYPE_TOKEN_END: u32 = 58;

pub const ROUP_NODE_RECORD: u32 = 1;

pub const ROUP_OMP_APPLY_FUSED: u32 = 1;
pub const ROUP_OMP_APPLY_GRID: u32 = 2;
pub const ROUP_OMP_APPLY_IDENTITY: u32 = 3;
pub const ROUP_OMP_APPLY_INTERCHANGED: u32 = 4;
pub const ROUP_OMP_APPLY_INTRATILE: u32 = 5;
pub const ROUP_OMP_APPLY_OFFSETS: u32 = 6;
pub const ROUP_OMP_APPLY_REVERSED: u32 = 7;
pub const ROUP_OMP_APPLY_SPLIT: u32 = 8;
pub const ROUP_OMP_APPLY_UNROLLED: u32 = 9;

pub const ROUP_OMP_INDUCTION_RELAXED: u32 = 1;
pub const ROUP_OMP_INDUCTION_STRICT: u32 = 2;

pub const ROUP_OMP_INTEROP_TARGET: u32 = 1;
pub const ROUP_OMP_INTEROP_TARGETSYNC: u32 = 2;
pub const ROUP_OMP_PREFERENCE_FOREIGN_RUNTIME: u32 = 1;
pub const ROUP_OMP_PREFERENCE_SELECTORS: u32 = 2;
pub const ROUP_OMP_PREFERENCE_SELECTOR_FOREIGN_RUNTIME: u32 = 1;
pub const ROUP_OMP_PREFERENCE_SELECTOR_ATTRIBUTES: u32 = 2;
pub const ROUP_OMP_FOREIGN_RUNTIME_STRING: u32 = 1;
pub const ROUP_OMP_FOREIGN_RUNTIME_EXPRESSION: u32 = 2;
pub const ROUP_STRING_LITERAL: u32 = 1;

pub const ROUP_OMP_PARAMETER_NAMED: u32 = 1;
pub const ROUP_OMP_PARAMETER_POSITION: u32 = 2;
pub const ROUP_OMP_PARAMETER_RANGE: u32 = 3;

pub const ROUP_OMP_APPEND_INTEROP: u32 = 1;

pub const ROUP_OMP_DEPENDENCE_LOCATORS: u32 = 1;
pub const ROUP_OMP_DEPENDENCE_DEPOBJS: u32 = 2;

pub const ROUP_OMP_DOACROSS_CURRENT: u32 = 1;
pub const ROUP_OMP_DOACROSS_PREVIOUS_CURRENT: u32 = 2;
pub const ROUP_OMP_DOACROSS_VECTOR: u32 = 3;
pub const ROUP_OMP_DOACROSS_VECTOR_ITEM: u32 = 1;
pub const ROUP_OMP_DOACROSS_OFFSET_ADD: u32 = 1;
pub const ROUP_OMP_DOACROSS_OFFSET_SUBTRACT: u32 = 2;

pub const ROUP_INDUCTION_TYPE_SAME: u32 = 1;
pub const ROUP_INDUCTION_TYPE_PAIR: u32 = 2;

pub const ROUP_ACC_SIZE_AUTOMATIC: u32 = 1;
pub const ROUP_ACC_SIZE_EXPRESSION: u32 = 2;

pub const ROUP_ACC_GANG_POSITIONAL: u32 = 1;
pub const ROUP_ACC_GANG_NUM: u32 = 2;
pub const ROUP_ACC_GANG_DIM: u32 = 3;
pub const ROUP_ACC_GANG_STATIC: u32 = 4;

pub const ROUP_ACC_CACHE_ARRAY_ELEMENT: u32 = 1;
pub const ROUP_ACC_CACHE_CONTIGUOUS_SUBARRAY: u32 = 2;
pub const ROUP_ACC_CACHE_SCALAR: u32 = 3;

pub const ROUP_ACC_END_ATOMIC: u32 = 1;
pub const ROUP_ACC_END_DATA: u32 = 2;
pub const ROUP_ACC_END_HOST_DATA: u32 = 3;
pub const ROUP_ACC_END_KERNELS: u32 = 4;
pub const ROUP_ACC_END_KERNELS_LOOP: u32 = 5;
pub const ROUP_ACC_END_LOOP: u32 = 6;
pub const ROUP_ACC_END_PARALLEL: u32 = 7;
pub const ROUP_ACC_END_PARALLEL_LOOP: u32 = 8;
pub const ROUP_ACC_END_SERIAL: u32 = 9;
pub const ROUP_ACC_END_SERIAL_LOOP: u32 = 10;

pub const ROUP_ACC_BIND_NAME: u32 = 1;
pub const ROUP_ACC_BIND_STRING_LITERAL: u32 = 2;

pub const ROUP_CLAUSE_ITEM_IDENTIFIER: u32 = 1;
pub const ROUP_CLAUSE_ITEM_VARIABLE: u32 = 2;
pub const ROUP_CLAUSE_ITEM_FORTRAN_COMMON_BLOCK: u32 = 3;
pub const ROUP_CLAUSE_ITEM_EXPRESSION: u32 = 4;
pub const ROUP_CLAUSE_ITEM_OMPPARSER_TRAILING_SLASH: u32 = 5;
pub const ROUP_CLAUSE_ITEM_LVALUE: u32 = 6;

pub const ROUP_OMP_STORAGE_ITEM_NAME: u32 = 1;
pub const ROUP_OMP_STORAGE_ITEM_FORTRAN_COMMON_BLOCK: u32 = 2;

pub const ROUP_OMP_DECLARE_TARGET_ITEM_NAME: u32 = 1;
pub const ROUP_OMP_DECLARE_TARGET_ITEM_FORTRAN_COMMON_BLOCK: u32 = 2;

pub const ROUP_OMP_FLUSH_ITEM_IDENTIFIER: u32 = 1;
pub const ROUP_OMP_FLUSH_ITEM_VARIABLE: u32 = 2;
pub const ROUP_OMP_FLUSH_ITEM_FORTRAN_COMMON_BLOCK: u32 = 3;

pub const ROUP_OMP_MAPPER_ID_DEFAULT: u32 = 1;
pub const ROUP_OMP_MAPPER_ID_USER: u32 = 2;

pub const ROUP_OMP_ID_EXPRESSION_NAME: u32 = 1;
pub const ROUP_OMP_ID_EXPRESSION_CPP_TEMPLATE_ID: u32 = 2;
pub const ROUP_OMP_ID_EXPRESSION_CPP_OPERATOR_FUNCTION: u32 = 3;

pub const ROUP_OMP_CPP_OPERATOR_QUALIFIER_NAME: u32 = 1;
pub const ROUP_OMP_CPP_OPERATOR_QUALIFIER_TEMPLATE_ID: u32 = 2;

pub const ROUP_OMP_IDENTIFIER_ADD: u32 = 1;
pub const ROUP_OMP_IDENTIFIER_SUBTRACT: u32 = 2;
pub const ROUP_OMP_IDENTIFIER_MULTIPLY: u32 = 3;
pub const ROUP_OMP_IDENTIFIER_BITWISE_AND: u32 = 4;
pub const ROUP_OMP_IDENTIFIER_BITWISE_OR: u32 = 5;
pub const ROUP_OMP_IDENTIFIER_BITWISE_XOR: u32 = 6;
pub const ROUP_OMP_IDENTIFIER_LOGICAL_AND: u32 = 7;
pub const ROUP_OMP_IDENTIFIER_LOGICAL_OR: u32 = 8;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_AND: u32 = 9;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_OR: u32 = 10;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_EQV: u32 = 11;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_NEQV: u32 = 12;
pub const ROUP_OMP_IDENTIFIER_NAME: u32 = 13;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_MAX: u32 = 14;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_MIN: u32 = 15;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_IAND: u32 = 16;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_IOR: u32 = 17;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_IEOR: u32 = 18;
pub const ROUP_OMP_IDENTIFIER_FORTRAN_DEFINED_OPERATOR: u32 = 19;

pub const ROUP_OMP_STYLIZED_C_CPP_EXPRESSION: u32 = 1;
pub const ROUP_OMP_STYLIZED_FORTRAN_ASSIGNMENT: u32 = 2;
pub const ROUP_OMP_STYLIZED_FORTRAN_SUBROUTINE_CALL: u32 = 3;

pub const ROUP_OMP_INITIALIZER_C_ASSIGNMENT: u32 = 1;
pub const ROUP_OMP_INITIALIZER_CPP_COPY: u32 = 2;
pub const ROUP_OMP_INITIALIZER_CPP_DIRECT: u32 = 3;
pub const ROUP_OMP_INITIALIZER_CPP_LIST: u32 = 4;
pub const ROUP_OMP_INITIALIZER_C_CPP_FUNCTION_CALL: u32 = 5;
pub const ROUP_OMP_INITIALIZER_FORTRAN_ASSIGNMENT: u32 = 6;
pub const ROUP_OMP_INITIALIZER_FORTRAN_SUBROUTINE_CALL: u32 = 7;

pub const ROUP_OMP_INITIALIZER_VALUE_EXPRESSION: u32 = 1;
pub const ROUP_OMP_INITIALIZER_VALUE_BRACED: u32 = 2;

pub const ROUP_OMP_ALLOCATOR_NULL: u32 = 1;
pub const ROUP_OMP_ALLOCATOR_DEFAULT: u32 = 2;
pub const ROUP_OMP_ALLOCATOR_LARGE_CAP: u32 = 3;
pub const ROUP_OMP_ALLOCATOR_CONST: u32 = 4;
pub const ROUP_OMP_ALLOCATOR_HIGH_BW: u32 = 5;
pub const ROUP_OMP_ALLOCATOR_LOW_LAT: u32 = 6;
pub const ROUP_OMP_ALLOCATOR_CGROUP: u32 = 7;
pub const ROUP_OMP_ALLOCATOR_PTEAM: u32 = 8;
pub const ROUP_OMP_ALLOCATOR_THREAD: u32 = 9;
pub const ROUP_OMP_ALLOCATOR_CUSTOM: u32 = 10;

pub const ROUP_ACC_DEVICE_TYPE_HOST: u32 = 1;
pub const ROUP_ACC_DEVICE_TYPE_WILDCARD: u32 = 2;
pub const ROUP_ACC_DEVICE_TYPE_MULTICORE: u32 = 3;
pub const ROUP_ACC_DEVICE_TYPE_DEFAULT: u32 = 4;
pub const ROUP_ACC_DEVICE_TYPE_NAMED: u32 = 5;

pub const ROUP_ACC_REDUCTION_ADD: u32 = 1;
pub const ROUP_ACC_REDUCTION_MUL: u32 = 2;
pub const ROUP_ACC_REDUCTION_MAX: u32 = 3;
pub const ROUP_ACC_REDUCTION_MIN: u32 = 4;
pub const ROUP_ACC_REDUCTION_BIT_AND: u32 = 5;
pub const ROUP_ACC_REDUCTION_BIT_OR: u32 = 6;
pub const ROUP_ACC_REDUCTION_BIT_XOR: u32 = 7;
pub const ROUP_ACC_REDUCTION_LOG_AND: u32 = 8;
pub const ROUP_ACC_REDUCTION_LOG_OR: u32 = 9;
pub const ROUP_ACC_REDUCTION_FORTRAN_AND: u32 = 10;
pub const ROUP_ACC_REDUCTION_FORTRAN_OR: u32 = 11;
pub const ROUP_ACC_REDUCTION_FORTRAN_EQV: u32 = 12;
pub const ROUP_ACC_REDUCTION_FORTRAN_NEQV: u32 = 13;
pub const ROUP_ACC_REDUCTION_FORTRAN_IAND: u32 = 14;
pub const ROUP_ACC_REDUCTION_FORTRAN_IOR: u32 = 15;
pub const ROUP_ACC_REDUCTION_FORTRAN_IEOR: u32 = 16;
pub const ROUP_ACC_REDUCTION_SUB: u32 = 17;

pub const ROUP_OMP_COUNT_FILL: u32 = 1;
pub const ROUP_OMP_COUNT_EXPRESSION: u32 = 2;

pub const ROUP_OMP_LOCATOR_LVALUE: u32 = 1;
pub const ROUP_OMP_LOCATOR_FORTRAN_COMMON_BLOCK: u32 = 2;
pub const ROUP_OMP_LOCATOR_POTENTIAL_LVALUE: u32 = 3;
pub const ROUP_OMP_LOCATOR_ALL_MEMORY: u32 = 4;
pub const ROUP_OMP_LOCATOR_DISTRIBUTED: u32 = 5;
pub const ROUP_OMP_LOCATOR_ARRAY_SHAPING: u32 = 6;

pub const ROUP_OMP_ARRAY_SHAPING_INDEX: u32 = 1;
pub const ROUP_OMP_ARRAY_SHAPING_SECTION: u32 = 2;
pub const ROUP_OMP_DIST_DATA_DUPLICATE: u32 = 1;

pub const ROUP_OMP_DATA_MOTION_PRESENT: u32 = 1;
pub const ROUP_OMP_ENTER_AUTOMAP: u32 = 1;

pub const ROUP_OMP_CPP_OPERATOR_ADD: u32 = 1;
pub const ROUP_OMP_CPP_OPERATOR_SUBTRACT: u32 = 2;
pub const ROUP_OMP_CPP_OPERATOR_MULTIPLY: u32 = 3;
pub const ROUP_OMP_CPP_OPERATOR_BITWISE_AND: u32 = 4;
pub const ROUP_OMP_CPP_OPERATOR_BITWISE_OR: u32 = 5;
pub const ROUP_OMP_CPP_OPERATOR_BITWISE_XOR: u32 = 6;
pub const ROUP_OMP_CPP_OPERATOR_LOGICAL_AND: u32 = 7;
pub const ROUP_OMP_CPP_OPERATOR_LOGICAL_OR: u32 = 8;

pub const ROUP_OMP_CONSTRUCT_PARALLEL: u32 = 1;
pub const ROUP_OMP_CONSTRUCT_SECTIONS: u32 = 2;
pub const ROUP_OMP_CONSTRUCT_FOR: u32 = 3;
pub const ROUP_OMP_CONSTRUCT_TASKGROUP: u32 = 4;

pub const ROUP_OMP_SCAN_INCLUSIVE: u32 = 1;
pub const ROUP_OMP_SCAN_EXCLUSIVE: u32 = 2;
pub const ROUP_OMP_ADJUST_ARGS_NEED_DEVICE_PTR: u32 = 1;
pub const ROUP_OMP_ADJUST_ARGS_NEED_DEVICE_ADDR: u32 = 2;
pub const ROUP_OMP_ADJUST_ARGS_NOTHING: u32 = 3;
pub const ROUP_OMP_FIRSTPRIVATE_SAVED: u32 = 1;
pub const ROUP_OMP_LASTPRIVATE_CONDITIONAL: u32 = 1;
pub const ROUP_OMP_ORIGINAL_SHARING_DEFAULT: u32 = 1;
pub const ROUP_OMP_ORIGINAL_SHARING_PRIVATE: u32 = 2;
pub const ROUP_OMP_ORIGINAL_SHARING_SHARED: u32 = 3;

pub const ROUP_OMP_DEFAULT_SHARED: u32 = 1;
pub const ROUP_OMP_DEFAULT_NONE: u32 = 2;
pub const ROUP_OMP_DEFAULT_PRIVATE: u32 = 3;
pub const ROUP_OMP_DEFAULT_FIRSTPRIVATE: u32 = 4;

pub const ROUP_OMP_DEFAULTMAP_ALLOC: u32 = 1;
pub const ROUP_OMP_DEFAULTMAP_TO: u32 = 2;
pub const ROUP_OMP_DEFAULTMAP_FROM: u32 = 3;
pub const ROUP_OMP_DEFAULTMAP_TOFROM: u32 = 4;
pub const ROUP_OMP_DEFAULTMAP_FIRSTPRIVATE: u32 = 5;
pub const ROUP_OMP_DEFAULTMAP_NONE: u32 = 6;
pub const ROUP_OMP_DEFAULTMAP_DEFAULT: u32 = 7;
pub const ROUP_OMP_DEFAULTMAP_PRESENT: u32 = 8;
pub const ROUP_OMP_DEFAULTMAP_PRIVATE: u32 = 9;
pub const ROUP_OMP_DEFAULTMAP_SELF: u32 = 10;
pub const ROUP_OMP_DEFAULTMAP_STORAGE: u32 = 11;
pub const ROUP_OMP_DEFAULTMAP_CATEGORY_SCALAR: u32 = 1;
pub const ROUP_OMP_DEFAULTMAP_CATEGORY_AGGREGATE: u32 = 2;
pub const ROUP_OMP_DEFAULTMAP_CATEGORY_POINTER: u32 = 3;
pub const ROUP_OMP_DEFAULTMAP_CATEGORY_ALL: u32 = 4;
pub const ROUP_OMP_DEFAULTMAP_CATEGORY_ALLOCATABLE: u32 = 5;

pub const ROUP_OMP_MAP_TO: u32 = 1;
pub const ROUP_OMP_MAP_FROM: u32 = 2;
pub const ROUP_OMP_MAP_TOFROM: u32 = 3;
pub const ROUP_OMP_MAP_STORAGE: u32 = 4;
pub const ROUP_OMP_MAP_TYPE_SPELLING_CANONICAL: u32 = 1;
pub const ROUP_OMP_MAP_TYPE_SPELLING_ALLOC: u32 = 2;
pub const ROUP_OMP_MAP_TYPE_SPELLING_RELEASE: u32 = 3;
pub const ROUP_OMP_MAP_TYPE_SPELLING_DELETE: u32 = 4;
pub const ROUP_OMP_MAP_MODIFIER_ALWAYS: u32 = 1;
pub const ROUP_OMP_MAP_MODIFIER_CLOSE: u32 = 2;
pub const ROUP_OMP_MAP_MODIFIER_PRESENT: u32 = 3;
pub const ROUP_OMP_MAP_MODIFIER_SELF: u32 = 4;
pub const ROUP_OMP_MAP_MODIFIER_ITERATOR: u32 = 5;
pub const ROUP_OMP_MAP_MODIFIER_REF_POINTEE: u32 = 6;
pub const ROUP_OMP_MAP_MODIFIER_REF_POINTER: u32 = 7;
pub const ROUP_OMP_MAP_MODIFIER_REF_POINTER_AND_POINTEE: u32 = 8;
pub const ROUP_OMP_MAP_MODIFIER_DELETE: u32 = 9;

pub const ROUP_OMP_DEPEND_IN: u32 = 1;
pub const ROUP_OMP_DEPEND_OUT: u32 = 2;
pub const ROUP_OMP_DEPEND_INOUT: u32 = 3;
pub const ROUP_OMP_DEPEND_INOUTSET: u32 = 4;
pub const ROUP_OMP_DEPEND_MUTEXINOUTSET: u32 = 5;
pub const ROUP_OMP_DEPEND_DEPOBJ: u32 = 6;
pub const ROUP_OMP_DOACROSS_SOURCE: u32 = 1;
pub const ROUP_OMP_DOACROSS_SINK: u32 = 2;
pub const ROUP_OMP_AFFINITY_ITERATOR: u32 = 1;

pub const ROUP_OMP_SCHEDULE_STATIC: u32 = 1;
pub const ROUP_OMP_SCHEDULE_DYNAMIC: u32 = 2;
pub const ROUP_OMP_SCHEDULE_GUIDED: u32 = 3;
pub const ROUP_OMP_SCHEDULE_AUTO: u32 = 4;
pub const ROUP_OMP_SCHEDULE_RUNTIME: u32 = 5;
pub const ROUP_OMP_SCHEDULE_MODIFIER_MONOTONIC: u32 = 1;
pub const ROUP_OMP_SCHEDULE_MODIFIER_NONMONOTONIC: u32 = 2;
pub const ROUP_OMP_SCHEDULE_MODIFIER_SIMD: u32 = 3;
pub const ROUP_OMP_LINEAR_VAL: u32 = 1;
pub const ROUP_OMP_LINEAR_REF: u32 = 2;
pub const ROUP_OMP_LINEAR_UVAL: u32 = 3;
pub const ROUP_OMP_LINEAR_SOURCE_HISTORICAL: u32 = 1;
pub const ROUP_OMP_LINEAR_SOURCE_MODIFIER_PREFIX: u32 = 2;
pub const ROUP_OMP_LINEAR_SOURCE_CANONICAL_MODIFIERS: u32 = 3;
pub const ROUP_OMP_ALLOCATE_SOURCE_UNMODIFIED: u32 = 1;
pub const ROUP_OMP_ALLOCATE_SOURCE_SIMPLE_ALLOCATOR: u32 = 2;
pub const ROUP_OMP_ALLOCATE_SOURCE_MODIFIERS: u32 = 3;
pub const ROUP_OMP_NUM_THREADS_STRICT: u32 = 1;
pub const ROUP_OMP_MEMORY_SPACE_DEFAULT: u32 = 1;
pub const ROUP_OMP_MEMORY_SPACE_LARGE_CAP: u32 = 2;
pub const ROUP_OMP_MEMORY_SPACE_CONST: u32 = 3;
pub const ROUP_OMP_MEMORY_SPACE_HIGH_BW: u32 = 4;
pub const ROUP_OMP_MEMORY_SPACE_LOW_LAT: u32 = 5;

pub const ROUP_OMP_THREADSET_OMP_POOL: u32 = 1;
pub const ROUP_OMP_THREADSET_OMP_TEAM: u32 = 2;
pub const ROUP_OMP_MEMSCOPE_ALL: u32 = 1;
pub const ROUP_OMP_MEMSCOPE_CGROUP: u32 = 2;
pub const ROUP_OMP_MEMSCOPE_DEVICE: u32 = 3;

pub const ROUP_OMP_PROC_BIND_CLOSE: u32 = 1;
pub const ROUP_OMP_PROC_BIND_SPREAD: u32 = 2;
pub const ROUP_OMP_PROC_BIND_PRIMARY: u32 = 3;
pub const ROUP_OMP_BIND_TEAMS: u32 = 1;
pub const ROUP_OMP_BIND_PARALLEL: u32 = 2;
pub const ROUP_OMP_BIND_THREAD: u32 = 3;
pub const ROUP_OMP_DEVICE_ANCESTOR: u32 = 1;
pub const ROUP_OMP_DEVICE_NUM: u32 = 2;
pub const ROUP_OMP_DEVICE_TYPE_HOST: u32 = 1;
pub const ROUP_OMP_DEVICE_TYPE_NOHOST: u32 = 2;
pub const ROUP_OMP_DEVICE_TYPE_ANY: u32 = 3;
pub const ROUP_OMP_AT_COMPILATION: u32 = 1;
pub const ROUP_OMP_AT_EXECUTION: u32 = 2;
pub const ROUP_OMP_SEVERITY_FATAL: u32 = 1;
pub const ROUP_OMP_SEVERITY_WARNING: u32 = 2;
pub const ROUP_OMP_MEMORY_ORDER_SEQ_CST: u32 = 1;
pub const ROUP_OMP_MEMORY_ORDER_ACQ_REL: u32 = 2;
pub const ROUP_OMP_MEMORY_ORDER_RELEASE: u32 = 3;
pub const ROUP_OMP_MEMORY_ORDER_ACQUIRE: u32 = 4;
pub const ROUP_OMP_MEMORY_ORDER_RELAXED: u32 = 5;
pub const ROUP_OMP_ATOMIC_READ: u32 = 1;
pub const ROUP_OMP_ATOMIC_WRITE: u32 = 2;
pub const ROUP_OMP_ATOMIC_UPDATE: u32 = 3;
pub const ROUP_OMP_EXTENDED_ATOMIC_CAPTURE: u32 = 1;
pub const ROUP_OMP_EXTENDED_ATOMIC_COMPARE: u32 = 2;
pub const ROUP_OMP_EXTENDED_ATOMIC_WEAK: u32 = 3;
pub const ROUP_OMP_ORDER_REPRODUCIBLE: u32 = 1;
pub const ROUP_OMP_ORDER_UNCONSTRAINED: u32 = 2;
pub const ROUP_OMP_ORDER_CONCURRENT: u32 = 1;
pub const ROUP_OMP_GRAINSIZE_STRICT: u32 = 1;
pub const ROUP_OMP_NUM_TASKS_STRICT: u32 = 1;
pub const ROUP_OMP_DEPOBJ_UPDATE_IN: u32 = 1;
pub const ROUP_OMP_DEPOBJ_UPDATE_OUT: u32 = 2;
pub const ROUP_OMP_DEPOBJ_UPDATE_INOUT: u32 = 3;
pub const ROUP_OMP_DEPOBJ_UPDATE_INOUTSET: u32 = 4;
pub const ROUP_OMP_DEPOBJ_UPDATE_MUTEXINOUTSET: u32 = 5;

pub const ROUP_ACC_DEFAULT_NONE: u32 = 1;
pub const ROUP_ACC_DEFAULT_PRESENT: u32 = 2;
pub const ROUP_ACC_COPY: u32 = 1;
pub const ROUP_ACC_COPYIN: u32 = 2;
pub const ROUP_ACC_COPYOUT: u32 = 3;
pub const ROUP_ACC_CREATE: u32 = 1;
pub const ROUP_ACC_DATA_ATTACH: u32 = 1;
pub const ROUP_ACC_DATA_DETACH: u32 = 2;
pub const ROUP_ACC_DATA_USE_DEVICE: u32 = 3;
pub const ROUP_ACC_DATA_LINK: u32 = 4;
pub const ROUP_ACC_DATA_DEVICE_RESIDENT: u32 = 5;
pub const ROUP_ACC_DATA_DEVICE: u32 = 6;
pub const ROUP_ACC_DATA_DELETE: u32 = 7;
pub const ROUP_ACC_DATA_MODIFIER_ALWAYS: u32 = 1;
pub const ROUP_ACC_DATA_MODIFIER_ALWAYS_IN: u32 = 2;
pub const ROUP_ACC_DATA_MODIFIER_ALWAYS_OUT: u32 = 3;
pub const ROUP_ACC_DATA_MODIFIER_CAPTURE: u32 = 4;
pub const ROUP_ACC_DATA_MODIFIER_READONLY: u32 = 5;
pub const ROUP_ACC_DATA_MODIFIER_ZERO: u32 = 6;
pub const ROUP_ACC_WORKER_NUM: u32 = 1;
pub const ROUP_ACC_WORKER_EXPRESSION: u32 = 2;
pub const ROUP_ACC_VECTOR_LENGTH: u32 = 1;
pub const ROUP_ACC_VECTOR_EXPRESSION: u32 = 2;

pub const ROUP_CHARACTER_ENCODING_ORDINARY: u32 = 1;
pub const ROUP_CHARACTER_ENCODING_UTF8: u32 = 2;
pub const ROUP_CHARACTER_ENCODING_UTF16: u32 = 3;
pub const ROUP_CHARACTER_ENCODING_UTF32: u32 = 4;
pub const ROUP_CHARACTER_ENCODING_WIDE: u32 = 5;
pub const ROUP_CHARACTER_ENCODING_FORTRAN: u32 = 6;

pub const ROUP_REQUIRE_REVERSE_OFFLOAD: u32 = 1;
pub const ROUP_REQUIRE_UNIFIED_ADDRESS: u32 = 2;
pub const ROUP_REQUIRE_UNIFIED_SHARED_MEMORY: u32 = 3;
pub const ROUP_REQUIRE_DYNAMIC_ALLOCATORS: u32 = 4;
pub const ROUP_REQUIRE_SELF_MAPS: u32 = 5;
pub const ROUP_REQUIRE_DEVICE_SAFESYNC: u32 = 6;
pub const ROUP_REQUIRE_ATOMIC_DEFAULT_MEM_ORDER: u32 = 7;
pub const ROUP_REQUIRE_EXTENSION: u32 = 8;

pub const ROUP_REDUCTION_MODIFIER_TASK: u32 = 1;
pub const ROUP_REDUCTION_MODIFIER_INSCAN: u32 = 2;
pub const ROUP_REDUCTION_MODIFIER_DEFAULT: u32 = 3;
pub const ROUP_REDUCTION_MODIFIER_ORIGINAL: u32 = 4;

pub const ROUP_SELECTOR_ENTRY_DEVICE: u32 = 1;
pub const ROUP_SELECTOR_ENTRY_TARGET_DEVICE: u32 = 2;
pub const ROUP_SELECTOR_ENTRY_IMPLEMENTATION: u32 = 3;
pub const ROUP_SELECTOR_ENTRY_USER: u32 = 4;
pub const ROUP_SELECTOR_ENTRY_CONSTRUCT: u32 = 5;

pub const ROUP_SELECTOR_DEVICE_NAME_LIST: u32 = 1;
pub const ROUP_SELECTOR_DEVICE_NUM: u32 = 2;
pub const ROUP_SELECTOR_DEVICE_UID: u32 = 3;
pub const ROUP_SELECTOR_DEVICE_EXTENSION: u32 = 4;

pub const ROUP_SELECTOR_IMPLEMENTATION_NAME_LIST: u32 = 1;
pub const ROUP_SELECTOR_IMPLEMENTATION_ATOMIC_DEFAULT_MEM_ORDER: u32 = 2;
pub const ROUP_SELECTOR_IMPLEMENTATION_REQUIREMENT: u32 = 3;
pub const ROUP_SELECTOR_IMPLEMENTATION_REQUIRES: u32 = 4;
pub const ROUP_SELECTOR_IMPLEMENTATION_EXTENSION: u32 = 5;

pub const ROUP_SELECTOR_NAME_LIST_KIND: u32 = 1;
pub const ROUP_SELECTOR_NAME_LIST_ISA: u32 = 2;
pub const ROUP_SELECTOR_NAME_LIST_ARCH: u32 = 3;
pub const ROUP_SELECTOR_NAME_LIST_VENDOR: u32 = 4;
pub const ROUP_SELECTOR_NAME_LIST_EXTENSION: u32 = 5;

pub const ROUP_SELECTOR_EXTENSION_TRAIT: u32 = 1;
pub const ROUP_SELECTOR_EXTENSION_PROPERTY_NAME: u32 = 1;
pub const ROUP_SELECTOR_EXTENSION_PROPERTY_CALL: u32 = 2;
pub const ROUP_SELECTOR_EXTENSION_PROPERTY_CONSTANT_INTEGER: u32 = 3;
pub const ROUP_SELECTOR_REQUIREMENT: u32 = 1;
pub const ROUP_SELECTOR_CONSTRUCT: u32 = 1;

pub const ROUP_SELECTOR_TRAIT_IDENTIFIER: u32 = 1;
pub const ROUP_SELECTOR_TRAIT_STRING_LITERAL: u32 = 2;
pub const ROUP_SELECTOR_TRAIT_PREDEFINED_DEVICE_KIND: u32 = 3;
pub const ROUP_SELECTOR_TRAIT_PREDEFINED_VENDOR: u32 = 4;

pub const ROUP_OMP_DEVICE_KIND_HOST: u32 = 1;
pub const ROUP_OMP_DEVICE_KIND_NOHOST: u32 = 2;
pub const ROUP_OMP_DEVICE_KIND_ANY: u32 = 3;
pub const ROUP_OMP_DEVICE_KIND_CPU: u32 = 4;
pub const ROUP_OMP_DEVICE_KIND_GPU: u32 = 5;
pub const ROUP_OMP_DEVICE_KIND_FPGA: u32 = 6;

pub const ROUP_OMP_VENDOR_AMD: u32 = 1;
pub const ROUP_OMP_VENDOR_ARM: u32 = 2;
pub const ROUP_OMP_VENDOR_BSC: u32 = 3;
pub const ROUP_OMP_VENDOR_CRAY: u32 = 4;
pub const ROUP_OMP_VENDOR_FUJITSU: u32 = 5;
pub const ROUP_OMP_VENDOR_GNU: u32 = 6;
pub const ROUP_OMP_VENDOR_IBM: u32 = 7;
pub const ROUP_OMP_VENDOR_INTEL: u32 = 8;
pub const ROUP_OMP_VENDOR_LLVM: u32 = 9;
pub const ROUP_OMP_VENDOR_NVIDIA: u32 = 10;
pub const ROUP_OMP_VENDOR_PGI: u32 = 11;
pub const ROUP_OMP_VENDOR_TI: u32 = 12;

pub const ROUP_OMP_PARAMETER_ALLOCATE_LIST: u32 = 1;
pub const ROUP_OMP_PARAMETER_THREADPRIVATE_LIST: u32 = 2;
pub const ROUP_OMP_PARAMETER_GROUPPRIVATE_LIST: u32 = 3;
pub const ROUP_OMP_PARAMETER_DECLARE_TARGET_LIST: u32 = 4;
pub const ROUP_OMP_PARAMETER_DECLARE_MAPPER: u32 = 5;
pub const ROUP_OMP_PARAMETER_DECLARE_VARIANT: u32 = 6;
pub const ROUP_OMP_PARAMETER_DEPOBJ: u32 = 7;
pub const ROUP_OMP_PARAMETER_CONSTRUCT: u32 = 8;
pub const ROUP_OMP_PARAMETER_CRITICAL_SECTION: u32 = 9;
pub const ROUP_OMP_PARAMETER_FLUSH_LIST: u32 = 10;
pub const ROUP_OMP_PARAMETER_DECLARE_REDUCTION: u32 = 11;
pub const ROUP_OMP_PARAMETER_DECLARE_SIMD: u32 = 12;
pub const ROUP_OMP_PARAMETER_DECLARE_INDUCTION: u32 = 13;
pub const ROUP_OMP_PARAMETER_OMPX: u32 = 14;

pub const ROUP_OMPX_PAYLOAD_IDENTIFIER: u32 = 1;
pub const ROUP_OMPX_PAYLOAD_INVOCATION: u32 = 2;

pub const ROUP_ACC_PARAMETER_CACHE: u32 = 1;
pub const ROUP_ACC_PARAMETER_WAIT: u32 = 2;
pub const ROUP_ACC_PARAMETER_ROUTINE: u32 = 3;
pub const ROUP_ACC_PARAMETER_END: u32 = 4;

pub const ROUP_OMP_DIRECTIVE_ALLOCATE: u32 = 0;
pub const ROUP_OMP_DIRECTIVE_ALLOCATORS: u32 = 1;
pub const ROUP_OMP_DIRECTIVE_ASSUME: u32 = 2;
pub const ROUP_OMP_DIRECTIVE_ASSUMES: u32 = 3;
pub const ROUP_OMP_DIRECTIVE_ATOMIC: u32 = 4;
pub const ROUP_OMP_DIRECTIVE_BARRIER: u32 = 5;
pub const ROUP_OMP_DIRECTIVE_BEGIN_ASSUMES: u32 = 6;
pub const ROUP_OMP_DIRECTIVE_BEGIN_DECLARE_TARGET: u32 = 7;
pub const ROUP_OMP_DIRECTIVE_BEGIN_DECLARE_VARIANT: u32 = 8;
pub const ROUP_OMP_DIRECTIVE_CANCEL: u32 = 9;
pub const ROUP_OMP_DIRECTIVE_CANCELLATION_POINT: u32 = 10;
pub const ROUP_OMP_DIRECTIVE_CRITICAL: u32 = 11;
pub const ROUP_OMP_DIRECTIVE_DECLARE_INDUCTION: u32 = 12;
pub const ROUP_OMP_DIRECTIVE_DECLARE_MAPPER: u32 = 13;
pub const ROUP_OMP_DIRECTIVE_DECLARE_REDUCTION: u32 = 14;
pub const ROUP_OMP_DIRECTIVE_DECLARE_SIMD: u32 = 15;
pub const ROUP_OMP_DIRECTIVE_DECLARE_TARGET: u32 = 16;
pub const ROUP_OMP_DIRECTIVE_DECLARE_VARIANT: u32 = 17;
pub const ROUP_OMP_DIRECTIVE_DEPOBJ: u32 = 18;
pub const ROUP_OMP_DIRECTIVE_DISPATCH: u32 = 19;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE: u32 = 20;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_DO: u32 = 21;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 22;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_FOR: u32 = 23;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_FOR_SIMD: u32 = 24;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_LOOP: u32 = 25;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_LOOP_SIMD: u32 = 26;
pub const ROUP_OMP_DIRECTIVE_DISTRIBUTE_SIMD: u32 = 27;
pub const ROUP_OMP_DIRECTIVE_DO: u32 = 28;
pub const ROUP_OMP_DIRECTIVE_DO_SIMD: u32 = 29;
pub const ROUP_OMP_DIRECTIVE_END_ASSUME: u32 = 30;
pub const ROUP_OMP_DIRECTIVE_END_ASSUMES: u32 = 31;
pub const ROUP_OMP_DIRECTIVE_END_ALLOCATORS: u32 = 32;
pub const ROUP_OMP_DIRECTIVE_END_DECLARE_TARGET: u32 = 33;
pub const ROUP_OMP_DIRECTIVE_END_DECLARE_VARIANT: u32 = 34;
pub const ROUP_OMP_DIRECTIVE_END_DISPATCH: u32 = 35;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL: u32 = 36;
pub const ROUP_OMP_DIRECTIVE_END_DO: u32 = 37;
pub const ROUP_OMP_DIRECTIVE_END_SIMD: u32 = 38;
pub const ROUP_OMP_DIRECTIVE_END_SECTIONS: u32 = 39;
pub const ROUP_OMP_DIRECTIVE_END_SINGLE: u32 = 40;
pub const ROUP_OMP_DIRECTIVE_END_WORKSHARE: u32 = 41;
pub const ROUP_OMP_DIRECTIVE_END_ORDERED: u32 = 42;
pub const ROUP_OMP_DIRECTIVE_END_LOOP: u32 = 43;
pub const ROUP_OMP_DIRECTIVE_END_DISTRIBUTE: u32 = 44;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS: u32 = 45;
pub const ROUP_OMP_DIRECTIVE_END_TASKLOOP: u32 = 46;
pub const ROUP_OMP_DIRECTIVE_END_TASK: u32 = 47;
pub const ROUP_OMP_DIRECTIVE_END_TASKGROUP: u32 = 48;
pub const ROUP_OMP_DIRECTIVE_END_MASTER: u32 = 49;
pub const ROUP_OMP_DIRECTIVE_END_MASKED: u32 = 50;
pub const ROUP_OMP_DIRECTIVE_END_UNROLL: u32 = 51;
pub const ROUP_OMP_DIRECTIVE_END_CRITICAL: u32 = 52;
pub const ROUP_OMP_DIRECTIVE_END_ATOMIC: u32 = 53;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_DO: u32 = 54;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_SECTIONS: u32 = 55;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_WORKSHARE: u32 = 56;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER: u32 = 57;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_SINGLE: u32 = 58;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER_TASKLOOP: u32 = 59;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER_TASKLOOP_SIMD: u32 = 60;
pub const ROUP_OMP_DIRECTIVE_END_DO_SIMD: u32 = 61;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_DO_SIMD: u32 = 62;
pub const ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_SIMD: u32 = 63;
pub const ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_PARALLEL_DO: u32 = 64;
pub const ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 65;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL: u32 = 66;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_DO: u32 = 67;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_DO_SIMD: u32 = 68;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_LOOP: u32 = 69;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_SIMD: u32 = 70;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS: u32 = 71;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE: u32 = 72;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO: u32 = 73;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 74;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_SIMD: u32 = 75;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_LOOP: u32 = 76;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_WORKDISTRIBUTE: u32 = 77;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE: u32 = 78;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_PARALLEL_DO: u32 = 79;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 80;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_SIMD: u32 = 81;
pub const ROUP_OMP_DIRECTIVE_END_TEAMS_LOOP: u32 = 82;
pub const ROUP_OMP_DIRECTIVE_END_TASKLOOP_SIMD: u32 = 83;
pub const ROUP_OMP_DIRECTIVE_END_MASTER_TASKLOOP: u32 = 84;
pub const ROUP_OMP_DIRECTIVE_END_MASTER_TASKLOOP_SIMD: u32 = 85;
pub const ROUP_OMP_DIRECTIVE_END_MASKED_TASKLOOP: u32 = 86;
pub const ROUP_OMP_DIRECTIVE_END_MASKED_TASKLOOP_SIMD: u32 = 87;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED: u32 = 88;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED_TASKLOOP: u32 = 89;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED_TASKLOOP_SIMD: u32 = 90;
pub const ROUP_OMP_DIRECTIVE_END_PARALLEL_LOOP: u32 = 91;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_LOOP: u32 = 92;
pub const ROUP_OMP_DIRECTIVE_END_TILE: u32 = 93;
pub const ROUP_OMP_DIRECTIVE_ERROR: u32 = 94;
pub const ROUP_OMP_DIRECTIVE_FLUSH: u32 = 95;
pub const ROUP_OMP_DIRECTIVE_FUSE: u32 = 96;
pub const ROUP_OMP_DIRECTIVE_GROUPPRIVATE: u32 = 97;
pub const ROUP_OMP_DIRECTIVE_FOR: u32 = 98;
pub const ROUP_OMP_DIRECTIVE_FOR_SIMD: u32 = 99;
pub const ROUP_OMP_DIRECTIVE_INTERCHANGE: u32 = 100;
pub const ROUP_OMP_DIRECTIVE_INTEROP: u32 = 101;
pub const ROUP_OMP_DIRECTIVE_LOOP: u32 = 102;
pub const ROUP_OMP_DIRECTIVE_REVERSE: u32 = 103;
pub const ROUP_OMP_DIRECTIVE_MASKED: u32 = 104;
pub const ROUP_OMP_DIRECTIVE_MASKED_TASKLOOP: u32 = 105;
pub const ROUP_OMP_DIRECTIVE_MASKED_TASKLOOP_SIMD: u32 = 106;
pub const ROUP_OMP_DIRECTIVE_MASTER: u32 = 107;
pub const ROUP_OMP_DIRECTIVE_MASTER_TASKLOOP: u32 = 108;
pub const ROUP_OMP_DIRECTIVE_MASTER_TASKLOOP_SIMD: u32 = 109;
pub const ROUP_OMP_DIRECTIVE_METADIRECTIVE: u32 = 110;
pub const ROUP_OMP_DIRECTIVE_BEGIN_METADIRECTIVE: u32 = 111;
pub const ROUP_OMP_DIRECTIVE_END_METADIRECTIVE: u32 = 112;
pub const ROUP_OMP_DIRECTIVE_NOTHING: u32 = 113;
pub const ROUP_OMP_DIRECTIVE_ORDERED: u32 = 114;
pub const ROUP_OMP_DIRECTIVE_PARALLEL: u32 = 115;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_DO: u32 = 116;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_DO_SIMD: u32 = 117;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_FOR: u32 = 118;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_FOR_SIMD: u32 = 119;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_LOOP: u32 = 120;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_LOOP_SIMD: u32 = 121;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASKED: u32 = 122;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASKED_TASKLOOP: u32 = 123;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASKED_TASKLOOP_SIMD: u32 = 124;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASTER: u32 = 125;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASTER_TASKLOOP: u32 = 126;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_MASTER_TASKLOOP_SIMD: u32 = 127;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_SECTIONS: u32 = 128;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_SINGLE: u32 = 129;
pub const ROUP_OMP_DIRECTIVE_PARALLEL_WORKSHARE: u32 = 130;
pub const ROUP_OMP_DIRECTIVE_REQUIRES: u32 = 131;
pub const ROUP_OMP_DIRECTIVE_SCOPE: u32 = 132;
pub const ROUP_OMP_DIRECTIVE_END_SCOPE: u32 = 133;
pub const ROUP_OMP_DIRECTIVE_SCAN: u32 = 134;
pub const ROUP_OMP_DIRECTIVE_SECTION: u32 = 135;
pub const ROUP_OMP_DIRECTIVE_SECTIONS: u32 = 136;
pub const ROUP_OMP_DIRECTIVE_SIMD: u32 = 137;
pub const ROUP_OMP_DIRECTIVE_SINGLE: u32 = 138;
pub const ROUP_OMP_DIRECTIVE_SPLIT: u32 = 139;
pub const ROUP_OMP_DIRECTIVE_STRIPE: u32 = 140;
pub const ROUP_OMP_DIRECTIVE_TARGET: u32 = 141;
pub const ROUP_OMP_DIRECTIVE_TARGET_DATA: u32 = 142;
pub const ROUP_OMP_DIRECTIVE_TARGET_ENTER_DATA: u32 = 143;
pub const ROUP_OMP_DIRECTIVE_TARGET_EXIT_DATA: u32 = 144;
pub const ROUP_OMP_DIRECTIVE_END_TARGET: u32 = 145;
pub const ROUP_OMP_DIRECTIVE_END_TARGET_DATA: u32 = 146;
pub const ROUP_OMP_DIRECTIVE_TARGET_LOOP: u32 = 147;
pub const ROUP_OMP_DIRECTIVE_TARGET_LOOP_SIMD: u32 = 148;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL: u32 = 149;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_DO: u32 = 150;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_DO_SIMD: u32 = 151;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_FOR: u32 = 152;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_FOR_SIMD: u32 = 153;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_LOOP: u32 = 154;
pub const ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_LOOP_SIMD: u32 = 155;
pub const ROUP_OMP_DIRECTIVE_TARGET_SIMD: u32 = 156;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS: u32 = 157;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE: u32 = 158;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO: u32 = 159;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 160;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR: u32 = 161;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD: u32 = 162;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP: u32 = 163;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD: u32 = 164;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_SIMD: u32 = 165;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_LOOP: u32 = 166;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_LOOP_SIMD: u32 = 167;
pub const ROUP_OMP_DIRECTIVE_TARGET_TEAMS_WORKDISTRIBUTE: u32 = 168;
pub const ROUP_OMP_DIRECTIVE_TARGET_UPDATE: u32 = 169;
pub const ROUP_OMP_DIRECTIVE_TASK: u32 = 170;
pub const ROUP_OMP_DIRECTIVE_TASK_ITERATION: u32 = 171;
pub const ROUP_OMP_DIRECTIVE_TASKGROUP: u32 = 172;
pub const ROUP_OMP_DIRECTIVE_TASKGRAPH: u32 = 173;
pub const ROUP_OMP_DIRECTIVE_TASKLOOP: u32 = 174;
pub const ROUP_OMP_DIRECTIVE_TASKLOOP_SIMD: u32 = 175;
pub const ROUP_OMP_DIRECTIVE_TASKWAIT: u32 = 176;
pub const ROUP_OMP_DIRECTIVE_TASKYIELD: u32 = 177;
pub const ROUP_OMP_DIRECTIVE_TEAMS: u32 = 178;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE: u32 = 179;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_DO: u32 = 180;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD: u32 = 181;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_FOR: u32 = 182;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD: u32 = 183;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_LOOP: u32 = 184;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD: u32 = 185;
pub const ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_SIMD: u32 = 186;
pub const ROUP_OMP_DIRECTIVE_TEAMS_LOOP: u32 = 187;
pub const ROUP_OMP_DIRECTIVE_TEAMS_LOOP_SIMD: u32 = 188;
pub const ROUP_OMP_DIRECTIVE_THREADPRIVATE: u32 = 189;
pub const ROUP_OMP_DIRECTIVE_TILE: u32 = 190;
pub const ROUP_OMP_DIRECTIVE_UNROLL: u32 = 191;
pub const ROUP_OMP_DIRECTIVE_WORKDISTRIBUTE: u32 = 192;
pub const ROUP_OMP_DIRECTIVE_WORKSHARE: u32 = 193;
pub const ROUP_OMP_DIRECTIVE_END_SECTION: u32 = 194;
pub const ROUP_OMP_DIRECTIVE_OMPX: u32 = 195;

pub const ROUP_OMP_CLAUSE_ABSENT: u32 = 0;
pub const ROUP_OMP_CLAUSE_ACQ_REL: u32 = 1;
pub const ROUP_OMP_CLAUSE_ACQUIRE: u32 = 2;
pub const ROUP_OMP_CLAUSE_ADJUST_ARGS: u32 = 3;
pub const ROUP_OMP_CLAUSE_AFFINITY: u32 = 4;
pub const ROUP_OMP_CLAUSE_ALIGN: u32 = 5;
pub const ROUP_OMP_CLAUSE_ALIGNED: u32 = 6;
pub const ROUP_OMP_CLAUSE_ALLOCATE: u32 = 7;
pub const ROUP_OMP_CLAUSE_ALLOCATOR: u32 = 8;
pub const ROUP_OMP_CLAUSE_APPEND_ARGS: u32 = 9;
pub const ROUP_OMP_CLAUSE_APPLY: u32 = 10;
pub const ROUP_OMP_CLAUSE_AT: u32 = 11;
pub const ROUP_OMP_CLAUSE_ATOMIC_DEFAULT_MEM_ORDER: u32 = 12;
pub const ROUP_OMP_CLAUSE_BIND: u32 = 13;
pub const ROUP_OMP_CLAUSE_CAPTURE: u32 = 14;
pub const ROUP_OMP_CLAUSE_COLLAPSE: u32 = 15;
pub const ROUP_OMP_CLAUSE_COLLECTOR: u32 = 16;
pub const ROUP_OMP_CLAUSE_COMBINER: u32 = 17;
pub const ROUP_OMP_CLAUSE_COMPARE: u32 = 18;
pub const ROUP_OMP_CLAUSE_CONTAINS: u32 = 19;
pub const ROUP_OMP_CLAUSE_COPY_IN: u32 = 20;
pub const ROUP_OMP_CLAUSE_COPYPRIVATE: u32 = 21;
pub const ROUP_OMP_CLAUSE_PARALLEL: u32 = 22;
pub const ROUP_OMP_CLAUSE_SECTIONS: u32 = 23;
pub const ROUP_OMP_CLAUSE_FOR: u32 = 24;
pub const ROUP_OMP_CLAUSE_DO: u32 = 25;
pub const ROUP_OMP_CLAUSE_TASKGROUP: u32 = 26;
pub const ROUP_OMP_CLAUSE_COUNTS: u32 = 27;
pub const ROUP_OMP_CLAUSE_DEFAULT: u32 = 28;
pub const ROUP_OMP_CLAUSE_DEFAULTMAP: u32 = 29;
pub const ROUP_OMP_CLAUSE_DEPEND: u32 = 30;
pub const ROUP_OMP_CLAUSE_DEPOBJ_UPDATE: u32 = 31;
pub const ROUP_OMP_CLAUSE_DESTROY: u32 = 32;
pub const ROUP_OMP_CLAUSE_DETACH: u32 = 33;
pub const ROUP_OMP_CLAUSE_DEVICE: u32 = 34;
pub const ROUP_OMP_CLAUSE_DEVICE_SAFESYNC: u32 = 35;
pub const ROUP_OMP_CLAUSE_DEVICE_TYPE: u32 = 36;
pub const ROUP_OMP_CLAUSE_DIST_SCHEDULE: u32 = 37;
pub const ROUP_OMP_CLAUSE_DOACROSS: u32 = 38;
pub const ROUP_OMP_CLAUSE_DYNAMIC_ALLOCATORS: u32 = 39;
pub const ROUP_OMP_CLAUSE_EXT_IMPLEMENTATION_DEFINED_REQUIREMENT: u32 = 40;
pub const ROUP_OMP_CLAUSE_ENTER: u32 = 41;
pub const ROUP_OMP_CLAUSE_EXCLUSIVE: u32 = 42;
pub const ROUP_OMP_CLAUSE_FAIL: u32 = 43;
pub const ROUP_OMP_CLAUSE_FINAL: u32 = 44;
pub const ROUP_OMP_CLAUSE_FILTER: u32 = 45;
pub const ROUP_OMP_CLAUSE_FIRSTPRIVATE: u32 = 46;
pub const ROUP_OMP_CLAUSE_FROM: u32 = 47;
pub const ROUP_OMP_CLAUSE_FULL: u32 = 48;
pub const ROUP_OMP_CLAUSE_GRAINSIZE: u32 = 49;
pub const ROUP_OMP_CLAUSE_GRAPH_ID: u32 = 50;
pub const ROUP_OMP_CLAUSE_GRAPH_RESET: u32 = 51;
pub const ROUP_OMP_CLAUSE_HAS_DEVICE_ADDR: u32 = 52;
pub const ROUP_OMP_CLAUSE_HINT: u32 = 53;
pub const ROUP_OMP_CLAUSE_HOLDS: u32 = 54;
pub const ROUP_OMP_CLAUSE_IF: u32 = 55;
pub const ROUP_OMP_CLAUSE_IN_REDUCTION: u32 = 56;
pub const ROUP_OMP_CLAUSE_INDUCTION: u32 = 57;
pub const ROUP_OMP_CLAUSE_INDUCTOR: u32 = 58;
pub const ROUP_OMP_CLAUSE_INBRANCH: u32 = 59;
pub const ROUP_OMP_CLAUSE_INCLUSIVE: u32 = 60;
pub const ROUP_OMP_CLAUSE_INIT: u32 = 61;
pub const ROUP_OMP_CLAUSE_INIT_COMPLETE: u32 = 62;
pub const ROUP_OMP_CLAUSE_INITIALIZER: u32 = 63;
pub const ROUP_OMP_CLAUSE_INDIRECT: u32 = 64;
pub const ROUP_OMP_CLAUSE_IS_DEVICE_PTR: u32 = 65;
pub const ROUP_OMP_CLAUSE_LASTPRIVATE: u32 = 66;
pub const ROUP_OMP_CLAUSE_LINEAR: u32 = 67;
pub const ROUP_OMP_CLAUSE_LINK: u32 = 68;
pub const ROUP_OMP_CLAUSE_LOCAL: u32 = 69;
pub const ROUP_OMP_CLAUSE_LOOPRANGE: u32 = 70;
pub const ROUP_OMP_CLAUSE_MAP: u32 = 71;
pub const ROUP_OMP_CLAUSE_MATCH: u32 = 72;
pub const ROUP_OMP_CLAUSE_MESSAGE: u32 = 73;
pub const ROUP_OMP_CLAUSE_MEMSCOPE: u32 = 74;
pub const ROUP_OMP_CLAUSE_MERGEABLE: u32 = 75;
pub const ROUP_OMP_CLAUSE_NOCONTEXT: u32 = 76;
pub const ROUP_OMP_CLAUSE_NOGROUP: u32 = 77;
pub const ROUP_OMP_CLAUSE_NO_OPENMP: u32 = 78;
pub const ROUP_OMP_CLAUSE_NO_OPENMP_CONSTRUCTS: u32 = 79;
pub const ROUP_OMP_CLAUSE_NO_OPENMP_ROUTINES: u32 = 80;
pub const ROUP_OMP_CLAUSE_NO_PARALLELISM: u32 = 81;
pub const ROUP_OMP_CLAUSE_NONTEMPORAL: u32 = 82;
pub const ROUP_OMP_CLAUSE_NOTINBRANCH: u32 = 83;
pub const ROUP_OMP_CLAUSE_NOVARIANTS: u32 = 84;
pub const ROUP_OMP_CLAUSE_INTEROP: u32 = 85;
pub const ROUP_OMP_CLAUSE_NOWAIT: u32 = 86;
pub const ROUP_OMP_CLAUSE_NUM_TASKS: u32 = 87;
pub const ROUP_OMP_CLAUSE_NUM_TEAMS: u32 = 88;
pub const ROUP_OMP_CLAUSE_NUM_THREADS: u32 = 89;
pub const ROUP_OMP_CLAUSE_ORDER: u32 = 90;
pub const ROUP_OMP_CLAUSE_ORDERED: u32 = 91;
pub const ROUP_OMP_CLAUSE_OTHERWISE: u32 = 92;
pub const ROUP_OMP_CLAUSE_PARTIAL: u32 = 93;
pub const ROUP_OMP_CLAUSE_PERMUTATION: u32 = 94;
pub const ROUP_OMP_CLAUSE_PRIORITY: u32 = 95;
pub const ROUP_OMP_CLAUSE_PRIVATE: u32 = 96;
pub const ROUP_OMP_CLAUSE_PROC_BIND: u32 = 97;
pub const ROUP_OMP_CLAUSE_READ: u32 = 98;
pub const ROUP_OMP_CLAUSE_REDUCTION: u32 = 99;
pub const ROUP_OMP_CLAUSE_RELEASE: u32 = 100;
pub const ROUP_OMP_CLAUSE_RELAXED: u32 = 101;
pub const ROUP_OMP_CLAUSE_REPLAYABLE: u32 = 102;
pub const ROUP_OMP_CLAUSE_REVERSE_OFFLOAD: u32 = 103;
pub const ROUP_OMP_CLAUSE_SAFELEN: u32 = 104;
pub const ROUP_OMP_CLAUSE_SAFESYNC: u32 = 105;
pub const ROUP_OMP_CLAUSE_SCHEDULE: u32 = 106;
pub const ROUP_OMP_CLAUSE_SELF_MAPS: u32 = 107;
pub const ROUP_OMP_CLAUSE_SEQ_CST: u32 = 108;
pub const ROUP_OMP_CLAUSE_SEVERITY: u32 = 109;
pub const ROUP_OMP_CLAUSE_SHARED: u32 = 110;
pub const ROUP_OMP_CLAUSE_SIMD: u32 = 111;
pub const ROUP_OMP_CLAUSE_SIMDLEN: u32 = 112;
pub const ROUP_OMP_CLAUSE_SIZES: u32 = 113;
pub const ROUP_OMP_CLAUSE_TASK_REDUCTION: u32 = 114;
pub const ROUP_OMP_CLAUSE_THREAD_LIMIT: u32 = 115;
pub const ROUP_OMP_CLAUSE_THREADS: u32 = 116;
pub const ROUP_OMP_CLAUSE_THREADSET: u32 = 117;
pub const ROUP_OMP_CLAUSE_TO: u32 = 118;
pub const ROUP_OMP_CLAUSE_TRANSPARENT: u32 = 119;
pub const ROUP_OMP_CLAUSE_UNIFIED_ADDRESS: u32 = 120;
pub const ROUP_OMP_CLAUSE_UNIFIED_SHARED_MEMORY: u32 = 121;
pub const ROUP_OMP_CLAUSE_UNIFORM: u32 = 122;
pub const ROUP_OMP_CLAUSE_UNTIED: u32 = 123;
pub const ROUP_OMP_CLAUSE_UPDATE: u32 = 124;
pub const ROUP_OMP_CLAUSE_USE: u32 = 125;
pub const ROUP_OMP_CLAUSE_USE_DEVICE_ADDR: u32 = 126;
pub const ROUP_OMP_CLAUSE_USE_DEVICE_PTR: u32 = 127;
pub const ROUP_OMP_CLAUSE_USES_ALLOCATORS: u32 = 128;
pub const ROUP_OMP_CLAUSE_WEAK: u32 = 129;
pub const ROUP_OMP_CLAUSE_WHEN: u32 = 130;
pub const ROUP_OMP_CLAUSE_WRITE: u32 = 131;

pub const ROUP_ACC_DIRECTIVE_ATOMIC: u32 = 0;
pub const ROUP_ACC_DIRECTIVE_CACHE: u32 = 1;
pub const ROUP_ACC_DIRECTIVE_DATA: u32 = 2;
pub const ROUP_ACC_DIRECTIVE_DECLARE: u32 = 3;
pub const ROUP_ACC_DIRECTIVE_END: u32 = 4;
pub const ROUP_ACC_DIRECTIVE_ENTER_DATA: u32 = 5;
pub const ROUP_ACC_DIRECTIVE_EXIT_DATA: u32 = 6;
pub const ROUP_ACC_DIRECTIVE_HOST_DATA: u32 = 7;
pub const ROUP_ACC_DIRECTIVE_INIT: u32 = 8;
pub const ROUP_ACC_DIRECTIVE_KERNELS: u32 = 9;
pub const ROUP_ACC_DIRECTIVE_KERNELS_LOOP: u32 = 10;
pub const ROUP_ACC_DIRECTIVE_LOOP: u32 = 11;
pub const ROUP_ACC_DIRECTIVE_PARALLEL: u32 = 12;
pub const ROUP_ACC_DIRECTIVE_PARALLEL_LOOP: u32 = 13;
pub const ROUP_ACC_DIRECTIVE_ROUTINE: u32 = 14;
pub const ROUP_ACC_DIRECTIVE_SERIAL: u32 = 15;
pub const ROUP_ACC_DIRECTIVE_SERIAL_LOOP: u32 = 16;
pub const ROUP_ACC_DIRECTIVE_SET: u32 = 17;
pub const ROUP_ACC_DIRECTIVE_SHUTDOWN: u32 = 18;
pub const ROUP_ACC_DIRECTIVE_UPDATE: u32 = 19;
pub const ROUP_ACC_DIRECTIVE_WAIT: u32 = 20;

pub const ROUP_ACC_CLAUSE_ASYNC: u32 = 0;
pub const ROUP_ACC_CLAUSE_ATTACH: u32 = 1;
pub const ROUP_ACC_CLAUSE_AUTO: u32 = 2;
pub const ROUP_ACC_CLAUSE_BIND: u32 = 3;
pub const ROUP_ACC_CLAUSE_CAPTURE: u32 = 4;
pub const ROUP_ACC_CLAUSE_COLLAPSE: u32 = 5;
pub const ROUP_ACC_CLAUSE_COPY: u32 = 6;
pub const ROUP_ACC_CLAUSE_COPY_IN: u32 = 7;
pub const ROUP_ACC_CLAUSE_COPY_OUT: u32 = 8;
pub const ROUP_ACC_CLAUSE_CREATE: u32 = 9;
pub const ROUP_ACC_CLAUSE_DEFAULT: u32 = 10;
pub const ROUP_ACC_CLAUSE_DEFAULT_ASYNC: u32 = 11;
pub const ROUP_ACC_CLAUSE_DELETE: u32 = 12;
pub const ROUP_ACC_CLAUSE_DETACH: u32 = 13;
pub const ROUP_ACC_CLAUSE_DEVICE: u32 = 14;
pub const ROUP_ACC_CLAUSE_DEVICE_NUM: u32 = 15;
pub const ROUP_ACC_CLAUSE_DEVICE_RESIDENT: u32 = 16;
pub const ROUP_ACC_CLAUSE_DEVICE_TYPE: u32 = 17;
pub const ROUP_ACC_CLAUSE_DEVICE_PTR: u32 = 18;
pub const ROUP_ACC_CLAUSE_FINALIZE: u32 = 19;
pub const ROUP_ACC_CLAUSE_FIRSTPRIVATE: u32 = 20;
pub const ROUP_ACC_CLAUSE_GANG: u32 = 21;
pub const ROUP_ACC_CLAUSE_IF: u32 = 22;
pub const ROUP_ACC_CLAUSE_IF_PRESENT: u32 = 23;
pub const ROUP_ACC_CLAUSE_INDEPENDENT: u32 = 24;
pub const ROUP_ACC_CLAUSE_INDIRECT: u32 = 25;
pub const ROUP_ACC_CLAUSE_LINK: u32 = 26;
pub const ROUP_ACC_CLAUSE_NO_CREATE: u32 = 27;
pub const ROUP_ACC_CLAUSE_NO_HOST: u32 = 28;
pub const ROUP_ACC_CLAUSE_NUM_GANGS: u32 = 29;
pub const ROUP_ACC_CLAUSE_NUM_WORKERS: u32 = 30;
pub const ROUP_ACC_CLAUSE_PRESENT: u32 = 31;
pub const ROUP_ACC_CLAUSE_PRIVATE: u32 = 32;
pub const ROUP_ACC_CLAUSE_REDUCTION: u32 = 33;
pub const ROUP_ACC_CLAUSE_READ: u32 = 34;
pub const ROUP_ACC_CLAUSE_SELF_CLAUSE: u32 = 35;
pub const ROUP_ACC_CLAUSE_SEQ: u32 = 36;
pub const ROUP_ACC_CLAUSE_TILE: u32 = 37;
pub const ROUP_ACC_CLAUSE_UPDATE: u32 = 38;
pub const ROUP_ACC_CLAUSE_USE_DEVICE: u32 = 39;
pub const ROUP_ACC_CLAUSE_VECTOR: u32 = 40;
pub const ROUP_ACC_CLAUSE_VECTOR_LENGTH: u32 = 41;
pub const ROUP_ACC_CLAUSE_WAIT: u32 = 42;
pub const ROUP_ACC_CLAUSE_WORKER: u32 = 43;
pub const ROUP_ACC_CLAUSE_WRITE: u32 = 44;

/// Numeric status returned by every fallible C ABI operation.
///
/// This is a transparent integer rather than a Rust enum, so an unknown value
/// received from foreign code can never create an invalid Rust enum.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoupStatus(pub u32);

impl RoupStatus {
    pub const OK: Self = Self(0);
    pub const INVALID_ARGUMENT: Self = Self(1);
    pub const INVALID_UTF8: Self = Self(2);
    pub const BUFFER_TOO_SMALL: Self = Self(3);
    pub const INVALID_HANDLE: Self = Self(4);
    pub const STALE_HANDLE: Self = Self(5);
    pub const PARSE_ERROR: Self = Self(6);
    pub const INTERNAL_ERROR: Self = Self(7);

    #[must_use]
    pub const fn is_ok(self) -> bool {
        self.0 == Self::OK.0
    }
}

macro_rules! define_handle {
    ($name:ident) => {
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub struct $name {
            pub generation: u64,
            pub index: u64,
        }

        impl $name {
            pub const INACTIVE: Self = Self {
                generation: 0,
                index: 0,
            };

            pub(crate) const fn active(index: u32, generation: u64) -> Self {
                Self {
                    generation,
                    index: index as u64,
                }
            }

            #[must_use]
            pub const fn is_active(self) -> bool {
                self.generation != 0
            }
        }
    };
}

define_handle!(RoupParserHandle);
define_handle!(RoupDirectiveHandle);
define_handle!(RoupErrorHandle);
define_handle!(RoupNodeHandle);

/// Raw, strictly validated parser configuration.
///
/// `version` contains the decimal specification encoding (`520` means OpenMP
/// 5.2 and `340` means OpenACC 3.4) when `version_policy` is exact. It must be
/// zero for the union-version policy. `host_standard` similarly uses `23` for
/// C23/C++23 and `2023` for Fortran 2023.
#[repr(C)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoupParserOptions {
    pub abi_version: u32,
    pub struct_size: u32,
    pub dialect: u32,
    pub version_policy: u32,
    pub version: u32,
    pub host_language: u32,
    pub host_standard: u32,
    pub source_form: u32,
    pub flags: u32,
    pub reserved: [u32; 3],
}

/// Half-open source span. Byte offsets are zero based; lines and columns are
/// one based for parser diagnostics and zero when no source exists.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupSpan {
    pub start_byte: usize,
    pub end_byte: usize,
    pub start_line: usize,
    pub start_column: usize,
    pub end_line: usize,
    pub end_column: usize,
}

/// Dialect-specific clause identity.
///
/// `ordinal` is the zero-based position in the dialect's typed clause schema.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupClauseKind {
    pub dialect: u32,
    pub ordinal: u32,
}

/// Dialect-specific directive identity.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupDirectiveKind {
    pub dialect: u32,
    pub ordinal: u32,
}

/// Dialect-specific directive parameter variant.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupParameterKind {
    pub dialect: u32,
    pub variant: u32,
}

/// Stable identity of a recursively queryable semantic record.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupNodeKind {
    pub family: u32,
    pub variant: u32,
}

/// Metadata for one typed field in a clause payload.
///
/// String-list elements are queried independently, so callers never need to
/// split a complete clause serialization to recover semantic list boundaries.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RoupFieldInfo {
    pub id: u32,
    pub value_kind: u32,
    pub count: usize,
}

/// Result header shared by all fallible ABI operations.
#[repr(C)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoupCallResult {
    pub status: RoupStatus,
    pub reserved: u32,
    pub error: RoupErrorHandle,
}

impl RoupCallResult {
    #[must_use]
    pub const fn success() -> Self {
        Self {
            status: RoupStatus::OK,
            reserved: 0,
            error: RoupErrorHandle::INACTIVE,
        }
    }

    #[must_use]
    pub(crate) const fn failure(status: RoupStatus, error: RoupErrorHandle) -> Self {
        Self {
            status,
            reserved: 0,
            error,
        }
    }
}

/// Result of a fallible ABI operation returning a `u32` value.
#[repr(C)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RoupU32Result {
    pub result: RoupCallResult,
    pub value: u32,
    pub reserved: u32,
}

impl RoupU32Result {
    pub(crate) const fn success(value: u32) -> Self {
        Self {
            result: RoupCallResult::success(),
            value,
            reserved: 0,
        }
    }

    pub(crate) const fn failure(status: RoupStatus, error: RoupErrorHandle) -> Self {
        Self {
            result: RoupCallResult::failure(status, error),
            value: 0,
            reserved: 0,
        }
    }
}

macro_rules! define_scalar_result {
    ($name:ident, $value:ty, $zero:expr) => {
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub struct $name {
            pub result: RoupCallResult,
            pub value: $value,
        }

        impl $name {
            pub(crate) const fn success(value: $value) -> Self {
                Self {
                    result: RoupCallResult::success(),
                    value,
                }
            }

            pub(crate) const fn failure(status: RoupStatus, error: RoupErrorHandle) -> Self {
                Self {
                    result: RoupCallResult::failure(status, error),
                    value: $zero,
                }
            }
        }
    };
}

define_scalar_result!(RoupU64Result, u64, 0);
define_scalar_result!(RoupSizeResult, usize, 0);
define_scalar_result!(
    RoupSpanResult,
    RoupSpan,
    RoupSpan {
        start_byte: 0,
        end_byte: 0,
        start_line: 0,
        start_column: 0,
        end_line: 0,
        end_column: 0,
    }
);
define_scalar_result!(
    RoupClauseKindResult,
    RoupClauseKind,
    RoupClauseKind {
        dialect: 0,
        ordinal: 0,
    }
);
define_scalar_result!(
    RoupDirectiveKindResult,
    RoupDirectiveKind,
    RoupDirectiveKind {
        dialect: 0,
        ordinal: 0,
    }
);
define_scalar_result!(
    RoupParameterKindResult,
    RoupParameterKind,
    RoupParameterKind {
        dialect: 0,
        variant: 0,
    }
);
define_scalar_result!(
    RoupNodeKindResult,
    RoupNodeKind,
    RoupNodeKind {
        family: 0,
        variant: 0,
    }
);
define_scalar_result!(
    RoupFieldInfoResult,
    RoupFieldInfo,
    RoupFieldInfo {
        id: 0,
        value_kind: 0,
        count: 0,
    }
);

macro_rules! define_handle_result {
    ($name:ident, $handle:ty) => {
        #[repr(C)]
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub struct $name {
            pub result: RoupCallResult,
            pub value: $handle,
        }

        impl $name {
            pub(crate) const fn success(value: $handle) -> Self {
                Self {
                    result: RoupCallResult::success(),
                    value,
                }
            }

            pub(crate) const fn failure(status: RoupStatus, error: RoupErrorHandle) -> Self {
                Self {
                    result: RoupCallResult::failure(status, error),
                    value: <$handle>::INACTIVE,
                }
            }
        }
    };
}

define_handle_result!(RoupParserResult, RoupParserHandle);
define_handle_result!(RoupDirectiveResult, RoupDirectiveHandle);
define_handle_result!(RoupNodeResult, RoupNodeHandle);

#[cfg(test)]
mod tests {
    use super::*;
    use core::mem::{align_of, offset_of, size_of};

    #[test]
    fn abi_layouts_match_the_public_c_header() {
        assert_eq!(size_of::<RoupStatus>(), size_of::<u32>());
        assert_eq!(size_of::<RoupParserHandle>(), 2 * size_of::<u64>());
        assert_eq!(size_of::<RoupDirectiveHandle>(), 2 * size_of::<u64>());
        assert_eq!(size_of::<RoupErrorHandle>(), 2 * size_of::<u64>());
        assert_eq!(size_of::<RoupNodeHandle>(), 2 * size_of::<u64>());
        assert_eq!(align_of::<RoupParserHandle>(), align_of::<u64>());
        assert_eq!(offset_of!(RoupParserHandle, generation), 0);
        assert_eq!(offset_of!(RoupParserHandle, index), 8);
        assert_eq!(size_of::<RoupParserOptions>(), 48);
        assert_eq!(size_of::<RoupSpan>(), 6 * size_of::<usize>());
        assert_eq!(size_of::<RoupClauseKind>(), 8);
        assert_eq!(size_of::<RoupDirectiveKind>(), 8);
        assert_eq!(size_of::<RoupParameterKind>(), 8);
        assert_eq!(size_of::<RoupNodeKind>(), 8);
        assert_eq!(size_of::<RoupFieldInfo>(), 8 + size_of::<usize>());
        assert_eq!(size_of::<RoupCallResult>(), 24);
        assert_eq!(offset_of!(RoupCallResult, status), 0);
        assert_eq!(offset_of!(RoupCallResult, reserved), 4);
        assert_eq!(offset_of!(RoupCallResult, error), 8);
        assert_eq!(size_of::<RoupU32Result>(), 32);
        assert_eq!(offset_of!(RoupU32Result, value), 24);
        assert_eq!(offset_of!(RoupU32Result, reserved), 28);
        assert_eq!(size_of::<RoupU64Result>(), 32);
        assert_eq!(offset_of!(RoupU64Result, value), 24);
        assert_eq!(ROUP_FIELD_VALUE_U32, 2);
        assert_eq!(ROUP_FIELD_VALUE_U32_LIST, 5);
    }

    #[test]
    fn successful_result_has_no_active_error() {
        let result = RoupU32Result::success(ROUP_ABI_VERSION);
        assert!(result.result.status.is_ok());
        assert!(!result.result.error.is_active());
        assert_eq!(result.value, ROUP_ABI_VERSION);
        assert_eq!(ROUP_ABI_VERSION, 3);
    }

    #[test]
    fn public_header_matches_the_exported_surface() {
        const HEADER: &str = include_str!("../include/roup.h");
        const EXPORTS: &[&str] = &[
            "roup_abi_version",
            "roup_clause_field_count",
            "roup_clause_field_info",
            "roup_clause_field_name_copy",
            "roup_clause_field_name_length",
            "roup_clause_field_node",
            "roup_clause_field_string_copy",
            "roup_clause_field_string_length",
            "roup_clause_field_u32",
            "roup_clause_field_u64",
            "roup_clause_field_bool",
            "roup_clause_kind",
            "roup_clause_name_copy",
            "roup_clause_name_length",
            "roup_clause_span",
            "roup_directive_clause_count",
            "roup_directive_compatible_versions",
            "roup_directive_dialect",
            "roup_directive_has_parameter",
            "roup_directive_kind",
            "roup_directive_source_alias",
            "roup_directive_name_copy",
            "roup_directive_name_length",
            "roup_directive_parameter_field_count",
            "roup_directive_parameter_field_info",
            "roup_directive_parameter_field_name_copy",
            "roup_directive_parameter_field_name_length",
            "roup_directive_parameter_field_node",
            "roup_directive_parameter_field_string_copy",
            "roup_directive_parameter_field_string_length",
            "roup_directive_parameter_field_u32",
            "roup_directive_parameter_field_u64",
            "roup_directive_parameter_field_bool",
            "roup_directive_parameter_kind",
            "roup_directive_release",
            "roup_directive_span",
            "roup_error_code",
            "roup_error_message_copy",
            "roup_error_message_length",
            "roup_error_release",
            "roup_error_span",
            "roup_node_field_count",
            "roup_node_field_info",
            "roup_node_field_name_copy",
            "roup_node_field_name_length",
            "roup_node_field_node",
            "roup_node_field_string_copy",
            "roup_node_field_string_length",
            "roup_node_field_u32",
            "roup_node_field_u64",
            "roup_node_field_bool",
            "roup_node_kind",
            "roup_node_release",
            "roup_parse",
            "roup_parser_create",
            "roup_parser_release",
        ];

        for export in EXPORTS {
            assert!(
                HEADER.contains(&format!("{export}(")),
                "public header is missing {export}"
            );
        }
        assert!(!HEADER.contains("roup_clause_payload_"));
    }

    #[test]
    fn generated_header_matches_the_checked_public_header() {
        let generated = std::fs::read_to_string(env!("ROUP_CAPI_HEADER"))
            .expect("build script must copy the header into OUT_DIR");
        assert_eq!(generated, include_str!("../include/roup.h"));
    }
}
