/*
 * ROUP C API Constants (Auto-generated)
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by build.rs from src/c_api.rs
 *
 * Single source of truth: src/c_api.rs
 * - directive_name_to_kind() for directives
 * - convert_clause() for clauses
 *
 * Copyright (c) 2025 ROUP Project
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ROUP_CONSTANTS_H
#define ROUP_CONSTANTS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Synchronization Check
// ============================================================================
// Auto-generated checksum: FNV-1a hash of OpenMP (34 directives + 89 clauses) + OpenACC (18 directives + 45 clauses) = 0x0D580BE641E02987
// If this doesn't match c_api.rs, rebuild with `cargo clean && cargo build`
#define ROUP_CONSTANTS_CHECKSUM 0x0D580BE641E02987

// ============================================================================
// Language Format Constants
// ============================================================================
// Language format for roup_parse_with_language() and acc_parse_with_language()
#define ROUP_LANG_C                         0  // C/C++ (#pragma omp/#pragma acc)
#define ROUP_LANG_FORTRAN_FREE              1  // Fortran free-form (!$OMP/!$ACC)
#define ROUP_LANG_FORTRAN_FIXED             2  // Fortran fixed-form (!$OMP/!$ACC or C$OMP/C$ACC)

// ============================================================================
// OpenMP Directive Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:directive_name_to_kind()

#define ROUP_DIRECTIVE_PARALLEL             0
#define ROUP_DIRECTIVE_FOR                  1
#define ROUP_DIRECTIVE_DO                   2
#define ROUP_DIRECTIVE_SIMD                 3
#define ROUP_DIRECTIVE_DISTRIBUTE           9
#define ROUP_DIRECTIVE_LOOP                 15
#define ROUP_DIRECTIVE_SCAN                 16
#define ROUP_DIRECTIVE_SECTIONS             17
#define ROUP_DIRECTIVE_SECTION              18
#define ROUP_DIRECTIVE_SINGLE               19
#define ROUP_DIRECTIVE_WORKSHARE            20
#define ROUP_DIRECTIVE_CANCEL               21
#define ROUP_DIRECTIVE_ALLOCATE             23
#define ROUP_DIRECTIVE_THREADPRIVATE        24
#define ROUP_DIRECTIVE_TEAMS                37
#define ROUP_DIRECTIVE_METADIRECTIVE        38
#define ROUP_DIRECTIVE_TASK                 40
#define ROUP_DIRECTIVE_TASKLOOP             41
#define ROUP_DIRECTIVE_TASKYIELD            43
#define ROUP_DIRECTIVE_REQUIRES             44
#define ROUP_DIRECTIVE_TARGET               49
#define ROUP_DIRECTIVE_MASTER               52
#define ROUP_DIRECTIVE_END                  53
#define ROUP_DIRECTIVE_BARRIER              54
#define ROUP_DIRECTIVE_TASKWAIT             55
#define ROUP_DIRECTIVE_UNROLL               56
#define ROUP_DIRECTIVE_TILE                 57
#define ROUP_DIRECTIVE_TASKGROUP            58
#define ROUP_DIRECTIVE_FLUSH                59
#define ROUP_DIRECTIVE_ATOMIC               60
#define ROUP_DIRECTIVE_CRITICAL             61
#define ROUP_DIRECTIVE_DEPOBJ               62
#define ROUP_DIRECTIVE_ORDERED              63
#define ROUP_DIRECTIVE_UNKNOWN              86
#define ROUP_DIRECTIVE_UNKNOWN       999


// ============================================================================
// OpenMP Clause Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:convert_clause()

#define ROUP_CLAUSE_IF              0
#define ROUP_CLAUSE_NUM_THREADS     1
#define ROUP_CLAUSE_DEFAULT         2
#define ROUP_CLAUSE_PRIVATE         3
#define ROUP_CLAUSE_FIRSTPRIVATE    4
#define ROUP_CLAUSE_SHARED          5
#define ROUP_CLAUSE_COPYIN          6
#define ROUP_CLAUSE_ALIGN           7
#define ROUP_CLAUSE_REDUCTION       8
#define ROUP_CLAUSE_PROC_BIND       9
#define ROUP_CLAUSE_ALLOCATE        10
#define ROUP_CLAUSE_NUM_TEAMS       11
#define ROUP_CLAUSE_THREAD_LIMIT    12
#define ROUP_CLAUSE_LASTPRIVATE     13
#define ROUP_CLAUSE_COLLAPSE        14
#define ROUP_CLAUSE_ORDERED         15
#define ROUP_CLAUSE_PARTIAL         16
#define ROUP_CLAUSE_NOWAIT          17
#define ROUP_CLAUSE_FULL            18
#define ROUP_CLAUSE_ORDER           19
#define ROUP_CLAUSE_LINEAR          20
#define ROUP_CLAUSE_SCHEDULE        21
#define ROUP_CLAUSE_SAFELEN         22
#define ROUP_CLAUSE_SIMDLEN         23
#define ROUP_CLAUSE_ALIGNED         24
#define ROUP_CLAUSE_NONTEMPORAL     25
#define ROUP_CLAUSE_UNIFORM         26
#define ROUP_CLAUSE_INBRANCH        27
#define ROUP_CLAUSE_NOTINBRANCH     28
#define ROUP_CLAUSE_DIST_SCHEDULE   29
#define ROUP_CLAUSE_BIND            30
#define ROUP_CLAUSE_INCLUSIVE       31
#define ROUP_CLAUSE_EXCLUSIVE       32
#define ROUP_CLAUSE_COPYPRIVATE     33
#define ROUP_CLAUSE_PARALLEL        34
#define ROUP_CLAUSE_SECTIONS        35
#define ROUP_CLAUSE_FOR             36
#define ROUP_CLAUSE_DO              37
#define ROUP_CLAUSE_TASKGROUP       38
#define ROUP_CLAUSE_ALLOCATOR       39
#define ROUP_CLAUSE_INITIALIZER     40
#define ROUP_CLAUSE_FINAL           41
#define ROUP_CLAUSE_UNTIED          42
#define ROUP_CLAUSE_REQUIRES        43
#define ROUP_CLAUSE_MERGEABLE       44
#define ROUP_CLAUSE_IN_REDUCTION    45
#define ROUP_CLAUSE_DEPEND          46
#define ROUP_CLAUSE_PRIORITY        47
#define ROUP_CLAUSE_AFFINITY        48
#define ROUP_CLAUSE_DETACH          49
#define ROUP_CLAUSE_GRAINSIZE       50
#define ROUP_CLAUSE_NUM_TASKS       51
#define ROUP_CLAUSE_NOGROUP         52
#define ROUP_CLAUSE_REVERSE_OFFLOAD 53
#define ROUP_CLAUSE_UNIFIED_ADDRESS 54
#define ROUP_CLAUSE_UNIFIED_SHARED_MEMORY 55
#define ROUP_CLAUSE_ATOMIC_DEFAULT_MEM_ORDER 56
#define ROUP_CLAUSE_DYNAMIC_ALLOCATORS 57
#define ROUP_CLAUSE_EXT_IMPLEMENTATION_DEFINED_REQUIREMENT 58
#define ROUP_CLAUSE_DEVICE          59
#define ROUP_CLAUSE_MAP             60
#define ROUP_CLAUSE_USE_DEVICE_PTR  61
#define ROUP_CLAUSE_SIZES           62
#define ROUP_CLAUSE_USE_DEVICE_ADDR 63
#define ROUP_CLAUSE_IS_DEVICE_PTR   64
#define ROUP_CLAUSE_HAS_DEVICE_ADDR 65
#define ROUP_CLAUSE_DEFAULTMAP      66
#define ROUP_CLAUSE_TO              67
#define ROUP_CLAUSE_FROM            68
#define ROUP_CLAUSE_USES_ALLOCATORS 69
#define ROUP_CLAUSE_WHEN            70
#define ROUP_CLAUSE_MATCH           71
#define ROUP_CLAUSE_LINK            72
#define ROUP_CLAUSE_DEVICE_TYPE     73
#define ROUP_CLAUSE_TASK_REDUCTION  74
#define ROUP_CLAUSE_ACQ_REL         75
#define ROUP_CLAUSE_RELEASE         76
#define ROUP_CLAUSE_ACQUIRE         77
#define ROUP_CLAUSE_READ            78
#define ROUP_CLAUSE_WRITE           79
#define ROUP_CLAUSE_UPDATE          80
#define ROUP_CLAUSE_CAPTURE         81
#define ROUP_CLAUSE_SEQ_CST         82
#define ROUP_CLAUSE_RELAXED         83
#define ROUP_CLAUSE_HINT            84
#define ROUP_CLAUSE_DESTROY         85
#define ROUP_CLAUSE_DEPOBJ_UPDATE   86
#define ROUP_CLAUSE_THREADS         87
#define ROUP_CLAUSE_SIMD            88
#define ROUP_CLAUSE_UNKNOWN      999


// ============================================================================
// OpenACC Directive Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:acc_directive_name_to_kind()

#define ACC_DIRECTIVE_PARALLEL             0
#define ACC_DIRECTIVE_LOOP                 1
#define ACC_DIRECTIVE_KERNELS              2
#define ACC_DIRECTIVE_DATA                 3
#define ACC_DIRECTIVE_HOST_DATA            6
#define ACC_DIRECTIVE_ATOMIC               7
#define ACC_DIRECTIVE_DECLARE              8
#define ACC_DIRECTIVE_WAIT                 9
#define ACC_DIRECTIVE_END                  10
#define ACC_DIRECTIVE_UPDATE               12
#define ACC_DIRECTIVE_SERIAL               17
#define ACC_DIRECTIVE_ROUTINE              18
#define ACC_DIRECTIVE_SET                  19
#define ACC_DIRECTIVE_INIT                 20
#define ACC_DIRECTIVE_SHUTDOWN             21
#define ACC_DIRECTIVE_CACHE                23
#define ACC_DIRECTIVE_ENTER_DATA           24
#define ACC_DIRECTIVE_EXIT_DATA            25
#define ACC_DIRECTIVE_UNKNOWN        999


// ============================================================================
// OpenACC Clause Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:convert_acc_clause()

#define ACC_CLAUSE_ASYNC           0
#define ACC_CLAUSE_WAIT            1
#define ACC_CLAUSE_NUM_GANGS       2
#define ACC_CLAUSE_NUM_WORKERS     3
#define ACC_CLAUSE_VECTOR_LENGTH   4
#define ACC_CLAUSE_GANG            5
#define ACC_CLAUSE_WORKER          6
#define ACC_CLAUSE_VECTOR          7
#define ACC_CLAUSE_SEQ             8
#define ACC_CLAUSE_INDEPENDENT     9
#define ACC_CLAUSE_AUTO            10
#define ACC_CLAUSE_COLLAPSE        11
#define ACC_CLAUSE_DEVICE_TYPE     12
#define ACC_CLAUSE_BIND            13
#define ACC_CLAUSE_IF              14
#define ACC_CLAUSE_DEFAULT         15
#define ACC_CLAUSE_FIRSTPRIVATE    16
#define ACC_CLAUSE_DEFAULT_ASYNC   17
#define ACC_CLAUSE_LINK            18
#define ACC_CLAUSE_NO_CREATE       19
#define ACC_CLAUSE_NOHOST          20
#define ACC_CLAUSE_PRESENT         21
#define ACC_CLAUSE_PRIVATE         22
#define ACC_CLAUSE_REDUCTION       23
#define ACC_CLAUSE_READ            24
#define ACC_CLAUSE_SELF            25
#define ACC_CLAUSE_TILE            26
#define ACC_CLAUSE_USE_DEVICE      27
#define ACC_CLAUSE_ATTACH          28
#define ACC_CLAUSE_DETACH          29
#define ACC_CLAUSE_FINALIZE        30
#define ACC_CLAUSE_IF_PRESENT      31
#define ACC_CLAUSE_CAPTURE         32
#define ACC_CLAUSE_WRITE           33
#define ACC_CLAUSE_UPDATE          34
#define ACC_CLAUSE_COPY            35
#define ACC_CLAUSE_COPYIN          36
#define ACC_CLAUSE_COPYOUT         37
#define ACC_CLAUSE_CREATE          38
#define ACC_CLAUSE_DELETE          39
#define ACC_CLAUSE_DEVICE          40
#define ACC_CLAUSE_DEVICEPTR       41
#define ACC_CLAUSE_DEVICE_NUM      42
#define ACC_CLAUSE_DEVICE_RESIDENT 43
#define ACC_CLAUSE_HOST            44
#define ACC_CLAUSE_UNKNOWN       999


// ============================================================================
// Validation Constants
// ============================================================================
#define ROUP_MAX_PRAGMA_LENGTH 65536  // 64KB

#ifdef __cplusplus
}
#endif

#endif /* ROUP_CONSTANTS_H */
