/*
 * ROUP C API Constants (Auto-generated)
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by build.rs from src/c_api.rs
 *
 * Single source of truth: src/c_api.rs
 * - directive_name_to_kind() for directives
 * - convert_clause() for clauses
 *
 * Copyright (c) 2025 ROUP Project
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ROUP_CONSTANTS_H
#define ROUP_CONSTANTS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Synchronization Check
// ============================================================================
// Auto-generated checksum: FNV-1a hash of OpenMP (17 directives + 12 clauses) + OpenACC (18 directives + 0 clauses) = 0x2AD097A84C2E139F
// If this doesn't match c_api.rs, rebuild with `cargo clean && cargo build`
#define ROUP_CONSTANTS_CHECKSUM 0x2AD097A84C2E139F

// ============================================================================
// Language Format Constants
// ============================================================================
// Language format for roup_parse_with_language() and acc_parse_with_language()
#define ROUP_LANG_C                         0  // C/C++ (#pragma omp/#pragma acc)
#define ROUP_LANG_FORTRAN_FREE              1  // Fortran free-form (!$OMP/!$ACC)
#define ROUP_LANG_FORTRAN_FIXED             2  // Fortran fixed-form (!$OMP/!$ACC or C$OMP/C$ACC)

// ============================================================================
// OpenMP Directive Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:directive_name_to_kind()

#define ROUP_DIRECTIVE_PARALLEL             0
#define ROUP_DIRECTIVE_FOR                  1
#define ROUP_DIRECTIVE_SECTIONS             2
#define ROUP_DIRECTIVE_SINGLE               3
#define ROUP_DIRECTIVE_TASK                 4
#define ROUP_DIRECTIVE_MASTER               5
#define ROUP_DIRECTIVE_CRITICAL             6
#define ROUP_DIRECTIVE_BARRIER              7
#define ROUP_DIRECTIVE_TASKWAIT             8
#define ROUP_DIRECTIVE_TASKGROUP            9
#define ROUP_DIRECTIVE_ATOMIC               10
#define ROUP_DIRECTIVE_FLUSH                11
#define ROUP_DIRECTIVE_ORDERED              12
#define ROUP_DIRECTIVE_TARGET               13
#define ROUP_DIRECTIVE_TEAMS                14
#define ROUP_DIRECTIVE_DISTRIBUTE           15
#define ROUP_DIRECTIVE_METADIRECTIVE        16
#define ROUP_DIRECTIVE_UNKNOWN       999


// ============================================================================
// OpenMP Clause Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:convert_clause()

#define ROUP_CLAUSE_NUM_THREADS     0
#define ROUP_CLAUSE_IF              1
#define ROUP_CLAUSE_PRIVATE         2
#define ROUP_CLAUSE_SHARED          3
#define ROUP_CLAUSE_FIRSTPRIVATE    4
#define ROUP_CLAUSE_LASTPRIVATE     5
#define ROUP_CLAUSE_REDUCTION       6
#define ROUP_CLAUSE_SCHEDULE        7
#define ROUP_CLAUSE_COLLAPSE        8
#define ROUP_CLAUSE_ORDERED         9
#define ROUP_CLAUSE_NOWAIT          10
#define ROUP_CLAUSE_DEFAULT         11
#define ROUP_CLAUSE_UNKNOWN      999


// ============================================================================
// OpenACC Directive Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:acc_directive_name_to_kind()

#define ACC_DIRECTIVE_PARALLEL             0
#define ACC_DIRECTIVE_LOOP                 1
#define ACC_DIRECTIVE_KERNELS              2
#define ACC_DIRECTIVE_DATA                 3
#define ACC_DIRECTIVE_HOST_DATA            6
#define ACC_DIRECTIVE_ATOMIC               7
#define ACC_DIRECTIVE_DECLARE              8
#define ACC_DIRECTIVE_WAIT                 9
#define ACC_DIRECTIVE_END                  10
#define ACC_DIRECTIVE_UPDATE               12
#define ACC_DIRECTIVE_SERIAL               17
#define ACC_DIRECTIVE_ROUTINE              18
#define ACC_DIRECTIVE_SET                  19
#define ACC_DIRECTIVE_INIT                 20
#define ACC_DIRECTIVE_SHUTDOWN             21
#define ACC_DIRECTIVE_CACHE                23
#define ACC_DIRECTIVE_ENTER_DATA           24
#define ACC_DIRECTIVE_EXIT_DATA            25
#define ACC_DIRECTIVE_UNKNOWN        999


// ============================================================================
// OpenACC Clause Kind Constants
// ============================================================================
// Auto-generated from src/c_api.rs:convert_acc_clause()

#define ACC_CLAUSE_UNKNOWN       999


// ============================================================================
// Validation Constants
// ============================================================================
#define ROUP_MAX_PRAGMA_LENGTH 65536  // 64KB

#ifdef __cplusplus
}
#endif

#endif /* ROUP_CONSTANTS_H */
