#ifndef ROUP_CAPI_ROUP_H
#define ROUP_CAPI_ROUP_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ROUP_ABI_VERSION UINT32_C(2)

#define ROUP_STATUS_OK UINT32_C(0)
#define ROUP_STATUS_INVALID_ARGUMENT UINT32_C(1)
#define ROUP_STATUS_INVALID_UTF8 UINT32_C(2)
#define ROUP_STATUS_BUFFER_TOO_SMALL UINT32_C(3)
#define ROUP_STATUS_INVALID_HANDLE UINT32_C(4)
#define ROUP_STATUS_STALE_HANDLE UINT32_C(5)
#define ROUP_STATUS_PARSE_ERROR UINT32_C(6)
#define ROUP_STATUS_INTERNAL_ERROR UINT32_C(7)

#define ROUP_DIALECT_OPENMP UINT32_C(1)
#define ROUP_DIALECT_OPENACC UINT32_C(2)

#define ROUP_VERSION_ANY UINT32_C(0)
#define ROUP_VERSION_EXACT UINT32_C(1)
#define ROUP_PARSER_SOURCE_COMPATIBILITY (UINT32_C(1) << 0)

#define ROUP_OMP_VERSION_1_0 UINT32_C(100)
#define ROUP_OMP_VERSION_1_1 UINT32_C(110)
#define ROUP_OMP_VERSION_2_0 UINT32_C(200)
#define ROUP_OMP_VERSION_2_5 UINT32_C(250)
#define ROUP_OMP_VERSION_3_0 UINT32_C(300)
#define ROUP_OMP_VERSION_3_1 UINT32_C(310)
#define ROUP_OMP_VERSION_4_0 UINT32_C(400)
#define ROUP_OMP_VERSION_4_5 UINT32_C(450)
#define ROUP_OMP_VERSION_5_0 UINT32_C(500)
#define ROUP_OMP_VERSION_5_1 UINT32_C(510)
#define ROUP_OMP_VERSION_5_2 UINT32_C(520)
#define ROUP_OMP_VERSION_6_0 UINT32_C(600)

#define ROUP_ACC_VERSION_1_0 UINT32_C(100)
#define ROUP_ACC_VERSION_2_0 UINT32_C(200)
#define ROUP_ACC_VERSION_2_5 UINT32_C(250)
#define ROUP_ACC_VERSION_2_6 UINT32_C(260)
#define ROUP_ACC_VERSION_2_7 UINT32_C(270)
#define ROUP_ACC_VERSION_3_0 UINT32_C(300)
#define ROUP_ACC_VERSION_3_1 UINT32_C(310)
#define ROUP_ACC_VERSION_3_2 UINT32_C(320)
#define ROUP_ACC_VERSION_3_3 UINT32_C(330)
#define ROUP_ACC_VERSION_3_4 UINT32_C(340)

#define ROUP_OMP_VERSION_BIT_1_0 (UINT64_C(1) << 0)
#define ROUP_OMP_VERSION_BIT_1_1 (UINT64_C(1) << 1)
#define ROUP_OMP_VERSION_BIT_2_0 (UINT64_C(1) << 2)
#define ROUP_OMP_VERSION_BIT_2_5 (UINT64_C(1) << 3)
#define ROUP_OMP_VERSION_BIT_3_0 (UINT64_C(1) << 4)
#define ROUP_OMP_VERSION_BIT_3_1 (UINT64_C(1) << 5)
#define ROUP_OMP_VERSION_BIT_4_0 (UINT64_C(1) << 6)
#define ROUP_OMP_VERSION_BIT_4_5 (UINT64_C(1) << 7)
#define ROUP_OMP_VERSION_BIT_5_0 (UINT64_C(1) << 8)
#define ROUP_OMP_VERSION_BIT_5_1 (UINT64_C(1) << 9)
#define ROUP_OMP_VERSION_BIT_5_2 (UINT64_C(1) << 10)
#define ROUP_OMP_VERSION_BIT_6_0 (UINT64_C(1) << 11)

#define ROUP_ACC_VERSION_BIT_1_0 (UINT64_C(1) << 0)
#define ROUP_ACC_VERSION_BIT_2_0 (UINT64_C(1) << 1)
#define ROUP_ACC_VERSION_BIT_2_5 (UINT64_C(1) << 2)
#define ROUP_ACC_VERSION_BIT_2_6 (UINT64_C(1) << 3)
#define ROUP_ACC_VERSION_BIT_2_7 (UINT64_C(1) << 4)
#define ROUP_ACC_VERSION_BIT_3_0 (UINT64_C(1) << 5)
#define ROUP_ACC_VERSION_BIT_3_1 (UINT64_C(1) << 6)
#define ROUP_ACC_VERSION_BIT_3_2 (UINT64_C(1) << 7)
#define ROUP_ACC_VERSION_BIT_3_3 (UINT64_C(1) << 8)
#define ROUP_ACC_VERSION_BIT_3_4 (UINT64_C(1) << 9)

#define ROUP_HOST_C UINT32_C(1)
#define ROUP_HOST_CPP UINT32_C(2)
#define ROUP_HOST_FORTRAN UINT32_C(3)

#define ROUP_C_89 UINT32_C(89)
#define ROUP_C_99 UINT32_C(99)
#define ROUP_C_11 UINT32_C(11)
#define ROUP_C_18 UINT32_C(18)
#define ROUP_C_23 UINT32_C(23)
#define ROUP_CPP_98 UINT32_C(98)
#define ROUP_CPP_11 UINT32_C(11)
#define ROUP_CPP_14 UINT32_C(14)
#define ROUP_CPP_17 UINT32_C(17)
#define ROUP_CPP_20 UINT32_C(20)
#define ROUP_CPP_23 UINT32_C(23)
#define ROUP_FORTRAN_77 UINT32_C(77)
#define ROUP_FORTRAN_90 UINT32_C(90)
#define ROUP_FORTRAN_95 UINT32_C(95)
#define ROUP_FORTRAN_2003 UINT32_C(2003)
#define ROUP_FORTRAN_2008 UINT32_C(2008)
#define ROUP_FORTRAN_2018 UINT32_C(2018)
#define ROUP_FORTRAN_2023 UINT32_C(2023)

#define ROUP_SOURCE_PRAGMA UINT32_C(1)
#define ROUP_SOURCE_FORTRAN_FREE UINT32_C(2)
#define ROUP_SOURCE_FORTRAN_FIXED UINT32_C(3)

#define ROUP_DIAGNOSTIC_INVALID_POINTER UINT32_C(60000)
#define ROUP_DIAGNOSTIC_INVALID_UTF8 UINT32_C(60001)
#define ROUP_DIAGNOSTIC_BUFFER_TOO_SMALL UINT32_C(60002)
#define ROUP_DIAGNOSTIC_INVALID_HANDLE UINT32_C(60003)
#define ROUP_DIAGNOSTIC_INDEX_OUT_OF_RANGE UINT32_C(60004)
#define ROUP_DIAGNOSTIC_INTERNAL_ERROR UINT32_C(60005)

#define ROUP_FIELD_VALUE_BOOL UINT32_C(1)
#define ROUP_FIELD_VALUE_U32 UINT32_C(2)
#define ROUP_FIELD_VALUE_STRING UINT32_C(3)
#define ROUP_FIELD_VALUE_STRING_LIST UINT32_C(4)
#define ROUP_FIELD_VALUE_U32_LIST UINT32_C(5)
#define ROUP_FIELD_VALUE_NODE UINT32_C(6)
#define ROUP_FIELD_VALUE_NODE_LIST UINT32_C(7)
#define ROUP_FIELD_VALUE_U64 UINT32_C(8)

#define ROUP_FIELD_VALUE UINT32_C(1)
#define ROUP_FIELD_VALUES UINT32_C(2)
#define ROUP_FIELD_ITEMS UINT32_C(3)
#define ROUP_FIELD_KIND UINT32_C(4)
#define ROUP_FIELD_MODIFIER UINT32_C(5)
#define ROUP_FIELD_MODIFIERS UINT32_C(6)
#define ROUP_FIELD_OPERATOR UINT32_C(7)
#define ROUP_FIELD_USER_IDENTIFIER UINT32_C(8)
#define ROUP_FIELD_MAPPER UINT32_C(9)
#define ROUP_FIELD_ITERATORS UINT32_C(10)
#define ROUP_FIELD_CONDITION UINT32_C(11)
#define ROUP_FIELD_CHUNK_SIZE UINT32_C(12)
#define ROUP_FIELD_STEP UINT32_C(13)
#define ROUP_FIELD_ALIGNMENT UINT32_C(14)
#define ROUP_FIELD_ALLOCATOR UINT32_C(15)
#define ROUP_FIELD_LABEL UINT32_C(16)
#define ROUP_FIELD_ARGUMENTS UINT32_C(18)
#define ROUP_FIELD_DIRECTIVES UINT32_C(19)
#define ROUP_FIELD_BEHAVIOR UINT32_C(20)
#define ROUP_FIELD_CATEGORY UINT32_C(21)
#define ROUP_FIELD_DEPEND_TYPE UINT32_C(22)
#define ROUP_FIELD_DEVICE_NUM UINT32_C(23)
#define ROUP_FIELD_MEMORY_ORDER UINT32_C(26)
#define ROUP_FIELD_REQUIREMENTS UINT32_C(27)
#define ROUP_FIELD_ALLOCATORS UINT32_C(28)
#define ROUP_FIELD_READONLY UINT32_C(30)
#define ROUP_FIELD_NESTED_DIRECTIVE UINT32_C(37)
#define ROUP_FIELD_TYPE_NAME UINT32_C(38)
#define ROUP_FIELD_VARIABLE UINT32_C(39)
#define ROUP_FIELD_COMBINER UINT32_C(40)
#define ROUP_FIELD_INITIALIZER UINT32_C(41)
#define ROUP_FIELD_FUNCTION UINT32_C(42)
#define ROUP_FIELD_START UINT32_C(43)
#define ROUP_FIELD_END UINT32_C(44)
#define ROUP_FIELD_SCORE UINT32_C(45)
#define ROUP_FIELD_CLAUSES UINT32_C(46)
#define ROUP_FIELD_PARAMETER UINT32_C(47)
#define ROUP_FIELD_TRAITS UINT32_C(49)
#define ROUP_FIELD_ENTRIES UINT32_C(50)
#define ROUP_FIELD_FORCE UINT32_C(51)
#define ROUP_FIELD_DIRECTIVE UINT32_C(52)
#define ROUP_FIELD_MEMSPACE UINT32_C(53)
#define ROUP_FIELD_NAME UINT32_C(54)
#define ROUP_FIELD_VARIABLE_TYPE UINT32_C(55)
#define ROUP_FIELD_STEP_TYPE UINT32_C(56)
#define ROUP_FIELD_TYPE_SPECIFIERS UINT32_C(57)
#define ROUP_FIELD_EVENT UINT32_C(58)
#define ROUP_FIELD_DO_NOT_SYNCHRONIZE UINT32_C(59)
#define ROUP_FIELD_FULLY_UNROLL UINT32_C(60)
#define ROUP_FIELD_UNROLL_FACTOR UINT32_C(61)
#define ROUP_FIELD_CAN_MERGE UINT32_C(62)
#define ROUP_FIELD_CAN_CHANGE_THREADS UINT32_C(63)
#define ROUP_FIELD_APPLY_TO_SIMD UINT32_C(64)
#define ROUP_FIELD_APPLY_TO_THREADS UINT32_C(65)
#define ROUP_FIELD_CAN_ASSUME UINT32_C(66)
#define ROUP_FIELD_INVOKED_BY_FPTR UINT32_C(67)
#define ROUP_FIELD_REPLAYABLE_EXPRESSION UINT32_C(68)
#define ROUP_FIELD_WIDTH UINT32_C(69)
#define ROUP_FIELD_IMPEX_TYPE UINT32_C(70)
#define ROUP_FIELD_USE_SEMANTICS UINT32_C(71)
#define ROUP_FIELD_REQUIRED UINT32_C(72)
#define ROUP_FIELD_BASE UINT32_C(73)
#define ROUP_FIELD_GLOBAL UINT32_C(74)
#define ROUP_FIELD_QUALIFIER UINT32_C(75)
#define ROUP_FIELD_ENCODING UINT32_C(76)
#define ROUP_FIELD_FIRST UINT32_C(77)
#define ROUP_FIELD_COUNT UINT32_C(78)
#define ROUP_FIELD_DIRECTIVE_NAME_MODIFIER UINT32_C(79)
#define ROUP_FIELD_OPERATION UINT32_C(80)
#define ROUP_FIELD_PARAMETERS UINT32_C(81)
#define ROUP_FIELD_OPERATIONS UINT32_C(82)
#define ROUP_FIELD_OFFSET UINT32_C(83)
#define ROUP_FIELD_OBJECTS UINT32_C(84)
#define ROUP_FIELD_LOWER_BOUND UINT32_C(90)
#define ROUP_FIELD_UPPER_BOUND UINT32_C(91)
#define ROUP_FIELD_SOURCE_SYNTAX UINT32_C(92)
#define ROUP_FIELD_ALLOCATOR_EXPRESSION UINT32_C(93)
#define ROUP_FIELD_ALIGNMENT_EXPRESSION UINT32_C(94)
#define ROUP_FIELD_ALLOCATE_SOURCE_SYNTAX UINT32_C(95)
#define ROUP_FIELD_LOOP_MODIFIER UINT32_C(100)
#define ROUP_FIELD_INDICES UINT32_C(101)
#define ROUP_FIELD_APPLIED_DIRECTIVES UINT32_C(102)
#define ROUP_FIELD_IDENTIFIER UINT32_C(103)
#define ROUP_FIELD_INTEROP_TYPES UINT32_C(104)
#define ROUP_FIELD_PREFERENCES UINT32_C(105)
#define ROUP_FIELD_SELECTORS UINT32_C(106)
#define ROUP_FIELD_ATTRIBUTES UINT32_C(107)
#define ROUP_FIELD_LOCATOR UINT32_C(108)
#define ROUP_FIELD_ITERATION UINT32_C(109)
#define ROUP_FIELD_DEPENDENCE UINT32_C(110)
#define ROUP_FIELD_PROPERTIES UINT32_C(120)
#define ROUP_FIELD_TRAIT_NAME UINT32_C(121)
#define ROUP_FIELD_REQUIREMENT UINT32_C(122)
#define ROUP_FIELD_SOURCE_ALIAS UINT32_C(123)
#define ROUP_FIELD_QUEUES_KEYWORD UINT32_C(124)
#define ROUP_FIELD_MAP_TYPE_SPELLING UINT32_C(125)
#define ROUP_FIELD_PRECEDING_SEPARATOR UINT32_C(126)
#define ROUP_FIELD_QUOTE_STYLE UINT32_C(127)
#define ROUP_FIELD_DECLARATOR_ATTACHED UINT32_C(128)
#define ROUP_FIELD_LENGTH UINT32_C(129)
#define ROUP_FIELD_STRIDE UINT32_C(130)

#define ROUP_OMP_CLAUSE_ALIAS_DEPEND_SOURCE UINT32_C(1)
#define ROUP_OMP_CLAUSE_ALIAS_DEPEND_SOURCE_CURRENT UINT32_C(2)
#define ROUP_OMP_CLAUSE_ALIAS_DEPEND_SINK UINT32_C(3)
#define ROUP_OMP_CLAUSE_ALIAS_DEPEND_SINK_PREVIOUS_CURRENT UINT32_C(4)
#define ROUP_OMP_CLAUSE_ALIAS_METADIRECTIVE_DEFAULT UINT32_C(5)
#define ROUP_OMP_CLAUSE_ALIAS_DECLARE_TARGET_TO UINT32_C(6)
#define ROUP_OMP_CLAUSE_ALIAS_PROC_BIND_MASTER UINT32_C(7)
#define ROUP_OMP_CLAUSE_ALIAS_DOACROSS_SOURCE_EMPTY UINT32_C(8)
#define ROUP_OMP_CLAUSE_ALIAS_REDUCTION_ORIGINAL_POSITIONAL UINT32_C(9)

#define ROUP_OMP_DIRECTIVE_ALIAS_NONE UINT32_C(0)
#define ROUP_OMP_DIRECTIVE_ALIAS_OPENMP60_UNDERSCORE UINT32_C(1)
#define ROUP_OMP_DIRECTIVE_ALIAS_FORTRAN_COMPACT UINT32_C(2)
#define ROUP_OMP_DIRECTIVE_ALIAS_FORTRAN_REDUNDANT_OMP UINT32_C(3)

#define ROUP_OMP_CLAUSE_SEPARATOR_SPACE UINT32_C(1)
#define ROUP_OMP_CLAUSE_SEPARATOR_COMMA UINT32_C(2)

#define ROUP_OMP_DECLARE_REDUCTION_INLINE_COMBINER UINT32_C(1)
#define ROUP_OMP_DECLARE_REDUCTION_COMBINER_CLAUSE UINT32_C(2)

#define ROUP_QUOTE_SINGLE UINT32_C(1)
#define ROUP_QUOTE_DOUBLE UINT32_C(2)

#define ROUP_OMP_USES_ALLOCATORS_HISTORICAL UINT32_C(1)
#define ROUP_OMP_USES_ALLOCATORS_MODIFIER UINT32_C(2)

#define ROUP_ACC_CLAUSE_ALIAS_PCOPY UINT32_C(1)
#define ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPY UINT32_C(2)
#define ROUP_ACC_CLAUSE_ALIAS_PCOPYIN UINT32_C(3)
#define ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPYIN UINT32_C(4)
#define ROUP_ACC_CLAUSE_ALIAS_PCOPYOUT UINT32_C(5)
#define ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_COPYOUT UINT32_C(6)
#define ROUP_ACC_CLAUSE_ALIAS_PCREATE UINT32_C(7)
#define ROUP_ACC_CLAUSE_ALIAS_PRESENT_OR_CREATE UINT32_C(8)
#define ROUP_ACC_CLAUSE_ALIAS_UPDATE_HOST UINT32_C(9)

#define ROUP_NODE_FAMILY_REQUIRE_MODIFIER UINT32_C(3)
#define ROUP_NODE_FAMILY_DEPEND_ITERATOR UINT32_C(4)
#define ROUP_NODE_FAMILY_USES_ALLOCATOR UINT32_C(5)
#define ROUP_NODE_FAMILY_OMP_DIRECTIVE UINT32_C(6)
#define ROUP_NODE_FAMILY_OMP_CLAUSE UINT32_C(7)
#define ROUP_NODE_FAMILY_REDUCTION_MODIFIER UINT32_C(8)
#define ROUP_NODE_FAMILY_OMP_PARAMETER UINT32_C(10)
#define ROUP_NODE_FAMILY_OMP_INDUCTION_TYPE UINT32_C(12)
#define ROUP_NODE_FAMILY_ACC_SIZE_EXPRESSION UINT32_C(13)
#define ROUP_NODE_FAMILY_ACC_GANG_ARGUMENT UINT32_C(14)
#define ROUP_NODE_FAMILY_ACC_CACHE_ITEM UINT32_C(15)
#define ROUP_NODE_FAMILY_ACC_END_KIND UINT32_C(16)
#define ROUP_NODE_FAMILY_ACC_BIND_TARGET UINT32_C(17)
#define ROUP_NODE_FAMILY_CLAUSE_ITEM UINT32_C(18)
#define ROUP_NODE_FAMILY_OMP_STORAGE_ITEM UINT32_C(19)
#define ROUP_NODE_FAMILY_OMP_DECLARE_TARGET_ITEM UINT32_C(20)
#define ROUP_NODE_FAMILY_OMP_FLUSH_ITEM UINT32_C(21)
#define ROUP_NODE_FAMILY_OMP_MAPPER_ID UINT32_C(22)
#define ROUP_NODE_FAMILY_OMP_ID_EXPRESSION UINT32_C(23)
#define ROUP_NODE_FAMILY_OMP_CPP_OPERATOR_QUALIFIER UINT32_C(24)
#define ROUP_NODE_FAMILY_OMP_IDENTIFIER UINT32_C(25)
#define ROUP_NODE_FAMILY_OMP_STYLIZED_EXPRESSION UINT32_C(26)
#define ROUP_NODE_FAMILY_OMP_REDUCTION_INITIALIZER UINT32_C(27)
#define ROUP_NODE_FAMILY_OMP_INITIALIZER_VALUE UINT32_C(28)
#define ROUP_NODE_FAMILY_OMP_ALLOCATOR_KIND UINT32_C(29)
#define ROUP_NODE_FAMILY_ACC_DEVICE_TYPE UINT32_C(30)
#define ROUP_NODE_FAMILY_ACC_REDUCTION_OPERATOR UINT32_C(31)
#define ROUP_NODE_FAMILY_OMP_COUNT UINT32_C(32)
#define ROUP_NODE_FAMILY_OMP_LOCATOR UINT32_C(33)
#define ROUP_NODE_FAMILY_OMP_PARAMETER_LIST_ITEM UINT32_C(40)
#define ROUP_NODE_FAMILY_OMP_APPEND_OPERATION UINT32_C(41)
#define ROUP_NODE_FAMILY_OMP_APPLY_MODIFIER UINT32_C(50)
#define ROUP_NODE_FAMILY_OMP_PREFERENCE_SPECIFICATION UINT32_C(51)
#define ROUP_NODE_FAMILY_OMP_PREFERENCE_SELECTOR UINT32_C(52)
#define ROUP_NODE_FAMILY_OMP_FOREIGN_RUNTIME_IDENTIFIER UINT32_C(53)
#define ROUP_NODE_FAMILY_STRING_LITERAL UINT32_C(54)
#define ROUP_NODE_FAMILY_OMP_DEPENDENCE UINT32_C(55)
#define ROUP_NODE_FAMILY_OMP_DOACROSS_ITERATION UINT32_C(56)
#define ROUP_NODE_FAMILY_OMP_DOACROSS_VECTOR_ITEM UINT32_C(57)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_ENTRY UINT32_C(60)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_DEVICE_TRAIT UINT32_C(61)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_IMPLEMENTATION_TRAIT UINT32_C(62)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_NAME_LIST_TRAIT UINT32_C(63)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_EXTENSION_TRAIT UINT32_C(64)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_EXTENSION_PROPERTY UINT32_C(65)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_REQUIREMENT UINT32_C(66)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_CONSTRUCT UINT32_C(67)
#define ROUP_NODE_FAMILY_OMP_SELECTOR_TRAIT_VALUE UINT32_C(68)
#define ROUP_NODE_FAMILY_OMP_ARRAY_SHAPING_SUBSCRIPT UINT32_C(69)
#define ROUP_NODE_FAMILY_OMPX_PAYLOAD_ITEM UINT32_C(70)

#define ROUP_NODE_RECORD UINT32_C(1)

#define ROUP_OMP_APPLY_FUSED UINT32_C(1)
#define ROUP_OMP_APPLY_GRID UINT32_C(2)
#define ROUP_OMP_APPLY_IDENTITY UINT32_C(3)
#define ROUP_OMP_APPLY_INTERCHANGED UINT32_C(4)
#define ROUP_OMP_APPLY_INTRATILE UINT32_C(5)
#define ROUP_OMP_APPLY_OFFSETS UINT32_C(6)
#define ROUP_OMP_APPLY_REVERSED UINT32_C(7)
#define ROUP_OMP_APPLY_SPLIT UINT32_C(8)
#define ROUP_OMP_APPLY_UNROLLED UINT32_C(9)

#define ROUP_OMP_INDUCTION_RELAXED UINT32_C(1)
#define ROUP_OMP_INDUCTION_STRICT UINT32_C(2)

#define ROUP_OMP_INTEROP_TARGET UINT32_C(1)
#define ROUP_OMP_INTEROP_TARGETSYNC UINT32_C(2)
#define ROUP_OMP_PREFERENCE_FOREIGN_RUNTIME UINT32_C(1)
#define ROUP_OMP_PREFERENCE_SELECTORS UINT32_C(2)
#define ROUP_OMP_PREFERENCE_SELECTOR_FOREIGN_RUNTIME UINT32_C(1)
#define ROUP_OMP_PREFERENCE_SELECTOR_ATTRIBUTES UINT32_C(2)
#define ROUP_OMP_FOREIGN_RUNTIME_STRING UINT32_C(1)
#define ROUP_OMP_FOREIGN_RUNTIME_EXPRESSION UINT32_C(2)
#define ROUP_STRING_LITERAL UINT32_C(1)

#define ROUP_OMP_PARAMETER_NAMED UINT32_C(1)
#define ROUP_OMP_PARAMETER_POSITION UINT32_C(2)
#define ROUP_OMP_PARAMETER_RANGE UINT32_C(3)

#define ROUP_OMP_APPEND_INTEROP UINT32_C(1)

#define ROUP_OMP_DEPENDENCE_LOCATORS UINT32_C(1)
#define ROUP_OMP_DEPENDENCE_DEPOBJS UINT32_C(2)

#define ROUP_OMP_DOACROSS_CURRENT UINT32_C(1)
#define ROUP_OMP_DOACROSS_PREVIOUS_CURRENT UINT32_C(2)
#define ROUP_OMP_DOACROSS_VECTOR UINT32_C(3)
#define ROUP_OMP_DOACROSS_VECTOR_ITEM UINT32_C(1)
#define ROUP_OMP_DOACROSS_OFFSET_ADD UINT32_C(1)
#define ROUP_OMP_DOACROSS_OFFSET_SUBTRACT UINT32_C(2)

#define ROUP_INDUCTION_TYPE_SAME UINT32_C(1)
#define ROUP_INDUCTION_TYPE_PAIR UINT32_C(2)

#define ROUP_ACC_SIZE_AUTOMATIC UINT32_C(1)
#define ROUP_ACC_SIZE_EXPRESSION UINT32_C(2)

#define ROUP_ACC_GANG_POSITIONAL UINT32_C(1)
#define ROUP_ACC_GANG_NUM UINT32_C(2)
#define ROUP_ACC_GANG_DIM UINT32_C(3)
#define ROUP_ACC_GANG_STATIC UINT32_C(4)

#define ROUP_ACC_CACHE_ARRAY_ELEMENT UINT32_C(1)
#define ROUP_ACC_CACHE_CONTIGUOUS_SUBARRAY UINT32_C(2)
#define ROUP_ACC_CACHE_SCALAR UINT32_C(3)

#define ROUP_ACC_END_ATOMIC UINT32_C(1)
#define ROUP_ACC_END_DATA UINT32_C(2)
#define ROUP_ACC_END_HOST_DATA UINT32_C(3)
#define ROUP_ACC_END_KERNELS UINT32_C(4)
#define ROUP_ACC_END_KERNELS_LOOP UINT32_C(5)
#define ROUP_ACC_END_LOOP UINT32_C(6)
#define ROUP_ACC_END_PARALLEL UINT32_C(7)
#define ROUP_ACC_END_PARALLEL_LOOP UINT32_C(8)
#define ROUP_ACC_END_SERIAL UINT32_C(9)
#define ROUP_ACC_END_SERIAL_LOOP UINT32_C(10)

#define ROUP_ACC_BIND_NAME UINT32_C(1)
#define ROUP_ACC_BIND_STRING_LITERAL UINT32_C(2)

#define ROUP_CLAUSE_ITEM_IDENTIFIER UINT32_C(1)
#define ROUP_CLAUSE_ITEM_VARIABLE UINT32_C(2)
#define ROUP_CLAUSE_ITEM_FORTRAN_COMMON_BLOCK UINT32_C(3)
#define ROUP_CLAUSE_ITEM_EXPRESSION UINT32_C(4)
#define ROUP_CLAUSE_ITEM_LEGACY_TRAILING_SLASH UINT32_C(5)
#define ROUP_CLAUSE_ITEM_LVALUE UINT32_C(6)

#define ROUP_OMP_STORAGE_ITEM_NAME UINT32_C(1)
#define ROUP_OMP_STORAGE_ITEM_FORTRAN_COMMON_BLOCK UINT32_C(2)

#define ROUP_OMP_DECLARE_TARGET_ITEM_NAME UINT32_C(1)
#define ROUP_OMP_DECLARE_TARGET_ITEM_FORTRAN_COMMON_BLOCK UINT32_C(2)

#define ROUP_OMP_FLUSH_ITEM_IDENTIFIER UINT32_C(1)
#define ROUP_OMP_FLUSH_ITEM_VARIABLE UINT32_C(2)
#define ROUP_OMP_FLUSH_ITEM_FORTRAN_COMMON_BLOCK UINT32_C(3)

#define ROUP_OMP_MAPPER_ID_DEFAULT UINT32_C(1)
#define ROUP_OMP_MAPPER_ID_USER UINT32_C(2)

#define ROUP_OMP_ID_EXPRESSION_NAME UINT32_C(1)
#define ROUP_OMP_ID_EXPRESSION_CPP_TEMPLATE_ID UINT32_C(2)
#define ROUP_OMP_ID_EXPRESSION_CPP_OPERATOR_FUNCTION UINT32_C(3)

#define ROUP_OMP_CPP_OPERATOR_QUALIFIER_NAME UINT32_C(1)
#define ROUP_OMP_CPP_OPERATOR_QUALIFIER_TEMPLATE_ID UINT32_C(2)

#define ROUP_OMP_IDENTIFIER_ADD UINT32_C(1)
#define ROUP_OMP_IDENTIFIER_SUBTRACT UINT32_C(2)
#define ROUP_OMP_IDENTIFIER_MULTIPLY UINT32_C(3)
#define ROUP_OMP_IDENTIFIER_BITWISE_AND UINT32_C(4)
#define ROUP_OMP_IDENTIFIER_BITWISE_OR UINT32_C(5)
#define ROUP_OMP_IDENTIFIER_BITWISE_XOR UINT32_C(6)
#define ROUP_OMP_IDENTIFIER_LOGICAL_AND UINT32_C(7)
#define ROUP_OMP_IDENTIFIER_LOGICAL_OR UINT32_C(8)
#define ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_AND UINT32_C(9)
#define ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_OR UINT32_C(10)
#define ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_EQV UINT32_C(11)
#define ROUP_OMP_IDENTIFIER_FORTRAN_LOGICAL_NEQV UINT32_C(12)
#define ROUP_OMP_IDENTIFIER_NAME UINT32_C(13)
#define ROUP_OMP_IDENTIFIER_FORTRAN_MAX UINT32_C(14)
#define ROUP_OMP_IDENTIFIER_FORTRAN_MIN UINT32_C(15)
#define ROUP_OMP_IDENTIFIER_FORTRAN_IAND UINT32_C(16)
#define ROUP_OMP_IDENTIFIER_FORTRAN_IOR UINT32_C(17)
#define ROUP_OMP_IDENTIFIER_FORTRAN_IEOR UINT32_C(18)
#define ROUP_OMP_IDENTIFIER_FORTRAN_DEFINED_OPERATOR UINT32_C(19)

#define ROUP_OMP_STYLIZED_C_CPP_EXPRESSION UINT32_C(1)
#define ROUP_OMP_STYLIZED_FORTRAN_ASSIGNMENT UINT32_C(2)
#define ROUP_OMP_STYLIZED_FORTRAN_SUBROUTINE_CALL UINT32_C(3)

#define ROUP_OMP_INITIALIZER_C_ASSIGNMENT UINT32_C(1)
#define ROUP_OMP_INITIALIZER_CPP_COPY UINT32_C(2)
#define ROUP_OMP_INITIALIZER_CPP_DIRECT UINT32_C(3)
#define ROUP_OMP_INITIALIZER_CPP_LIST UINT32_C(4)
#define ROUP_OMP_INITIALIZER_C_CPP_FUNCTION_CALL UINT32_C(5)
#define ROUP_OMP_INITIALIZER_FORTRAN_ASSIGNMENT UINT32_C(6)
#define ROUP_OMP_INITIALIZER_FORTRAN_SUBROUTINE_CALL UINT32_C(7)

#define ROUP_OMP_INITIALIZER_VALUE_EXPRESSION UINT32_C(1)
#define ROUP_OMP_INITIALIZER_VALUE_BRACED UINT32_C(2)

#define ROUP_OMP_ALLOCATOR_NULL UINT32_C(1)
#define ROUP_OMP_ALLOCATOR_DEFAULT UINT32_C(2)
#define ROUP_OMP_ALLOCATOR_LARGE_CAP UINT32_C(3)
#define ROUP_OMP_ALLOCATOR_CONST UINT32_C(4)
#define ROUP_OMP_ALLOCATOR_HIGH_BW UINT32_C(5)
#define ROUP_OMP_ALLOCATOR_LOW_LAT UINT32_C(6)
#define ROUP_OMP_ALLOCATOR_CGROUP UINT32_C(7)
#define ROUP_OMP_ALLOCATOR_PTEAM UINT32_C(8)
#define ROUP_OMP_ALLOCATOR_THREAD UINT32_C(9)
#define ROUP_OMP_ALLOCATOR_CUSTOM UINT32_C(10)

#define ROUP_ACC_DEVICE_TYPE_HOST UINT32_C(1)
#define ROUP_ACC_DEVICE_TYPE_WILDCARD UINT32_C(2)
#define ROUP_ACC_DEVICE_TYPE_MULTICORE UINT32_C(3)
#define ROUP_ACC_DEVICE_TYPE_DEFAULT UINT32_C(4)
#define ROUP_ACC_DEVICE_TYPE_NAMED UINT32_C(5)

#define ROUP_ACC_REDUCTION_ADD UINT32_C(1)
#define ROUP_ACC_REDUCTION_MUL UINT32_C(2)
#define ROUP_ACC_REDUCTION_MAX UINT32_C(3)
#define ROUP_ACC_REDUCTION_MIN UINT32_C(4)
#define ROUP_ACC_REDUCTION_BIT_AND UINT32_C(5)
#define ROUP_ACC_REDUCTION_BIT_OR UINT32_C(6)
#define ROUP_ACC_REDUCTION_BIT_XOR UINT32_C(7)
#define ROUP_ACC_REDUCTION_LOG_AND UINT32_C(8)
#define ROUP_ACC_REDUCTION_LOG_OR UINT32_C(9)
#define ROUP_ACC_REDUCTION_FORTRAN_AND UINT32_C(10)
#define ROUP_ACC_REDUCTION_FORTRAN_OR UINT32_C(11)
#define ROUP_ACC_REDUCTION_FORTRAN_EQV UINT32_C(12)
#define ROUP_ACC_REDUCTION_FORTRAN_NEQV UINT32_C(13)
#define ROUP_ACC_REDUCTION_FORTRAN_IAND UINT32_C(14)
#define ROUP_ACC_REDUCTION_FORTRAN_IOR UINT32_C(15)
#define ROUP_ACC_REDUCTION_FORTRAN_IEOR UINT32_C(16)
#define ROUP_ACC_REDUCTION_SUB UINT32_C(17)

#define ROUP_OMP_COUNT_FILL UINT32_C(1)
#define ROUP_OMP_COUNT_EXPRESSION UINT32_C(2)

#define ROUP_OMP_LOCATOR_LVALUE UINT32_C(1)
#define ROUP_OMP_LOCATOR_FORTRAN_COMMON_BLOCK UINT32_C(2)
#define ROUP_OMP_LOCATOR_POTENTIAL_LVALUE UINT32_C(3)
#define ROUP_OMP_LOCATOR_ALL_MEMORY UINT32_C(4)
#define ROUP_OMP_LOCATOR_DISTRIBUTED UINT32_C(5)
#define ROUP_OMP_LOCATOR_ARRAY_SHAPING UINT32_C(6)

#define ROUP_OMP_ARRAY_SHAPING_INDEX UINT32_C(1)
#define ROUP_OMP_ARRAY_SHAPING_SECTION UINT32_C(2)
#define ROUP_OMP_DIST_DATA_DUPLICATE UINT32_C(1)

#define ROUP_OMP_DATA_MOTION_PRESENT UINT32_C(1)
#define ROUP_OMP_ENTER_AUTOMAP UINT32_C(1)

#define ROUP_OMP_CPP_OPERATOR_ADD UINT32_C(1)
#define ROUP_OMP_CPP_OPERATOR_SUBTRACT UINT32_C(2)
#define ROUP_OMP_CPP_OPERATOR_MULTIPLY UINT32_C(3)
#define ROUP_OMP_CPP_OPERATOR_BITWISE_AND UINT32_C(4)
#define ROUP_OMP_CPP_OPERATOR_BITWISE_OR UINT32_C(5)
#define ROUP_OMP_CPP_OPERATOR_BITWISE_XOR UINT32_C(6)
#define ROUP_OMP_CPP_OPERATOR_LOGICAL_AND UINT32_C(7)
#define ROUP_OMP_CPP_OPERATOR_LOGICAL_OR UINT32_C(8)

#define ROUP_OMP_CONSTRUCT_PARALLEL UINT32_C(1)
#define ROUP_OMP_CONSTRUCT_SECTIONS UINT32_C(2)
#define ROUP_OMP_CONSTRUCT_FOR UINT32_C(3)
#define ROUP_OMP_CONSTRUCT_TASKGROUP UINT32_C(4)

#define ROUP_OMP_SCAN_INCLUSIVE UINT32_C(1)
#define ROUP_OMP_SCAN_EXCLUSIVE UINT32_C(2)
#define ROUP_OMP_ADJUST_ARGS_NEED_DEVICE_PTR UINT32_C(1)
#define ROUP_OMP_ADJUST_ARGS_NEED_DEVICE_ADDR UINT32_C(2)
#define ROUP_OMP_ADJUST_ARGS_NOTHING UINT32_C(3)
#define ROUP_OMP_FIRSTPRIVATE_SAVED UINT32_C(1)
#define ROUP_OMP_LASTPRIVATE_CONDITIONAL UINT32_C(1)
#define ROUP_OMP_ORIGINAL_SHARING_DEFAULT UINT32_C(1)
#define ROUP_OMP_ORIGINAL_SHARING_PRIVATE UINT32_C(2)
#define ROUP_OMP_ORIGINAL_SHARING_SHARED UINT32_C(3)

#define ROUP_OMP_DEFAULT_SHARED UINT32_C(1)
#define ROUP_OMP_DEFAULT_NONE UINT32_C(2)
#define ROUP_OMP_DEFAULT_PRIVATE UINT32_C(3)
#define ROUP_OMP_DEFAULT_FIRSTPRIVATE UINT32_C(4)

#define ROUP_OMP_DEFAULTMAP_ALLOC UINT32_C(1)
#define ROUP_OMP_DEFAULTMAP_TO UINT32_C(2)
#define ROUP_OMP_DEFAULTMAP_FROM UINT32_C(3)
#define ROUP_OMP_DEFAULTMAP_TOFROM UINT32_C(4)
#define ROUP_OMP_DEFAULTMAP_FIRSTPRIVATE UINT32_C(5)
#define ROUP_OMP_DEFAULTMAP_NONE UINT32_C(6)
#define ROUP_OMP_DEFAULTMAP_DEFAULT UINT32_C(7)
#define ROUP_OMP_DEFAULTMAP_PRESENT UINT32_C(8)
#define ROUP_OMP_DEFAULTMAP_PRIVATE UINT32_C(9)
#define ROUP_OMP_DEFAULTMAP_SELF UINT32_C(10)
#define ROUP_OMP_DEFAULTMAP_STORAGE UINT32_C(11)
#define ROUP_OMP_DEFAULTMAP_CATEGORY_SCALAR UINT32_C(1)
#define ROUP_OMP_DEFAULTMAP_CATEGORY_AGGREGATE UINT32_C(2)
#define ROUP_OMP_DEFAULTMAP_CATEGORY_POINTER UINT32_C(3)
#define ROUP_OMP_DEFAULTMAP_CATEGORY_ALL UINT32_C(4)
#define ROUP_OMP_DEFAULTMAP_CATEGORY_ALLOCATABLE UINT32_C(5)

#define ROUP_OMP_MAP_TO UINT32_C(1)
#define ROUP_OMP_MAP_FROM UINT32_C(2)
#define ROUP_OMP_MAP_TOFROM UINT32_C(3)
#define ROUP_OMP_MAP_STORAGE UINT32_C(4)
#define ROUP_OMP_MAP_TYPE_SPELLING_CANONICAL UINT32_C(1)
#define ROUP_OMP_MAP_TYPE_SPELLING_ALLOC UINT32_C(2)
#define ROUP_OMP_MAP_TYPE_SPELLING_RELEASE UINT32_C(3)
#define ROUP_OMP_MAP_TYPE_SPELLING_DELETE UINT32_C(4)
#define ROUP_OMP_MAP_MODIFIER_ALWAYS UINT32_C(1)
#define ROUP_OMP_MAP_MODIFIER_CLOSE UINT32_C(2)
#define ROUP_OMP_MAP_MODIFIER_PRESENT UINT32_C(3)
#define ROUP_OMP_MAP_MODIFIER_SELF UINT32_C(4)
#define ROUP_OMP_MAP_MODIFIER_ITERATOR UINT32_C(5)
#define ROUP_OMP_MAP_MODIFIER_REF_POINTEE UINT32_C(6)
#define ROUP_OMP_MAP_MODIFIER_REF_POINTER UINT32_C(7)
#define ROUP_OMP_MAP_MODIFIER_REF_POINTER_AND_POINTEE UINT32_C(8)
#define ROUP_OMP_MAP_MODIFIER_DELETE UINT32_C(9)

#define ROUP_OMP_DEPEND_IN UINT32_C(1)
#define ROUP_OMP_DEPEND_OUT UINT32_C(2)
#define ROUP_OMP_DEPEND_INOUT UINT32_C(3)
#define ROUP_OMP_DEPEND_INOUTSET UINT32_C(4)
#define ROUP_OMP_DEPEND_MUTEXINOUTSET UINT32_C(5)
#define ROUP_OMP_DEPEND_DEPOBJ UINT32_C(6)
#define ROUP_OMP_DOACROSS_SOURCE UINT32_C(1)
#define ROUP_OMP_DOACROSS_SINK UINT32_C(2)
#define ROUP_OMP_AFFINITY_ITERATOR UINT32_C(1)

#define ROUP_OMP_SCHEDULE_STATIC UINT32_C(1)
#define ROUP_OMP_SCHEDULE_DYNAMIC UINT32_C(2)
#define ROUP_OMP_SCHEDULE_GUIDED UINT32_C(3)
#define ROUP_OMP_SCHEDULE_AUTO UINT32_C(4)
#define ROUP_OMP_SCHEDULE_RUNTIME UINT32_C(5)
#define ROUP_OMP_SCHEDULE_MODIFIER_MONOTONIC UINT32_C(1)
#define ROUP_OMP_SCHEDULE_MODIFIER_NONMONOTONIC UINT32_C(2)
#define ROUP_OMP_SCHEDULE_MODIFIER_SIMD UINT32_C(3)
#define ROUP_OMP_LINEAR_VAL UINT32_C(1)
#define ROUP_OMP_LINEAR_REF UINT32_C(2)
#define ROUP_OMP_LINEAR_UVAL UINT32_C(3)
#define ROUP_OMP_LINEAR_SOURCE_HISTORICAL UINT32_C(1)
#define ROUP_OMP_LINEAR_SOURCE_MODIFIER_PREFIX UINT32_C(2)
#define ROUP_OMP_LINEAR_SOURCE_CANONICAL_MODIFIERS UINT32_C(3)
#define ROUP_OMP_ALLOCATE_SOURCE_UNMODIFIED UINT32_C(1)
#define ROUP_OMP_ALLOCATE_SOURCE_SIMPLE_ALLOCATOR UINT32_C(2)
#define ROUP_OMP_ALLOCATE_SOURCE_MODIFIERS UINT32_C(3)
#define ROUP_OMP_NUM_THREADS_STRICT UINT32_C(1)
#define ROUP_OMP_MEMORY_SPACE_DEFAULT UINT32_C(1)
#define ROUP_OMP_MEMORY_SPACE_LARGE_CAP UINT32_C(2)
#define ROUP_OMP_MEMORY_SPACE_CONST UINT32_C(3)
#define ROUP_OMP_MEMORY_SPACE_HIGH_BW UINT32_C(4)
#define ROUP_OMP_MEMORY_SPACE_LOW_LAT UINT32_C(5)

#define ROUP_OMP_THREADSET_OMP_POOL UINT32_C(1)
#define ROUP_OMP_THREADSET_OMP_TEAM UINT32_C(2)
#define ROUP_OMP_MEMSCOPE_ALL UINT32_C(1)
#define ROUP_OMP_MEMSCOPE_CGROUP UINT32_C(2)
#define ROUP_OMP_MEMSCOPE_DEVICE UINT32_C(3)

#define ROUP_OMP_PROC_BIND_CLOSE UINT32_C(1)
#define ROUP_OMP_PROC_BIND_SPREAD UINT32_C(2)
#define ROUP_OMP_PROC_BIND_PRIMARY UINT32_C(3)
#define ROUP_OMP_BIND_TEAMS UINT32_C(1)
#define ROUP_OMP_BIND_PARALLEL UINT32_C(2)
#define ROUP_OMP_BIND_THREAD UINT32_C(3)
#define ROUP_OMP_DEVICE_ANCESTOR UINT32_C(1)
#define ROUP_OMP_DEVICE_NUM UINT32_C(2)
#define ROUP_OMP_DEVICE_TYPE_HOST UINT32_C(1)
#define ROUP_OMP_DEVICE_TYPE_NOHOST UINT32_C(2)
#define ROUP_OMP_DEVICE_TYPE_ANY UINT32_C(3)
#define ROUP_OMP_AT_COMPILATION UINT32_C(1)
#define ROUP_OMP_AT_EXECUTION UINT32_C(2)
#define ROUP_OMP_SEVERITY_FATAL UINT32_C(1)
#define ROUP_OMP_SEVERITY_WARNING UINT32_C(2)
#define ROUP_OMP_MEMORY_ORDER_SEQ_CST UINT32_C(1)
#define ROUP_OMP_MEMORY_ORDER_ACQ_REL UINT32_C(2)
#define ROUP_OMP_MEMORY_ORDER_RELEASE UINT32_C(3)
#define ROUP_OMP_MEMORY_ORDER_ACQUIRE UINT32_C(4)
#define ROUP_OMP_MEMORY_ORDER_RELAXED UINT32_C(5)
#define ROUP_OMP_ATOMIC_READ UINT32_C(1)
#define ROUP_OMP_ATOMIC_WRITE UINT32_C(2)
#define ROUP_OMP_ATOMIC_UPDATE UINT32_C(3)
#define ROUP_OMP_EXTENDED_ATOMIC_CAPTURE UINT32_C(1)
#define ROUP_OMP_EXTENDED_ATOMIC_COMPARE UINT32_C(2)
#define ROUP_OMP_EXTENDED_ATOMIC_WEAK UINT32_C(3)
#define ROUP_OMP_ORDER_REPRODUCIBLE UINT32_C(1)
#define ROUP_OMP_ORDER_UNCONSTRAINED UINT32_C(2)
#define ROUP_OMP_ORDER_CONCURRENT UINT32_C(1)
#define ROUP_OMP_GRAINSIZE_STRICT UINT32_C(1)
#define ROUP_OMP_NUM_TASKS_STRICT UINT32_C(1)
#define ROUP_OMP_DEPOBJ_UPDATE_IN UINT32_C(1)
#define ROUP_OMP_DEPOBJ_UPDATE_OUT UINT32_C(2)
#define ROUP_OMP_DEPOBJ_UPDATE_INOUT UINT32_C(3)
#define ROUP_OMP_DEPOBJ_UPDATE_INOUTSET UINT32_C(4)
#define ROUP_OMP_DEPOBJ_UPDATE_MUTEXINOUTSET UINT32_C(5)

#define ROUP_ACC_DEFAULT_NONE UINT32_C(1)
#define ROUP_ACC_DEFAULT_PRESENT UINT32_C(2)
#define ROUP_ACC_COPY UINT32_C(1)
#define ROUP_ACC_COPYIN UINT32_C(2)
#define ROUP_ACC_COPYOUT UINT32_C(3)
#define ROUP_ACC_CREATE UINT32_C(1)
#define ROUP_ACC_DATA_ATTACH UINT32_C(1)
#define ROUP_ACC_DATA_DETACH UINT32_C(2)
#define ROUP_ACC_DATA_USE_DEVICE UINT32_C(3)
#define ROUP_ACC_DATA_LINK UINT32_C(4)
#define ROUP_ACC_DATA_DEVICE_RESIDENT UINT32_C(5)
#define ROUP_ACC_DATA_DEVICE UINT32_C(6)
#define ROUP_ACC_DATA_DELETE UINT32_C(7)
#define ROUP_ACC_DATA_MODIFIER_ALWAYS UINT32_C(1)
#define ROUP_ACC_DATA_MODIFIER_ALWAYS_IN UINT32_C(2)
#define ROUP_ACC_DATA_MODIFIER_ALWAYS_OUT UINT32_C(3)
#define ROUP_ACC_DATA_MODIFIER_CAPTURE UINT32_C(4)
#define ROUP_ACC_DATA_MODIFIER_READONLY UINT32_C(5)
#define ROUP_ACC_DATA_MODIFIER_ZERO UINT32_C(6)
#define ROUP_ACC_WORKER_NUM UINT32_C(1)
#define ROUP_ACC_WORKER_EXPRESSION UINT32_C(2)
#define ROUP_ACC_VECTOR_LENGTH UINT32_C(1)
#define ROUP_ACC_VECTOR_EXPRESSION UINT32_C(2)

#define ROUP_CHARACTER_ENCODING_ORDINARY UINT32_C(1)
#define ROUP_CHARACTER_ENCODING_UTF8 UINT32_C(2)
#define ROUP_CHARACTER_ENCODING_UTF16 UINT32_C(3)
#define ROUP_CHARACTER_ENCODING_UTF32 UINT32_C(4)
#define ROUP_CHARACTER_ENCODING_WIDE UINT32_C(5)
#define ROUP_CHARACTER_ENCODING_FORTRAN UINT32_C(6)

#define ROUP_REQUIRE_REVERSE_OFFLOAD UINT32_C(1)
#define ROUP_REQUIRE_UNIFIED_ADDRESS UINT32_C(2)
#define ROUP_REQUIRE_UNIFIED_SHARED_MEMORY UINT32_C(3)
#define ROUP_REQUIRE_DYNAMIC_ALLOCATORS UINT32_C(4)
#define ROUP_REQUIRE_SELF_MAPS UINT32_C(5)
#define ROUP_REQUIRE_DEVICE_SAFESYNC UINT32_C(6)
#define ROUP_REQUIRE_ATOMIC_DEFAULT_MEM_ORDER UINT32_C(7)
#define ROUP_REQUIRE_EXTENSION UINT32_C(8)

#define ROUP_REDUCTION_MODIFIER_TASK UINT32_C(1)
#define ROUP_REDUCTION_MODIFIER_INSCAN UINT32_C(2)
#define ROUP_REDUCTION_MODIFIER_DEFAULT UINT32_C(3)
#define ROUP_REDUCTION_MODIFIER_ORIGINAL UINT32_C(4)

#define ROUP_SELECTOR_ENTRY_DEVICE UINT32_C(1)
#define ROUP_SELECTOR_ENTRY_TARGET_DEVICE UINT32_C(2)
#define ROUP_SELECTOR_ENTRY_IMPLEMENTATION UINT32_C(3)
#define ROUP_SELECTOR_ENTRY_USER UINT32_C(4)
#define ROUP_SELECTOR_ENTRY_CONSTRUCT UINT32_C(5)

#define ROUP_SELECTOR_DEVICE_NAME_LIST UINT32_C(1)
#define ROUP_SELECTOR_DEVICE_NUM UINT32_C(2)
#define ROUP_SELECTOR_DEVICE_UID UINT32_C(3)
#define ROUP_SELECTOR_DEVICE_EXTENSION UINT32_C(4)

#define ROUP_SELECTOR_IMPLEMENTATION_NAME_LIST UINT32_C(1)
#define ROUP_SELECTOR_IMPLEMENTATION_ATOMIC_DEFAULT_MEM_ORDER UINT32_C(2)
#define ROUP_SELECTOR_IMPLEMENTATION_REQUIREMENT UINT32_C(3)
#define ROUP_SELECTOR_IMPLEMENTATION_REQUIRES UINT32_C(4)
#define ROUP_SELECTOR_IMPLEMENTATION_EXTENSION UINT32_C(5)

#define ROUP_SELECTOR_NAME_LIST_KIND UINT32_C(1)
#define ROUP_SELECTOR_NAME_LIST_ISA UINT32_C(2)
#define ROUP_SELECTOR_NAME_LIST_ARCH UINT32_C(3)
#define ROUP_SELECTOR_NAME_LIST_VENDOR UINT32_C(4)
#define ROUP_SELECTOR_NAME_LIST_EXTENSION UINT32_C(5)

#define ROUP_SELECTOR_EXTENSION_TRAIT UINT32_C(1)
#define ROUP_SELECTOR_EXTENSION_PROPERTY_NAME UINT32_C(1)
#define ROUP_SELECTOR_EXTENSION_PROPERTY_CALL UINT32_C(2)
#define ROUP_SELECTOR_EXTENSION_PROPERTY_CONSTANT_INTEGER UINT32_C(3)
#define ROUP_SELECTOR_REQUIREMENT UINT32_C(1)
#define ROUP_SELECTOR_CONSTRUCT UINT32_C(1)

#define ROUP_SELECTOR_TRAIT_IDENTIFIER UINT32_C(1)
#define ROUP_SELECTOR_TRAIT_STRING_LITERAL UINT32_C(2)
#define ROUP_SELECTOR_TRAIT_PREDEFINED_DEVICE_KIND UINT32_C(3)
#define ROUP_SELECTOR_TRAIT_PREDEFINED_VENDOR UINT32_C(4)

#define ROUP_OMP_DEVICE_KIND_HOST UINT32_C(1)
#define ROUP_OMP_DEVICE_KIND_NOHOST UINT32_C(2)
#define ROUP_OMP_DEVICE_KIND_ANY UINT32_C(3)
#define ROUP_OMP_DEVICE_KIND_CPU UINT32_C(4)
#define ROUP_OMP_DEVICE_KIND_GPU UINT32_C(5)
#define ROUP_OMP_DEVICE_KIND_FPGA UINT32_C(6)

#define ROUP_OMP_VENDOR_AMD UINT32_C(1)
#define ROUP_OMP_VENDOR_ARM UINT32_C(2)
#define ROUP_OMP_VENDOR_BSC UINT32_C(3)
#define ROUP_OMP_VENDOR_CRAY UINT32_C(4)
#define ROUP_OMP_VENDOR_FUJITSU UINT32_C(5)
#define ROUP_OMP_VENDOR_GNU UINT32_C(6)
#define ROUP_OMP_VENDOR_IBM UINT32_C(7)
#define ROUP_OMP_VENDOR_INTEL UINT32_C(8)
#define ROUP_OMP_VENDOR_LLVM UINT32_C(9)
#define ROUP_OMP_VENDOR_NVIDIA UINT32_C(10)
#define ROUP_OMP_VENDOR_PGI UINT32_C(11)
#define ROUP_OMP_VENDOR_TI UINT32_C(12)

#define ROUP_OMP_PARAMETER_ALLOCATE_LIST UINT32_C(1)
#define ROUP_OMP_PARAMETER_THREADPRIVATE_LIST UINT32_C(2)
#define ROUP_OMP_PARAMETER_GROUPPRIVATE_LIST UINT32_C(3)
#define ROUP_OMP_PARAMETER_DECLARE_TARGET_LIST UINT32_C(4)
#define ROUP_OMP_PARAMETER_DECLARE_MAPPER UINT32_C(5)
#define ROUP_OMP_PARAMETER_DECLARE_VARIANT UINT32_C(6)
#define ROUP_OMP_PARAMETER_DEPOBJ UINT32_C(7)
#define ROUP_OMP_PARAMETER_CONSTRUCT UINT32_C(8)
#define ROUP_OMP_PARAMETER_CRITICAL_SECTION UINT32_C(9)
#define ROUP_OMP_PARAMETER_FLUSH_LIST UINT32_C(10)
#define ROUP_OMP_PARAMETER_DECLARE_REDUCTION UINT32_C(11)
#define ROUP_OMP_PARAMETER_DECLARE_SIMD UINT32_C(12)
#define ROUP_OMP_PARAMETER_DECLARE_INDUCTION UINT32_C(13)
#define ROUP_OMP_PARAMETER_OMPX UINT32_C(14)

#define ROUP_OMPX_PAYLOAD_IDENTIFIER UINT32_C(1)
#define ROUP_OMPX_PAYLOAD_INVOCATION UINT32_C(2)

#define ROUP_ACC_PARAMETER_CACHE UINT32_C(1)
#define ROUP_ACC_PARAMETER_WAIT UINT32_C(2)
#define ROUP_ACC_PARAMETER_ROUTINE UINT32_C(3)
#define ROUP_ACC_PARAMETER_END UINT32_C(4)

#define ROUP_OMP_DIRECTIVE_ALLOCATE UINT32_C(0)
#define ROUP_OMP_DIRECTIVE_ALLOCATORS UINT32_C(1)
#define ROUP_OMP_DIRECTIVE_ASSUME UINT32_C(2)
#define ROUP_OMP_DIRECTIVE_ASSUMES UINT32_C(3)
#define ROUP_OMP_DIRECTIVE_ATOMIC UINT32_C(4)
#define ROUP_OMP_DIRECTIVE_BARRIER UINT32_C(5)
#define ROUP_OMP_DIRECTIVE_BEGIN_ASSUMES UINT32_C(6)
#define ROUP_OMP_DIRECTIVE_BEGIN_DECLARE_TARGET UINT32_C(7)
#define ROUP_OMP_DIRECTIVE_BEGIN_DECLARE_VARIANT UINT32_C(8)
#define ROUP_OMP_DIRECTIVE_CANCEL UINT32_C(9)
#define ROUP_OMP_DIRECTIVE_CANCELLATION_POINT UINT32_C(10)
#define ROUP_OMP_DIRECTIVE_CRITICAL UINT32_C(11)
#define ROUP_OMP_DIRECTIVE_DECLARE_INDUCTION UINT32_C(12)
#define ROUP_OMP_DIRECTIVE_DECLARE_MAPPER UINT32_C(13)
#define ROUP_OMP_DIRECTIVE_DECLARE_REDUCTION UINT32_C(14)
#define ROUP_OMP_DIRECTIVE_DECLARE_SIMD UINT32_C(15)
#define ROUP_OMP_DIRECTIVE_DECLARE_TARGET UINT32_C(16)
#define ROUP_OMP_DIRECTIVE_DECLARE_VARIANT UINT32_C(17)
#define ROUP_OMP_DIRECTIVE_DEPOBJ UINT32_C(18)
#define ROUP_OMP_DIRECTIVE_DISPATCH UINT32_C(19)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE UINT32_C(20)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_DO UINT32_C(21)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(22)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_FOR UINT32_C(23)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_FOR_SIMD UINT32_C(24)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_LOOP UINT32_C(25)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_PARALLEL_LOOP_SIMD UINT32_C(26)
#define ROUP_OMP_DIRECTIVE_DISTRIBUTE_SIMD UINT32_C(27)
#define ROUP_OMP_DIRECTIVE_DO UINT32_C(28)
#define ROUP_OMP_DIRECTIVE_DO_SIMD UINT32_C(29)
#define ROUP_OMP_DIRECTIVE_END_ASSUME UINT32_C(30)
#define ROUP_OMP_DIRECTIVE_END_ASSUMES UINT32_C(31)
#define ROUP_OMP_DIRECTIVE_END_ALLOCATORS UINT32_C(32)
#define ROUP_OMP_DIRECTIVE_END_DECLARE_TARGET UINT32_C(33)
#define ROUP_OMP_DIRECTIVE_END_DECLARE_VARIANT UINT32_C(34)
#define ROUP_OMP_DIRECTIVE_END_DISPATCH UINT32_C(35)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL UINT32_C(36)
#define ROUP_OMP_DIRECTIVE_END_DO UINT32_C(37)
#define ROUP_OMP_DIRECTIVE_END_SIMD UINT32_C(38)
#define ROUP_OMP_DIRECTIVE_END_SECTIONS UINT32_C(39)
#define ROUP_OMP_DIRECTIVE_END_SINGLE UINT32_C(40)
#define ROUP_OMP_DIRECTIVE_END_WORKSHARE UINT32_C(41)
#define ROUP_OMP_DIRECTIVE_END_ORDERED UINT32_C(42)
#define ROUP_OMP_DIRECTIVE_END_LOOP UINT32_C(43)
#define ROUP_OMP_DIRECTIVE_END_DISTRIBUTE UINT32_C(44)
#define ROUP_OMP_DIRECTIVE_END_TEAMS UINT32_C(45)
#define ROUP_OMP_DIRECTIVE_END_TASKLOOP UINT32_C(46)
#define ROUP_OMP_DIRECTIVE_END_TASK UINT32_C(47)
#define ROUP_OMP_DIRECTIVE_END_TASKGROUP UINT32_C(48)
#define ROUP_OMP_DIRECTIVE_END_MASTER UINT32_C(49)
#define ROUP_OMP_DIRECTIVE_END_MASKED UINT32_C(50)
#define ROUP_OMP_DIRECTIVE_END_UNROLL UINT32_C(51)
#define ROUP_OMP_DIRECTIVE_END_CRITICAL UINT32_C(52)
#define ROUP_OMP_DIRECTIVE_END_ATOMIC UINT32_C(53)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_DO UINT32_C(54)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_SECTIONS UINT32_C(55)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_WORKSHARE UINT32_C(56)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER UINT32_C(57)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_SINGLE UINT32_C(58)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER_TASKLOOP UINT32_C(59)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASTER_TASKLOOP_SIMD UINT32_C(60)
#define ROUP_OMP_DIRECTIVE_END_DO_SIMD UINT32_C(61)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_DO_SIMD UINT32_C(62)
#define ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_SIMD UINT32_C(63)
#define ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_PARALLEL_DO UINT32_C(64)
#define ROUP_OMP_DIRECTIVE_END_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(65)
#define ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL UINT32_C(66)
#define ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_DO UINT32_C(67)
#define ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_DO_SIMD UINT32_C(68)
#define ROUP_OMP_DIRECTIVE_END_TARGET_PARALLEL_LOOP UINT32_C(69)
#define ROUP_OMP_DIRECTIVE_END_TARGET_SIMD UINT32_C(70)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS UINT32_C(71)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE UINT32_C(72)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO UINT32_C(73)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(74)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_DISTRIBUTE_SIMD UINT32_C(75)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_LOOP UINT32_C(76)
#define ROUP_OMP_DIRECTIVE_END_TARGET_TEAMS_WORKDISTRIBUTE UINT32_C(77)
#define ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE UINT32_C(78)
#define ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_PARALLEL_DO UINT32_C(79)
#define ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(80)
#define ROUP_OMP_DIRECTIVE_END_TEAMS_DISTRIBUTE_SIMD UINT32_C(81)
#define ROUP_OMP_DIRECTIVE_END_TEAMS_LOOP UINT32_C(82)
#define ROUP_OMP_DIRECTIVE_END_TASKLOOP_SIMD UINT32_C(83)
#define ROUP_OMP_DIRECTIVE_END_MASTER_TASKLOOP UINT32_C(84)
#define ROUP_OMP_DIRECTIVE_END_MASTER_TASKLOOP_SIMD UINT32_C(85)
#define ROUP_OMP_DIRECTIVE_END_MASKED_TASKLOOP UINT32_C(86)
#define ROUP_OMP_DIRECTIVE_END_MASKED_TASKLOOP_SIMD UINT32_C(87)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED UINT32_C(88)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED_TASKLOOP UINT32_C(89)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_MASKED_TASKLOOP_SIMD UINT32_C(90)
#define ROUP_OMP_DIRECTIVE_END_PARALLEL_LOOP UINT32_C(91)
#define ROUP_OMP_DIRECTIVE_END_TARGET_LOOP UINT32_C(92)
#define ROUP_OMP_DIRECTIVE_END_TILE UINT32_C(93)
#define ROUP_OMP_DIRECTIVE_ERROR UINT32_C(94)
#define ROUP_OMP_DIRECTIVE_FLUSH UINT32_C(95)
#define ROUP_OMP_DIRECTIVE_FUSE UINT32_C(96)
#define ROUP_OMP_DIRECTIVE_GROUPPRIVATE UINT32_C(97)
#define ROUP_OMP_DIRECTIVE_FOR UINT32_C(98)
#define ROUP_OMP_DIRECTIVE_FOR_SIMD UINT32_C(99)
#define ROUP_OMP_DIRECTIVE_INTERCHANGE UINT32_C(100)
#define ROUP_OMP_DIRECTIVE_INTEROP UINT32_C(101)
#define ROUP_OMP_DIRECTIVE_LOOP UINT32_C(102)
#define ROUP_OMP_DIRECTIVE_REVERSE UINT32_C(103)
#define ROUP_OMP_DIRECTIVE_MASKED UINT32_C(104)
#define ROUP_OMP_DIRECTIVE_MASKED_TASKLOOP UINT32_C(105)
#define ROUP_OMP_DIRECTIVE_MASKED_TASKLOOP_SIMD UINT32_C(106)
#define ROUP_OMP_DIRECTIVE_MASTER UINT32_C(107)
#define ROUP_OMP_DIRECTIVE_MASTER_TASKLOOP UINT32_C(108)
#define ROUP_OMP_DIRECTIVE_MASTER_TASKLOOP_SIMD UINT32_C(109)
#define ROUP_OMP_DIRECTIVE_METADIRECTIVE UINT32_C(110)
#define ROUP_OMP_DIRECTIVE_BEGIN_METADIRECTIVE UINT32_C(111)
#define ROUP_OMP_DIRECTIVE_END_METADIRECTIVE UINT32_C(112)
#define ROUP_OMP_DIRECTIVE_NOTHING UINT32_C(113)
#define ROUP_OMP_DIRECTIVE_ORDERED UINT32_C(114)
#define ROUP_OMP_DIRECTIVE_PARALLEL UINT32_C(115)
#define ROUP_OMP_DIRECTIVE_PARALLEL_DO UINT32_C(116)
#define ROUP_OMP_DIRECTIVE_PARALLEL_DO_SIMD UINT32_C(117)
#define ROUP_OMP_DIRECTIVE_PARALLEL_FOR UINT32_C(118)
#define ROUP_OMP_DIRECTIVE_PARALLEL_FOR_SIMD UINT32_C(119)
#define ROUP_OMP_DIRECTIVE_PARALLEL_LOOP UINT32_C(120)
#define ROUP_OMP_DIRECTIVE_PARALLEL_LOOP_SIMD UINT32_C(121)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASKED UINT32_C(122)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASKED_TASKLOOP UINT32_C(123)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASKED_TASKLOOP_SIMD UINT32_C(124)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASTER UINT32_C(125)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASTER_TASKLOOP UINT32_C(126)
#define ROUP_OMP_DIRECTIVE_PARALLEL_MASTER_TASKLOOP_SIMD UINT32_C(127)
#define ROUP_OMP_DIRECTIVE_PARALLEL_SECTIONS UINT32_C(128)
#define ROUP_OMP_DIRECTIVE_PARALLEL_SINGLE UINT32_C(129)
#define ROUP_OMP_DIRECTIVE_PARALLEL_WORKSHARE UINT32_C(130)
#define ROUP_OMP_DIRECTIVE_REQUIRES UINT32_C(131)
#define ROUP_OMP_DIRECTIVE_SCOPE UINT32_C(132)
#define ROUP_OMP_DIRECTIVE_END_SCOPE UINT32_C(133)
#define ROUP_OMP_DIRECTIVE_SCAN UINT32_C(134)
#define ROUP_OMP_DIRECTIVE_SECTION UINT32_C(135)
#define ROUP_OMP_DIRECTIVE_SECTIONS UINT32_C(136)
#define ROUP_OMP_DIRECTIVE_SIMD UINT32_C(137)
#define ROUP_OMP_DIRECTIVE_SINGLE UINT32_C(138)
#define ROUP_OMP_DIRECTIVE_SPLIT UINT32_C(139)
#define ROUP_OMP_DIRECTIVE_STRIPE UINT32_C(140)
#define ROUP_OMP_DIRECTIVE_TARGET UINT32_C(141)
#define ROUP_OMP_DIRECTIVE_TARGET_DATA UINT32_C(142)
#define ROUP_OMP_DIRECTIVE_TARGET_ENTER_DATA UINT32_C(143)
#define ROUP_OMP_DIRECTIVE_TARGET_EXIT_DATA UINT32_C(144)
#define ROUP_OMP_DIRECTIVE_END_TARGET UINT32_C(145)
#define ROUP_OMP_DIRECTIVE_END_TARGET_DATA UINT32_C(146)
#define ROUP_OMP_DIRECTIVE_TARGET_LOOP UINT32_C(147)
#define ROUP_OMP_DIRECTIVE_TARGET_LOOP_SIMD UINT32_C(148)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL UINT32_C(149)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_DO UINT32_C(150)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_DO_SIMD UINT32_C(151)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_FOR UINT32_C(152)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_FOR_SIMD UINT32_C(153)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_LOOP UINT32_C(154)
#define ROUP_OMP_DIRECTIVE_TARGET_PARALLEL_LOOP_SIMD UINT32_C(155)
#define ROUP_OMP_DIRECTIVE_TARGET_SIMD UINT32_C(156)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS UINT32_C(157)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE UINT32_C(158)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO UINT32_C(159)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(160)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR UINT32_C(161)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD UINT32_C(162)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP UINT32_C(163)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD UINT32_C(164)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_DISTRIBUTE_SIMD UINT32_C(165)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_LOOP UINT32_C(166)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_LOOP_SIMD UINT32_C(167)
#define ROUP_OMP_DIRECTIVE_TARGET_TEAMS_WORKDISTRIBUTE UINT32_C(168)
#define ROUP_OMP_DIRECTIVE_TARGET_UPDATE UINT32_C(169)
#define ROUP_OMP_DIRECTIVE_TASK UINT32_C(170)
#define ROUP_OMP_DIRECTIVE_TASK_ITERATION UINT32_C(171)
#define ROUP_OMP_DIRECTIVE_TASKGROUP UINT32_C(172)
#define ROUP_OMP_DIRECTIVE_TASKGRAPH UINT32_C(173)
#define ROUP_OMP_DIRECTIVE_TASKLOOP UINT32_C(174)
#define ROUP_OMP_DIRECTIVE_TASKLOOP_SIMD UINT32_C(175)
#define ROUP_OMP_DIRECTIVE_TASKWAIT UINT32_C(176)
#define ROUP_OMP_DIRECTIVE_TASKYIELD UINT32_C(177)
#define ROUP_OMP_DIRECTIVE_TEAMS UINT32_C(178)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE UINT32_C(179)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_DO UINT32_C(180)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_DO_SIMD UINT32_C(181)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_FOR UINT32_C(182)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_FOR_SIMD UINT32_C(183)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_LOOP UINT32_C(184)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_PARALLEL_LOOP_SIMD UINT32_C(185)
#define ROUP_OMP_DIRECTIVE_TEAMS_DISTRIBUTE_SIMD UINT32_C(186)
#define ROUP_OMP_DIRECTIVE_TEAMS_LOOP UINT32_C(187)
#define ROUP_OMP_DIRECTIVE_TEAMS_LOOP_SIMD UINT32_C(188)
#define ROUP_OMP_DIRECTIVE_THREADPRIVATE UINT32_C(189)
#define ROUP_OMP_DIRECTIVE_TILE UINT32_C(190)
#define ROUP_OMP_DIRECTIVE_UNROLL UINT32_C(191)
#define ROUP_OMP_DIRECTIVE_WORKDISTRIBUTE UINT32_C(192)
#define ROUP_OMP_DIRECTIVE_WORKSHARE UINT32_C(193)
#define ROUP_OMP_DIRECTIVE_END_SECTION UINT32_C(194)
#define ROUP_OMP_DIRECTIVE_OMPX UINT32_C(195)

#define ROUP_OMP_CLAUSE_ABSENT UINT32_C(0)
#define ROUP_OMP_CLAUSE_ACQ_REL UINT32_C(1)
#define ROUP_OMP_CLAUSE_ACQUIRE UINT32_C(2)
#define ROUP_OMP_CLAUSE_ADJUST_ARGS UINT32_C(3)
#define ROUP_OMP_CLAUSE_AFFINITY UINT32_C(4)
#define ROUP_OMP_CLAUSE_ALIGN UINT32_C(5)
#define ROUP_OMP_CLAUSE_ALIGNED UINT32_C(6)
#define ROUP_OMP_CLAUSE_ALLOCATE UINT32_C(7)
#define ROUP_OMP_CLAUSE_ALLOCATOR UINT32_C(8)
#define ROUP_OMP_CLAUSE_APPEND_ARGS UINT32_C(9)
#define ROUP_OMP_CLAUSE_APPLY UINT32_C(10)
#define ROUP_OMP_CLAUSE_AT UINT32_C(11)
#define ROUP_OMP_CLAUSE_ATOMIC_DEFAULT_MEM_ORDER UINT32_C(12)
#define ROUP_OMP_CLAUSE_BIND UINT32_C(13)
#define ROUP_OMP_CLAUSE_CAPTURE UINT32_C(14)
#define ROUP_OMP_CLAUSE_COLLAPSE UINT32_C(15)
#define ROUP_OMP_CLAUSE_COLLECTOR UINT32_C(16)
#define ROUP_OMP_CLAUSE_COMBINER UINT32_C(17)
#define ROUP_OMP_CLAUSE_COMPARE UINT32_C(18)
#define ROUP_OMP_CLAUSE_CONTAINS UINT32_C(19)
#define ROUP_OMP_CLAUSE_COPY_IN UINT32_C(20)
#define ROUP_OMP_CLAUSE_COPYPRIVATE UINT32_C(21)
#define ROUP_OMP_CLAUSE_PARALLEL UINT32_C(22)
#define ROUP_OMP_CLAUSE_SECTIONS UINT32_C(23)
#define ROUP_OMP_CLAUSE_FOR UINT32_C(24)
#define ROUP_OMP_CLAUSE_DO UINT32_C(25)
#define ROUP_OMP_CLAUSE_TASKGROUP UINT32_C(26)
#define ROUP_OMP_CLAUSE_COUNTS UINT32_C(27)
#define ROUP_OMP_CLAUSE_DEFAULT UINT32_C(28)
#define ROUP_OMP_CLAUSE_DEFAULTMAP UINT32_C(29)
#define ROUP_OMP_CLAUSE_DEPEND UINT32_C(30)
#define ROUP_OMP_CLAUSE_DEPOBJ_UPDATE UINT32_C(31)
#define ROUP_OMP_CLAUSE_DESTROY UINT32_C(32)
#define ROUP_OMP_CLAUSE_DETACH UINT32_C(33)
#define ROUP_OMP_CLAUSE_DEVICE UINT32_C(34)
#define ROUP_OMP_CLAUSE_DEVICE_SAFESYNC UINT32_C(35)
#define ROUP_OMP_CLAUSE_DEVICE_TYPE UINT32_C(36)
#define ROUP_OMP_CLAUSE_DIST_SCHEDULE UINT32_C(37)
#define ROUP_OMP_CLAUSE_DOACROSS UINT32_C(38)
#define ROUP_OMP_CLAUSE_DYNAMIC_ALLOCATORS UINT32_C(39)
#define ROUP_OMP_CLAUSE_EXT_IMPLEMENTATION_DEFINED_REQUIREMENT UINT32_C(40)
#define ROUP_OMP_CLAUSE_ENTER UINT32_C(41)
#define ROUP_OMP_CLAUSE_EXCLUSIVE UINT32_C(42)
#define ROUP_OMP_CLAUSE_FAIL UINT32_C(43)
#define ROUP_OMP_CLAUSE_FINAL UINT32_C(44)
#define ROUP_OMP_CLAUSE_FILTER UINT32_C(45)
#define ROUP_OMP_CLAUSE_FIRSTPRIVATE UINT32_C(46)
#define ROUP_OMP_CLAUSE_FROM UINT32_C(47)
#define ROUP_OMP_CLAUSE_FULL UINT32_C(48)
#define ROUP_OMP_CLAUSE_GRAINSIZE UINT32_C(49)
#define ROUP_OMP_CLAUSE_GRAPH_ID UINT32_C(50)
#define ROUP_OMP_CLAUSE_GRAPH_RESET UINT32_C(51)
#define ROUP_OMP_CLAUSE_HAS_DEVICE_ADDR UINT32_C(52)
#define ROUP_OMP_CLAUSE_HINT UINT32_C(53)
#define ROUP_OMP_CLAUSE_HOLDS UINT32_C(54)
#define ROUP_OMP_CLAUSE_IF UINT32_C(55)
#define ROUP_OMP_CLAUSE_IN_REDUCTION UINT32_C(56)
#define ROUP_OMP_CLAUSE_INDUCTION UINT32_C(57)
#define ROUP_OMP_CLAUSE_INDUCTOR UINT32_C(58)
#define ROUP_OMP_CLAUSE_INBRANCH UINT32_C(59)
#define ROUP_OMP_CLAUSE_INCLUSIVE UINT32_C(60)
#define ROUP_OMP_CLAUSE_INIT UINT32_C(61)
#define ROUP_OMP_CLAUSE_INIT_COMPLETE UINT32_C(62)
#define ROUP_OMP_CLAUSE_INITIALIZER UINT32_C(63)
#define ROUP_OMP_CLAUSE_INDIRECT UINT32_C(64)
#define ROUP_OMP_CLAUSE_IS_DEVICE_PTR UINT32_C(65)
#define ROUP_OMP_CLAUSE_LASTPRIVATE UINT32_C(66)
#define ROUP_OMP_CLAUSE_LINEAR UINT32_C(67)
#define ROUP_OMP_CLAUSE_LINK UINT32_C(68)
#define ROUP_OMP_CLAUSE_LOCAL UINT32_C(69)
#define ROUP_OMP_CLAUSE_LOOPRANGE UINT32_C(70)
#define ROUP_OMP_CLAUSE_MAP UINT32_C(71)
#define ROUP_OMP_CLAUSE_MATCH UINT32_C(72)
#define ROUP_OMP_CLAUSE_MESSAGE UINT32_C(73)
#define ROUP_OMP_CLAUSE_MEMSCOPE UINT32_C(74)
#define ROUP_OMP_CLAUSE_MERGEABLE UINT32_C(75)
#define ROUP_OMP_CLAUSE_NOCONTEXT UINT32_C(76)
#define ROUP_OMP_CLAUSE_NOGROUP UINT32_C(77)
#define ROUP_OMP_CLAUSE_NO_OPENMP UINT32_C(78)
#define ROUP_OMP_CLAUSE_NO_OPENMP_CONSTRUCTS UINT32_C(79)
#define ROUP_OMP_CLAUSE_NO_OPENMP_ROUTINES UINT32_C(80)
#define ROUP_OMP_CLAUSE_NO_PARALLELISM UINT32_C(81)
#define ROUP_OMP_CLAUSE_NONTEMPORAL UINT32_C(82)
#define ROUP_OMP_CLAUSE_NOTINBRANCH UINT32_C(83)
#define ROUP_OMP_CLAUSE_NOVARIANTS UINT32_C(84)
#define ROUP_OMP_CLAUSE_INTEROP UINT32_C(85)
#define ROUP_OMP_CLAUSE_NOWAIT UINT32_C(86)
#define ROUP_OMP_CLAUSE_NUM_TASKS UINT32_C(87)
#define ROUP_OMP_CLAUSE_NUM_TEAMS UINT32_C(88)
#define ROUP_OMP_CLAUSE_NUM_THREADS UINT32_C(89)
#define ROUP_OMP_CLAUSE_ORDER UINT32_C(90)
#define ROUP_OMP_CLAUSE_ORDERED UINT32_C(91)
#define ROUP_OMP_CLAUSE_OTHERWISE UINT32_C(92)
#define ROUP_OMP_CLAUSE_PARTIAL UINT32_C(93)
#define ROUP_OMP_CLAUSE_PERMUTATION UINT32_C(94)
#define ROUP_OMP_CLAUSE_PRIORITY UINT32_C(95)
#define ROUP_OMP_CLAUSE_PRIVATE UINT32_C(96)
#define ROUP_OMP_CLAUSE_PROC_BIND UINT32_C(97)
#define ROUP_OMP_CLAUSE_READ UINT32_C(98)
#define ROUP_OMP_CLAUSE_REDUCTION UINT32_C(99)
#define ROUP_OMP_CLAUSE_RELEASE UINT32_C(100)
#define ROUP_OMP_CLAUSE_RELAXED UINT32_C(101)
#define ROUP_OMP_CLAUSE_REPLAYABLE UINT32_C(102)
#define ROUP_OMP_CLAUSE_REVERSE_OFFLOAD UINT32_C(103)
#define ROUP_OMP_CLAUSE_SAFELEN UINT32_C(104)
#define ROUP_OMP_CLAUSE_SAFESYNC UINT32_C(105)
#define ROUP_OMP_CLAUSE_SCHEDULE UINT32_C(106)
#define ROUP_OMP_CLAUSE_SELF_MAPS UINT32_C(107)
#define ROUP_OMP_CLAUSE_SEQ_CST UINT32_C(108)
#define ROUP_OMP_CLAUSE_SEVERITY UINT32_C(109)
#define ROUP_OMP_CLAUSE_SHARED UINT32_C(110)
#define ROUP_OMP_CLAUSE_SIMD UINT32_C(111)
#define ROUP_OMP_CLAUSE_SIMDLEN UINT32_C(112)
#define ROUP_OMP_CLAUSE_SIZES UINT32_C(113)
#define ROUP_OMP_CLAUSE_TASK_REDUCTION UINT32_C(114)
#define ROUP_OMP_CLAUSE_THREAD_LIMIT UINT32_C(115)
#define ROUP_OMP_CLAUSE_THREADS UINT32_C(116)
#define ROUP_OMP_CLAUSE_THREADSET UINT32_C(117)
#define ROUP_OMP_CLAUSE_TO UINT32_C(118)
#define ROUP_OMP_CLAUSE_TRANSPARENT UINT32_C(119)
#define ROUP_OMP_CLAUSE_UNIFIED_ADDRESS UINT32_C(120)
#define ROUP_OMP_CLAUSE_UNIFIED_SHARED_MEMORY UINT32_C(121)
#define ROUP_OMP_CLAUSE_UNIFORM UINT32_C(122)
#define ROUP_OMP_CLAUSE_UNTIED UINT32_C(123)
#define ROUP_OMP_CLAUSE_UPDATE UINT32_C(124)
#define ROUP_OMP_CLAUSE_USE UINT32_C(125)
#define ROUP_OMP_CLAUSE_USE_DEVICE_ADDR UINT32_C(126)
#define ROUP_OMP_CLAUSE_USE_DEVICE_PTR UINT32_C(127)
#define ROUP_OMP_CLAUSE_USES_ALLOCATORS UINT32_C(128)
#define ROUP_OMP_CLAUSE_WEAK UINT32_C(129)
#define ROUP_OMP_CLAUSE_WHEN UINT32_C(130)
#define ROUP_OMP_CLAUSE_WRITE UINT32_C(131)

#define ROUP_ACC_DIRECTIVE_ATOMIC UINT32_C(0)
#define ROUP_ACC_DIRECTIVE_CACHE UINT32_C(1)
#define ROUP_ACC_DIRECTIVE_DATA UINT32_C(2)
#define ROUP_ACC_DIRECTIVE_DECLARE UINT32_C(3)
#define ROUP_ACC_DIRECTIVE_END UINT32_C(4)
#define ROUP_ACC_DIRECTIVE_ENTER_DATA UINT32_C(5)
#define ROUP_ACC_DIRECTIVE_EXIT_DATA UINT32_C(6)
#define ROUP_ACC_DIRECTIVE_HOST_DATA UINT32_C(7)
#define ROUP_ACC_DIRECTIVE_INIT UINT32_C(8)
#define ROUP_ACC_DIRECTIVE_KERNELS UINT32_C(9)
#define ROUP_ACC_DIRECTIVE_KERNELS_LOOP UINT32_C(10)
#define ROUP_ACC_DIRECTIVE_LOOP UINT32_C(11)
#define ROUP_ACC_DIRECTIVE_PARALLEL UINT32_C(12)
#define ROUP_ACC_DIRECTIVE_PARALLEL_LOOP UINT32_C(13)
#define ROUP_ACC_DIRECTIVE_ROUTINE UINT32_C(14)
#define ROUP_ACC_DIRECTIVE_SERIAL UINT32_C(15)
#define ROUP_ACC_DIRECTIVE_SERIAL_LOOP UINT32_C(16)
#define ROUP_ACC_DIRECTIVE_SET UINT32_C(17)
#define ROUP_ACC_DIRECTIVE_SHUTDOWN UINT32_C(18)
#define ROUP_ACC_DIRECTIVE_UPDATE UINT32_C(19)
#define ROUP_ACC_DIRECTIVE_WAIT UINT32_C(20)

#define ROUP_ACC_CLAUSE_ASYNC UINT32_C(0)
#define ROUP_ACC_CLAUSE_ATTACH UINT32_C(1)
#define ROUP_ACC_CLAUSE_AUTO UINT32_C(2)
#define ROUP_ACC_CLAUSE_BIND UINT32_C(3)
#define ROUP_ACC_CLAUSE_CAPTURE UINT32_C(4)
#define ROUP_ACC_CLAUSE_COLLAPSE UINT32_C(5)
#define ROUP_ACC_CLAUSE_COPY UINT32_C(6)
#define ROUP_ACC_CLAUSE_COPY_IN UINT32_C(7)
#define ROUP_ACC_CLAUSE_COPY_OUT UINT32_C(8)
#define ROUP_ACC_CLAUSE_CREATE UINT32_C(9)
#define ROUP_ACC_CLAUSE_DEFAULT UINT32_C(10)
#define ROUP_ACC_CLAUSE_DEFAULT_ASYNC UINT32_C(11)
#define ROUP_ACC_CLAUSE_DELETE UINT32_C(12)
#define ROUP_ACC_CLAUSE_DETACH UINT32_C(13)
#define ROUP_ACC_CLAUSE_DEVICE UINT32_C(14)
#define ROUP_ACC_CLAUSE_DEVICE_NUM UINT32_C(15)
#define ROUP_ACC_CLAUSE_DEVICE_RESIDENT UINT32_C(16)
#define ROUP_ACC_CLAUSE_DEVICE_TYPE UINT32_C(17)
#define ROUP_ACC_CLAUSE_DEVICE_PTR UINT32_C(18)
#define ROUP_ACC_CLAUSE_FINALIZE UINT32_C(19)
#define ROUP_ACC_CLAUSE_FIRSTPRIVATE UINT32_C(20)
#define ROUP_ACC_CLAUSE_GANG UINT32_C(21)
#define ROUP_ACC_CLAUSE_IF UINT32_C(22)
#define ROUP_ACC_CLAUSE_IF_PRESENT UINT32_C(23)
#define ROUP_ACC_CLAUSE_INDEPENDENT UINT32_C(24)
#define ROUP_ACC_CLAUSE_INDIRECT UINT32_C(25)
#define ROUP_ACC_CLAUSE_LINK UINT32_C(26)
#define ROUP_ACC_CLAUSE_NO_CREATE UINT32_C(27)
#define ROUP_ACC_CLAUSE_NO_HOST UINT32_C(28)
#define ROUP_ACC_CLAUSE_NUM_GANGS UINT32_C(29)
#define ROUP_ACC_CLAUSE_NUM_WORKERS UINT32_C(30)
#define ROUP_ACC_CLAUSE_PRESENT UINT32_C(31)
#define ROUP_ACC_CLAUSE_PRIVATE UINT32_C(32)
#define ROUP_ACC_CLAUSE_REDUCTION UINT32_C(33)
#define ROUP_ACC_CLAUSE_READ UINT32_C(34)
#define ROUP_ACC_CLAUSE_SELF_CLAUSE UINT32_C(35)
#define ROUP_ACC_CLAUSE_SEQ UINT32_C(36)
#define ROUP_ACC_CLAUSE_TILE UINT32_C(37)
#define ROUP_ACC_CLAUSE_UPDATE UINT32_C(38)
#define ROUP_ACC_CLAUSE_USE_DEVICE UINT32_C(39)
#define ROUP_ACC_CLAUSE_VECTOR UINT32_C(40)
#define ROUP_ACC_CLAUSE_VECTOR_LENGTH UINT32_C(41)
#define ROUP_ACC_CLAUSE_WAIT UINT32_C(42)
#define ROUP_ACC_CLAUSE_WORKER UINT32_C(43)
#define ROUP_ACC_CLAUSE_WRITE UINT32_C(44)


typedef uint32_t RoupStatus;

/*
 * Handles are padding-free opaque identities in one server-owned object
 * arena. Copy both words unchanged; the stored object kind is validated on
 * every operation and is never supplied by the caller.
 */
typedef struct RoupParserHandle {
    uint64_t generation;
    uint64_t index;
} RoupParserHandle;

typedef struct RoupDirectiveHandle {
    uint64_t generation;
    uint64_t index;
} RoupDirectiveHandle;

typedef struct RoupErrorHandle {
    uint64_t generation;
    uint64_t index;
} RoupErrorHandle;

typedef struct RoupNodeHandle {
    uint64_t generation;
    uint64_t index;
} RoupNodeHandle;

typedef struct RoupParserOptions {
    uint32_t abi_version;
    uint32_t struct_size;
    uint32_t dialect;
    uint32_t version_policy;
    uint32_t version;
    uint32_t host_language;
    uint32_t host_standard;
    uint32_t source_form;
    uint32_t flags;
    uint32_t reserved[3];
} RoupParserOptions;

typedef struct RoupSpan {
    size_t start_byte;
    size_t end_byte;
    size_t start_line;
    size_t start_column;
    size_t end_line;
    size_t end_column;
} RoupSpan;

typedef struct RoupClauseKind {
    uint32_t dialect;
    uint32_t ordinal;
} RoupClauseKind;

typedef struct RoupDirectiveKind {
    uint32_t dialect;
    uint32_t ordinal;
} RoupDirectiveKind;

typedef struct RoupParameterKind {
    uint32_t dialect;
    uint32_t variant;
} RoupParameterKind;

typedef struct RoupNodeKind {
    uint32_t family;
    uint32_t variant;
} RoupNodeKind;

typedef struct RoupFieldInfo {
    uint32_t id;
    uint32_t value_kind;
    size_t count;
} RoupFieldInfo;

/*
 * Every fallible call returns an explicit status. On failure, error is an
 * active typed handle that must be inspected and released. Value fields are
 * inactive on failure and are never the error signal.
 */
typedef struct RoupCallResult {
    RoupStatus status;
    uint32_t reserved;
    RoupErrorHandle error;
} RoupCallResult;

#define ROUP_DECLARE_RESULT(name, value_type) \
    typedef struct name {                       \
        RoupCallResult result;                  \
        value_type value;                       \
    } name

typedef struct RoupU32Result {
    RoupCallResult result;
    uint32_t value;
    uint32_t reserved;
} RoupU32Result;
ROUP_DECLARE_RESULT(RoupU64Result, uint64_t);
ROUP_DECLARE_RESULT(RoupSizeResult, size_t);
ROUP_DECLARE_RESULT(RoupSpanResult, RoupSpan);
ROUP_DECLARE_RESULT(RoupClauseKindResult, RoupClauseKind);
ROUP_DECLARE_RESULT(RoupDirectiveKindResult, RoupDirectiveKind);
ROUP_DECLARE_RESULT(RoupParameterKindResult, RoupParameterKind);
ROUP_DECLARE_RESULT(RoupNodeKindResult, RoupNodeKind);
ROUP_DECLARE_RESULT(RoupFieldInfoResult, RoupFieldInfo);
ROUP_DECLARE_RESULT(RoupParserResult, RoupParserHandle);
ROUP_DECLARE_RESULT(RoupDirectiveResult, RoupDirectiveHandle);
ROUP_DECLARE_RESULT(RoupNodeResult, RoupNodeHandle);

#undef ROUP_DECLARE_RESULT

RoupU32Result roup_abi_version(void);
/*
 * All RoupParserOptions fields are mandatory. Set abi_version to
 * ROUP_ABI_VERSION, struct_size to sizeof(RoupParserOptions), and every
 * reserved/flags field to zero. Unknown values are hard errors.
 */
RoupParserResult roup_parser_create(RoupParserOptions options);
RoupCallResult roup_parser_release(RoupParserHandle parser);
RoupDirectiveResult roup_parse(RoupParserHandle parser, const uint8_t *input, size_t length);
RoupCallResult roup_directive_release(RoupDirectiveHandle directive);

RoupU32Result roup_directive_dialect(RoupDirectiveHandle directive);
RoupDirectiveKindResult roup_directive_kind(RoupDirectiveHandle directive);
RoupU32Result roup_directive_source_alias(RoupDirectiveHandle directive);
RoupSpanResult roup_directive_span(RoupDirectiveHandle directive);
RoupU32Result roup_directive_has_parameter(RoupDirectiveHandle directive);
RoupParameterKindResult roup_directive_parameter_kind(RoupDirectiveHandle directive);
RoupSizeResult roup_directive_parameter_field_count(RoupDirectiveHandle directive);
RoupFieldInfoResult roup_directive_parameter_field_info(
    RoupDirectiveHandle directive, size_t field_index);
RoupSizeResult roup_directive_parameter_field_name_length(
    RoupDirectiveHandle directive, size_t field_index);
RoupSizeResult roup_directive_parameter_field_name_copy(
    RoupDirectiveHandle directive, size_t field_index, uint8_t *output, size_t capacity);
RoupU32Result roup_directive_parameter_field_u32(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index);
RoupU64Result roup_directive_parameter_field_u64(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index);
RoupU32Result roup_directive_parameter_field_bool(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index);
RoupSizeResult roup_directive_parameter_field_string_length(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index);
RoupSizeResult roup_directive_parameter_field_string_copy(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index,
    uint8_t *output, size_t capacity);
RoupNodeResult roup_directive_parameter_field_node(
    RoupDirectiveHandle directive, size_t field_index, size_t value_index);
RoupSizeResult roup_directive_name_length(RoupDirectiveHandle directive);
RoupSizeResult roup_directive_name_copy(
    RoupDirectiveHandle directive, uint8_t *output, size_t capacity);
RoupSizeResult roup_directive_clause_count(RoupDirectiveHandle directive);
RoupU64Result roup_directive_compatible_versions(RoupDirectiveHandle directive);

RoupClauseKindResult roup_clause_kind(RoupDirectiveHandle directive, size_t clause_index);
RoupSpanResult roup_clause_span(RoupDirectiveHandle directive, size_t clause_index);
RoupSizeResult roup_clause_name_length(RoupDirectiveHandle directive, size_t clause_index);
RoupSizeResult roup_clause_name_copy(
    RoupDirectiveHandle directive, size_t clause_index, uint8_t *output, size_t capacity);
RoupSizeResult roup_clause_field_count(RoupDirectiveHandle directive, size_t clause_index);
/*
 * Field metadata identifies a semantic field and its scalar/list value kind.
 * Lists are read one element at a time; consumers never split a rendered
 * clause. Every *_copy call writes exactly the corresponding *_length bytes,
 * appends no NUL byte, and writes nothing when capacity is insufficient.
 * U32 and U32_LIST elements are queried through the matching *_field_u32
 * function; U64 elements use *_field_u64. Using a getter for a different
 * value kind is a hard error.
 */
RoupFieldInfoResult roup_clause_field_info(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index);
RoupSizeResult roup_clause_field_name_length(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index);
RoupSizeResult roup_clause_field_name_copy(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index,
    uint8_t *output, size_t capacity);
RoupU32Result roup_clause_field_u32(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index,
    size_t value_index);
RoupU64Result roup_clause_field_u64(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index,
    size_t value_index);
RoupU32Result roup_clause_field_bool(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index, size_t value_index);
RoupSizeResult roup_clause_field_string_length(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index, size_t value_index);
RoupSizeResult roup_clause_field_string_copy(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index, size_t value_index,
    uint8_t *output, size_t capacity);
RoupNodeResult roup_clause_field_node(
    RoupDirectiveHandle directive, size_t clause_index, size_t field_index, size_t value_index);

/*
 * NODE and NODE_LIST fields are acquired as independently owned handles. Each
 * acquired handle must be released, and remains valid after its parent handle
 * is released. Nested semantic records use the same recursive field API.
 */
RoupNodeKindResult roup_node_kind(RoupNodeHandle node);
RoupSizeResult roup_node_field_count(RoupNodeHandle node);
RoupFieldInfoResult roup_node_field_info(RoupNodeHandle node, size_t field_index);
RoupSizeResult roup_node_field_name_length(RoupNodeHandle node, size_t field_index);
RoupSizeResult roup_node_field_name_copy(
    RoupNodeHandle node, size_t field_index, uint8_t *output, size_t capacity);
RoupU32Result roup_node_field_u32(
    RoupNodeHandle node, size_t field_index, size_t value_index);
RoupU64Result roup_node_field_u64(
    RoupNodeHandle node, size_t field_index, size_t value_index);
RoupU32Result roup_node_field_bool(
    RoupNodeHandle node, size_t field_index, size_t value_index);
RoupSizeResult roup_node_field_string_length(
    RoupNodeHandle node, size_t field_index, size_t value_index);
RoupSizeResult roup_node_field_string_copy(
    RoupNodeHandle node, size_t field_index, size_t value_index,
    uint8_t *output, size_t capacity);
RoupNodeResult roup_node_field_node(
    RoupNodeHandle node, size_t field_index, size_t value_index);
RoupCallResult roup_node_release(RoupNodeHandle node);

RoupU32Result roup_error_code(RoupErrorHandle error);
RoupSpanResult roup_error_span(RoupErrorHandle error);
RoupSizeResult roup_error_message_length(RoupErrorHandle error);
RoupSizeResult roup_error_message_copy(RoupErrorHandle error, uint8_t *output, size_t capacity);
RoupCallResult roup_error_release(RoupErrorHandle error);

#if defined(__cplusplus)
static_assert(sizeof(RoupParserHandle) == 16, "ROUP handle ABI drift");
static_assert(sizeof(RoupDirectiveHandle) == 16, "ROUP directive handle ABI drift");
static_assert(sizeof(RoupErrorHandle) == 16, "ROUP error handle ABI drift");
static_assert(sizeof(RoupNodeHandle) == 16, "ROUP node handle ABI drift");
static_assert(offsetof(RoupParserHandle, generation) == 0,
              "ROUP handle generation offset drift");
static_assert(offsetof(RoupParserHandle, index) == 8,
              "ROUP handle index offset drift");
static_assert(sizeof(RoupParserOptions) == 48, "ROUP parser option ABI drift");
static_assert(sizeof(RoupCallResult) == 24, "ROUP result ABI drift");
static_assert(sizeof(RoupU32Result) == 32, "ROUP u32 result ABI drift");
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(RoupParserHandle) == 16, "ROUP handle ABI drift");
_Static_assert(sizeof(RoupDirectiveHandle) == 16, "ROUP directive handle ABI drift");
_Static_assert(sizeof(RoupErrorHandle) == 16, "ROUP error handle ABI drift");
_Static_assert(sizeof(RoupNodeHandle) == 16, "ROUP node handle ABI drift");
_Static_assert(offsetof(RoupParserHandle, generation) == 0,
               "ROUP handle generation offset drift");
_Static_assert(offsetof(RoupParserHandle, index) == 8,
               "ROUP handle index offset drift");
_Static_assert(sizeof(RoupParserOptions) == 48, "ROUP parser option ABI drift");
_Static_assert(sizeof(RoupCallResult) == 24, "ROUP result ABI drift");
_Static_assert(sizeof(RoupU32Result) == 32, "ROUP u32 result ABI drift");
#endif

#ifdef __cplusplus
}
#endif

#endif
