name: ROUP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: [1.77, 1.76, 1.75, 1.74, 1.73, 1.72]
        os: [macos-14]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "18"
          arch: arm64
    
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt

      - name: Check rust information
        run: |
          rustc --version
          cargo --version

      - name: Check llvm information
        run: |
          clang --version
          clang++ -v
