name: ROUP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: ["1.80", "1.79", "1.78", "1.77", "1.76", "1.75"]
        os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

# Check supported versions at: https://github.com/KyleMayes/install-llvm-action/blob/master/assets.json
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0.6"
    
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt

      - name: Check rust information
        run: |
          rustc --version
          cargo --version

      - name: Check llvm information
        run: |
          clang --version
          clang++ -v
