name: ROUP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        version: [1.74, 1.73, 1.72, 1.71]
        os: [ubuntu-22.04, windows-2022, macos-13]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
    
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt

      - name: Check rust information
        run: |
          rustc --version
          cargo --version
          clang --version
          clang++ -v
