name: Codex review (after CI success)

# This workflow posts @codex review comment after successful CI on PRs
# Note: Uses workflow_run event to trigger after CI workflow completes
# This file must exist on the main branch to work (GitHub Actions limitation)
#
# REQUIRES: Repository secret 'CODEX_COMMENT_TOKEN' - Personal Access Token with:
#   - Permissions: pull_requests: write (to post comments as user)
#   - Scopes: repo (for private repos) or public_repo (for public repos)
# Without PAT, comments will be posted as github-actions[bot] and Copilot won't respond

on:
  workflow_run:
    workflows: ["CI"]  # Only trigger after the "CI" workflow
    types: [completed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    # Only run when:
    # 1. CI workflow completed successfully
    # 2. It was triggered by a pull_request event (not push to main)
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow run info
        run: |
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow event: ${{ github.event.workflow_run.event }}"
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Pull requests: ${{ toJson(github.event.workflow_run.pull_requests) }}"
      
      - name: Get PR number
        id: pr
        run: |
          prs='${{ toJson(github.event.workflow_run.pull_requests) }}'
          echo "PRs JSON: $prs"
          
          # Use jq to reliably check if array is empty
          if echo "$prs" | jq -e 'length == 0' >/dev/null || [ -z "$prs" ]; then
            echo "No PR found for this workflow run"
            echo "pr=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          pr_number=$(echo "$prs" | jq -r '.[0].number')
          echo "Found PR number: $pr_number"
          echo "pr=$pr_number" >> "$GITHUB_OUTPUT"

      - name: Post @codex review comment
        if: steps.pr.outputs.pr != ''
        env:
          # Use PAT to post as user instead of github-actions bot
          # This allows Copilot to respond to the @codex mention
          GH_TOKEN: ${{ secrets.CODEX_COMMENT_TOKEN }}
        run: |
          echo "Posting @codex review comment to PR #${{ steps.pr.outputs.pr }}"
          gh pr comment ${{ steps.pr.outputs.pr }} \
            --repo ${{ github.repository }} \
            --body "@codex review"
          echo "✓ Posted @codex review comment"
