name: Codex review (after CI success)

# This workflow posts @codex review comment after successful CI on PRs
# Note: Uses workflow_run event to trigger after CI workflow completes
# This file must exist on the main branch to work (GitHub Actions limitation)

on:
  workflow_run:
    workflows: ["CI"]  # Only trigger after the "CI" workflow
    types: [completed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    # Only run when:
    # 1. CI workflow completed successfully
    # 2. It was triggered by a pull_request event (not push to main)
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow run info
        run: |
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow event: ${{ github.event.workflow_run.event }}"
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Pull requests: ${{ toJson(github.event.workflow_run.pull_requests) }}"
      
      - name: Get PR number
        id: pr
        run: |
          prs='${{ toJson(github.event.workflow_run.pull_requests) }}'
          echo "PRs JSON: $prs"
          
          # Use jq to reliably check if array is empty
          if echo "$prs" | jq -e 'length == 0' >/dev/null || [ -z "$prs" ]; then
            echo "No PR found for this workflow run"
            echo "pr=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          
          pr_number=$(echo "$prs" | jq -r '.[0].number')
          echo "Found PR number: $pr_number"
          echo "pr=$pr_number" >> "$GITHUB_OUTPUT"

      - name: Check if codex comment already exists
        id: check_comment
        if: steps.pr.outputs.pr != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if we already posted a codex review comment
          existing=$(gh api \
            "/repos/${{ github.repository }}/issues/${{ steps.pr.outputs.pr }}/comments" \
            --jq '.[] | select(.user.login == "github-actions[bot]" and (.body | contains("@codex review"))) | .id' \
            | head -1)
          
          if [ -n "$existing" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "Codex review comment already exists (ID: $existing)"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "No existing codex review comment found"
          fi

      - name: Post @codex review comment
        if: steps.pr.outputs.pr != '' && steps.check_comment.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Posting @codex review comment to PR #${{ steps.pr.outputs.pr }}"
          gh pr comment ${{ steps.pr.outputs.pr }} \
            --repo ${{ github.repository }} \
            --body "@codex review"
          echo "✓ Posted @codex review comment"
