name: Codex review (after CI success)

# This workflow posts an @codex review comment once the main CI workflow
# completes successfully on a pull request. We rely on the workflow_run event
# because it provides consistent metadata for GitHub Actions workflow
# executions (including the triggering PR), whereas check_suite can be
# inconsistent across matrix jobs and third-party providers.

on:
  workflow_run:
    workflows: ["CI"]
    types: [ completed ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  comment:
    # Only run when the CI workflow succeeded for a pull request.
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:
      - name: Debug workflow run info
        run: |
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow event: ${{ github.event.workflow_run.event }}"
          echo "Workflow ID: ${{ github.event.workflow_run.id }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Pull requests: ${{ toJson(github.event.workflow_run.pull_requests) }}"

      - name: Get PR number
        id: pr
        run: |
          pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "PR number: $pr_number"
          echo "pr=$pr_number" >> "$GITHUB_OUTPUT"

      - name: Check if codex comment already exists
        id: check_comment
        if: steps.pr.outputs.pr != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if we already posted a codex review comment
          existing=$(gh api \
            "/repos/${{ github.repository }}/issues/${{ steps.pr.outputs.pr }}/comments" \
            --jq '.[] | select(.user.login == "github-actions[bot]" and (.body | contains("@codex review"))) | .id' \
            | head -1)

          if [ -n "$existing" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "Codex review comment already exists (ID: $existing)"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            echo "No existing codex review comment found"
          fi

      - name: Post @codex review comment
        if: steps.pr.outputs.pr != '' && steps.check_comment.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Posting @codex review comment to PR #${{ steps.pr.outputs.pr }}"
          gh pr comment ${{ steps.pr.outputs.pr }} \
            --repo ${{ github.repository }} \
            --body "@codex review"
          echo "✓ Posted @codex review comment"
