name: Documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/book/**'
      - 'src/**'
      - 'examples/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'docs/book/**'
      - 'src/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Build mdBook
        run: mdbook build docs/book
      
      - name: Build rustdoc
        run: cargo doc --no-deps --all-features
      
      - name: Combine documentation
        run: |
          mkdir -p ./docs/book/book/api
          cp -r target/doc/* ./docs/book/book/api/
      
      - name: Deploy to GitHub Pages
        # Only deploy on push to main (not on PRs)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book/book
          cname: roup.ouankou.com
